### PR TITLE
Circles tree look & feel changes

### PR DESCRIPTION
**Pull request by defnax**
Improved look feel for easyer overview
* Own Tree for My Circles when im Member or Admin of the Circle
* changed to the new icons

- Orange = Invited
- Green = Member
- Blue = Admin
- Gray = Unknown

image

@csoler 
When required i can make a new color for the admin. At the moment blue,  or red
Other idea is for invited Circles own tree
But it was nice a better Invite notify, i hope you like it?

### CODE REVIEW

**Comment by csoler** [comment]
The way it is now is:
- admin: bold or not bold
- member/invited/unknown: color (green/yellow/grey)
This way, when you are both admin and member, or both admin and non member, you can see the difference between the two. 
With your color convention, you cannot.
In summary you need to different conventions for admin flag and for membership, that can be used simultaneously.

**Comment by defnax** [comment]
> * This way, when you are both admin and member, or both admin and non member, you can see the difference between the two.
>   With your color convention, you cannot.

Admin & Member blue with green circle
image

**Comment by defnax** [comment]
> * admin: bold or not bold

admin i saw newer not bold

**Comment by csoler** [comment]
maybe that is because you are not the admin of any circle. Try to create one. It should appear as bold.

**Comment by csoler** [comment]
I don't understand how you can expect to display 2 different information only using the icons' color. It doesn't seem possible to me. given that there is 2 admin states: admin / non admin, and 4 menbership states (member, invited, requested, and nothing), it means you would need 8 different icons. This is going to be very difficult for users to understand what they mean.
It seems to me that keeping the bold for admin/non admin, and 4 icons (there's just 3 now) for membership is much better. Also, the bold paradigm is used also in identities.

**Comment by defnax** [comment]
> maybe that is because you are not the admin of any circle. Try to create one. It should appear as bold.

you said admins can have no bold the text.
every time i create a circle then im admin with bold text

or you mean other admins?
i speak about only for my circles,

**Comment by defnax** [comment]
> I don't understand how you can expect to display 2 different information only using the icons' color. It doesn't seem possible to me.

Yes Blue background im Admin and inner circle green display that im a member too

But normally admin of the circle is always a member 
but i dont understand why the circle admin must join as member too via action.

**Comment by defnax** [comment]
For me the old one its not userfriendly you dont know what is what or which is my circle and where im member or admin, always i must look on the bold text or tooltips, 
i organised it better view, the colors can be changed when looks not good
image

**Comment by csoler** [comment]
sorry, but *you* know what is what in your own design idea, but I really don't think it is more clear than the existing one. We may need an external opinion here.

**Comment by csoler** [comment]
So, in your new setting, what does "My circles" mean? does it mean circles that you own (meaning your are admin)? Or does it mean circles you belong to as a member (which is not the same thing), or does it mean circles you are subscribed to (which is another thing) ?

**Comment by defnax** [comment]
> So, in your new setting, what does "My circles" mean? does it mean circles that you own (meaning your are admin)? Or does it mean circles you belong to as a member (which is not the same thing), or does it mean circles you are subscribed to (which is another thing) ?

My Circles:
Where im a Admin of a circle
where im a member in a Circle
or when im both Admin & Member

i think you dont like it my concept, 
i think you prefer this more:

My Circles:
Im Admin of Circle

Subscribed circles 
Im Member of Circle

Invited Circles:
Im Invited 

Other Circles:
im not yet a member or admin of a circle

 you said subscribed or belong to (member?), whats different

**Comment by csoler** [comment]
Subscribed state is managed automatically. You are subscribed to a circle in 3 situations: (1) when you are requesting membership (or when you're a member) and (2) when you're in the invited list and (3) when you are admin. "Subscribed" simply means that GXS will forward it to your friends, and get updates. It does not need to be displayed in the GUI. I only display it in the tooltip for debugging reasons.

**Comment by csoler** [comment]
It took me a while to find a good logic and color codes to display all this information consistently. Im not saying that you cannot do better, but I would like to make sure that in any new solution that is proposed, the same information is displayed consistently as well.
IMHO what is missing in the current master is to display membership request and invited using different colors (or using icons, whatever you prefer). For now, both are yellow.

**Comment by defnax** [comment]
> IMHO what is missing in the current master is to display membership request and invited using different colors (or using icons, whatever you prefer). For now, both are yellow.

you mean two different text colors for membership request or invited.
or two different circle icons one yellow one orange or other color.
But i prefer more one color for both for the text. 
you mean circle item or person item

for me is a good notify missed membership request & invited , often it doesnt works.
And people dont see that he is invited.

some ideas:
Better News Feed Notify when i can view the circle and join via circle link
Notify via RS Message and circle link to join for accept
Notify on People/Circles Tab, counting, colors/bold things...
maybe as Toaster/Sys tray too

**Comment by csoler** [comment]
> > IMHO what is missing in the current master is to display membership request and invited using different colors (or using icons, whatever you prefer). For now, both are yellow.
> 
> you mean two different text colors for membership request or invited.
> or two different circle icons one yellow one orange or other color.
> But i prefer more one color for both for the text.
> you mean circle item or person item

I mean different icons for membership request and invitation. For now both are yellow dots.

> for me is a good notify missed membership request & invited , often it doesnt works.
> And people dont see that he is invited.

That's true. Sometimes it doesn't work. I havn't investigated that. Could you take a look at it?

> maybe as Toaster/Sys tray too

Seems to me that most users hate toasters ;-)

**Comment by defnax** [comment]
> > for me is a good notify missed membership request & invited , often it doesnt works.
> > And people dont see that he is invited.
> 
> That's true. Sometimes it doesn't work. I havn't investigated that. Could you take a look at it?

i dont know if i have the knowledge for that and time, but when i remove mysewlf from circle on other side im still stay as member seems no update or very slow. re add again i get no membership request/invited notify 

> 
> > maybe as Toaster/Sys tray too
> 
> Seems to me that most users hate toasters ;-)

yes you are right :)

**Comment by defnax** [comment]
> I mean different icons for membership request and invitation. For now both are yellow dots.

ah ok you mean this here:
i need seperate then this 

> 		else if(am_I_invited || am_I_pending)
> 			item->setIcon(CIRCLEGROUP_CIRCLE_COL_GROUPNAME,QIcon(IMAGE_INVITED)) ;

**Comment by csoler** [comment]
yes. Should we use two shades of yellow? The chosen color needs to convey the information that you're not member yet. Could be also achieved by choosing a specific icon that let you think that something is pending (when you request membership) or that your action is required (when you are invited)

**Comment by defnax** [comment]
at the moment yellow for pending and orange for invited
image

maybe i need to correct the yellow its little bit to light

**Pull request closed without merging**
