### PR TITLE
Fix implicitly-declared operator= warnings

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
/retroshare-gui/src/TorControl/HiddenService.cpp:105: warning:
implicitly-declared 'CryptoKey& CryptoKey::operator=(const CryptoKey&)'
is deprecated [-Wdeprecated-copy]

### CODE REVIEW

**Comment by csoler** [comment]
I dont understand what you're trying to do here. There's no need for an assigment operator since the default ssigment operator is going to do exactly what you explicitely implemented. You could also remove the copy constructor which does the default as well.
I have the feeling that you got a warning somewhere in the code that uses this class that may concern the way we use it instead of the class itself.

**Comment by PhenomRetroShare** [comment]
It's here: [/retroshare-gui/src/TorControl/HiddenService.cpp:105](https://github.com/RetroShare/RetroShare/blob/502459a25a01e3136c0e8c1b05fb3b8dd72f8f4d/retroshare-gui/src/TorControl/HiddenService.cpp#L105)
```void HiddenService::setPrivateKey(const CryptoKey &key)
{
    if (m_privateKey.isLoaded()) {
        BUG() << "Cannot change the private key on an existing HiddenService";
        return;
    }

    if (!key.isPrivate()) {
        BUG() << "Cannot create a hidden service with a public key";
        return;
    }
//--- Here ---//
    m_privateKey = key;
    m_hostname = m_privateKey.torServiceID() + QStringLiteral(".onion");
    emit privateKeyChanged();
}```
How can I do it better?

**Comment by PhenomRetroShare** [comment]
@csoler : >How can I do it better?

**Comment by csoler** [comment]
> @csoler : >How can I do it better?

Answer is : no need to do it at all. The implicit copy constructor is going to copy d, which is a Shared pointer (managed by Qt). So there's no ambiguity about what happens in the copy operation.

**Pull request closed without merging**
