### PR TITLE
Create Debian source without re-cloning

### PR DESCRIPTION
**Pull request by heini**
Reworked the makeSourcePackage.sh script, so that it creates the source package directly from the checked out revision, w/o re-cloning the repository into a subdirectory. It now works similar to the package creation script for RedHat/Fedora.

### CODE REVIEW

**Comment by csoler** [comment]
I don't understand what you gain with this. It's so easy to include local commits unknowingly doing that, that I consider it a bad solution.

**Comment by heini** [comment]
What's bad about local commits? OTOH, why should I need to clone the repository again, when I already cloned it to get at the build scripts?

**Comment by csoler** [comment]
Because I'm the guy who does the packaging for ubuntu, and I want to make sure that what I'm packaging is the unaltered trunk every time. The clone operation is performed with -depth 1, which is minimal, so I prefer to keep it that way.

**Comment by heini** [comment]
What about adding an option for doing it in-place?

**Pull request closed without merging**
