### PR TITLE
Update Info.plist

### PR DESCRIPTION
**Pull request by core-code**
maybe that one works better

### CODE REVIEW

**Comment by defnax** [comment]
im not sure if your changes will work

**Comment by G10h4ck** [comment]
@core-code I am not able to test it, how did you test those changes?

**Comment by core-code** [comment]
not at all. i can test it if you make a new (test) build.

**Comment by defnax** [comment]
i made a build last week, but i shared on retroshare network, i added manually the version number to Info.plist

**Comment by G10h4ck** [comment]
@core-code @defnax if you have some macOS machine it would be great if you can investigate how to fix automatic macOS builds via github actions, and tet what come out from there.

**Comment by core-code** [comment]
@G10h4ck sorry there i got zero experience with 'GitHub Actions'.

**Pull request closed without merging**
