### PR TITLE
Fix versioning script msys2

### PR DESCRIPTION
**Pull request by hunbernd**
Made the msys2 build scripts work with the new versioning system.

### CODE REVIEW

**Comment by PhenomRetroShare** [comment]
Could you call it in appveyor.yml ?

**Comment by hunbernd** [comment]
Yes, but I think it is a bad idea.
Currently the scripts automatically update msys2.
In my experience msys2 packages are often broken, so the success of the build would depend on if msys2 is broken, not on RS is broken.

**Comment by G10h4ck** [comment]
Anyway the appveyor build should works fine right now, one should be even able do download the compiled executable, @PhenomRetroShare did you tried it?
What is missing is to integrate it in RetroShare main repository pull requests, but i have no permissions to do that @csoler  while I have it activated on my personal fork so i get notifications if one of my PR fails to build on appveyor

**Comment by G10h4ck** [comment]
Seems at same time thunder made similar modifications, can you take a look to see if it is better to solve de conflicts or close the PR ?

**Comment by hunbernd** [comment]
It would be redundant

**Pull request closed without merging**
