### PR TITLE
Update the main toolbar icons

### PR DESCRIPTION
**Pull request by defnax**
* Removed the Blue Circles from main Toolbar icons for better look & feel

### CODE REVIEW

**Comment by felisucoibi** [comment]
testing

**Comment by felisucoibi** [comment]
All icons must be same width and height

**Comment by felisucoibi** [comment]
Any news fixing this?

**Comment by defnax** [comment]
Maybe when get time im checking it again next days

**Comment by defnax** [comment]
@felisucoibi check again its now up to date with master & i has fixed the mail icon little bit

**Comment by felisucoibi** [comment]
thnks testing

**Comment by defnax** [comment]
https://github.com/RetroShare/RetroShare/pull/1835

**Pull request closed without merging**
