### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by felisucoibi**
First of all sorry for doing it, it's my first git pull, probably I'm doing it wrong, just updated the readme with the ubuntu/debian stuff to compile, I'm trying to help somehow, I'm learning to try to fix the bugs I submitted so you can keep working on real stuff.

I put the ubuntu command just to copy paste, for simple people like me, without the \ with the latest csoler instrucctions, seems to work, now compiling latest version of my fork.

### CODE REVIEW

**Comment by csoler** [comment]
actually the dependencies differ depending on which debian and ubuntu version you use. See the build_scripts/Debian+Ubuntu/control.\* files

**Comment by csoler** [comment]
Sorry but this PR is a mess: there's commits from different contributors (including me) that already are in trunk. Please clean it before I review it. Thx!

**Comment by sehraf** [comment]
@felisucoibi you may want to [rebase](https://git-scm.com/docs/git-rebase) you commits 😉

**Comment by felisucoibi** [comment]
Closed :P

**Pull request closed without merging**
