### PR TITLE
Fix UPnP

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
For version > 1.6.24 and < 1.8.0
Maybe version numbers to adjust.

### CODE REVIEW

**Comment by G10h4ck** [comment]
Phenom can you explain more widely what this PR is doing?

**Comment by PhenomRetroShare** [comment]
It seems that UPNP_DISCOVERY_SEARCH_TIMEOUT is never triggered.
So CUPnPControlPoint constructor wait for an undefined time in:
/libretroshare/src/rs_upnp/UPnPBase.cpp:999

**Comment by G10h4ck** [comment]
do you have any clue of why this is happening only with a few libUPnP versions?

**Comment by PhenomRetroShare** [comment]
No. Else I've wrote real version.

**Comment by G10h4ck** [comment]
Do I understand well that this PR is solving this issue too?  https://github.com/RetroShare/RetroShare/issues/1598

**Comment by PhenomRetroShare** [comment]
Yes

**Pull request merged**
