### PR TITLE
This commit adds the edit account functionality and also the functionality of setting a background image in the profile of a particular wire account.

### PR DESCRIPTION
**Pull request by PYRET1C**

### CODE REVIEW

**Comment by csoler** [comment]
There's a problem in this PR: lots of code is unchanged but marked as changed. This sets authorship to these lines to the wrong person.

**Comment by defnax** [comment]
yes i saw it too, need a fresh clean pr, cant see the changes on second commit

**Comment by csoler** [comment]
I assume this PR can be closed?

**Comment by PYRET1C** [comment]
done

**Comment by defnax** [comment]
@PYRET1C you get my email? last week

**Comment by PYRET1C** [comment]
no, what was it about?

**Comment by defnax** [comment]
something about imagecroper

**Comment by PYRET1C** [comment]
yeah now i see it. in your second mail

**Pull request closed without merging**
