### PR TITLE
Fixes for channels GUI

### PR DESCRIPTION
**Pull request by csoler**

### CODE REVIEW

**Comment by defnax** [comment]
i can test it maybe tomorrow night when get time.

**Comment by defnax** [comment]
thx for the fix, now background has automactily own color by the stylesheet...
but second color is now different, why you has enabled alternate row colors? thats normaly not needed

image

**Comment by defnax** [comment]
when i use the zoom, i get it visble but under the thumbnail it add extra space
always the old bug 

image

**Comment by csoler** [comment]
it's just an experiment. If you want to disable it, it's one line to remove. There's a call somewhere to serAlternateRowColors().

**Comment by defnax** [comment]
> it's just an experiment. If you want to disable it, it's one line to remove. There's a call somewhere to serAlternateRowColors().

you can see now the bug with spacing better :)

**Comment by defnax** [comment]
i found a issue not sure if happens on master... running latest board pr
i cant more make the bottom widget shorter seems there is a new fixed minimum size?
now i cant view
second thumbnail line will be not more 100% visible for 4/3 channel
image

**Comment by defnax** [comment]
here for none 4:3 channel it doesnt goe more to the limit too
image

**Pull request merged**
