### PR TITLE
Fix error in compilation with last Cpp11 g++

### PR DESCRIPTION
**Pull request by PhenomRetroShare**

### CODE REVIEW

**Comment by csoler** [comment]
We really cannot go down that path. Having these ifdef c++11 whenever we have a const in the code is simply not possible. What's is the problem exactly? Is the compiler reporting any guidelines on how to fix this?

**Comment by PhenomRetroShare** [comment]
This is the error:
/libretroshare/src/pqi/pqiqosstreamer.h:37: erreur : 'constexpr' needed for in-class initialization of static data member 'const float pqiQoSstreamer::PQI_QOS_STREAMER_ALPHA' of non-integral type [-fpermissive]
   static const float    PQI_QOS_STREAMER_ALPHA      = 2.0 ;
                                                       ^

You can have a look to this: http://stackoverflow.com/questions/9141950/initializing-const-member-within-class-declaration-in-c

**Comment by dtschmitz** [comment]
Might this be for the new branch of circle changes?? Is circles using qt5?  If so is phenom building with qmake-qt4 or qmake-qt5?  Am I barking up the wrong tree?...

...because, either an environment var should be set or /usr/bin/qmake should symlink to qtchooser which will look to ~/.config/qtchooser for a symlink from the appropriate conf (4.conf or 5.conf) in /etc/xdg/qtchooser:

`[dts@ThinkPad qtchooser]$ ls -l
total 0
lrwxrwxrwx 1 root root 25 Mar 28 13:14 default.conf -> /etc/xdg/qtchooser/5.conf
[dts@ThinkPad qtchooser]$
`

**Comment by PhenomRetroShare** [comment]
I use last arch Qt5

**Comment by dtschmitz** [comment]
Phenom, are the functions prototypes the same from cyril's circle merge?

**Comment by PhenomRetroShare** [comment]
constexpr come from C++11

**Comment by aereaux** [comment]
Would [this](https://doc.qt.io/qt-5/qtglobal.html#Q_DECL_CONSTEXPR) help resolve this issue?

**Comment by csoler** [comment]
then this is simple to solve:
- in the .h, remove the "= something" part. 
- in the .cc, add the declaration of the value:
  const float pqiqosstreamer::PQI_QOS_STREAMER_ALPHA = 2.0;

**Comment by PhenomRetroShare** [comment]
Can't get it working with RsReputations and RsServer as only header file...

**Comment by zeners** [comment]
Phenom: what do you tried? csoler suggestion in #332

**Comment by FanchTheSystem** [comment]
why not replace const by constexpr in header file ?

**Comment by zeners** [comment]
@FanchTheSystem backward compatibility i guess, i only followed csolers suggestion

**Pull request closed without merging**
