### PR TITLE
New posted card view

### PR DESCRIPTION
**Pull request by defnax**
* Added new Card View for Posted.

* Embeded text or Pictures will be visible when added
* Attached Picture will be shown too when available (for 34k pics)

Its not perfect jet but first attempt to have alternative view like how on Reddit.

It needs some improvements:
* Feature to view the post into a bigger View as popup Dialog (like how on reddit)
* Picture File attachment for Download & View Picture in a Label (for bigger pictures or gifs)   
* Hide some Text when it has to much embeded text (Notes)
* When attaching embeded html picture use same for the classic views thumbnail label

image

### CODE REVIEW

**Comment by defnax** [comment]
Fixed the issue for loading card view on first page 
Please test it

**Comment by hunbernd** [comment]
> Fixed the issue for loading card view on first page
> Please test it

It still doesn't load topics with lots of post, but I could fix it.

**Comment by defnax** [comment]
> > Fixed the issue for loading card view on first page
> > Please test it
> 
> It still doesn't load topics with lots of post, but I could fix it.

that would be great

**Comment by defnax** [comment]
Fixes & Improvements from @hunbernd 
https://github.com/hunbernd/RetroShare/tree/New-Posted-Card-View

**Comment by defnax** [comment]
closed this one,  improved one by anmo pr #1753

**Pull request closed without merging**
