### PR TITLE
Rename several items in default stack #485

### PR DESCRIPTION
**Pull request by stevensona**
Greetings,
This PR addresses #485

I didn't modify any of the underlying class names, because I do believe the original names are more accurate, but from an end user's perspective, the new names make more sense.

### CODE REVIEW

**Comment by felisucoibi** [comment]
Nice to see it done! I was doing it too, but I didn't commit because I'm new doing this things and I wasn't doing it very well, thanks for doing it!

**Comment by felisucoibi** [comment]
I used your code and updated putting the most used button first, or the ones I think are most used in retroshare, first, chat, I think it's the main goal of this program, second Files, i think is the most used thing in retroshare, after that, links, forum, etc....

https://github.com/felisucoibi/RetroGhibli/commit/2b17bee12ca2b2fd5f72a83c6b08ca2275fae46f

Thanks again.

**Comment by cavebeat** [comment]
my personal whish would be:

news feed -> news
chat lobbies -> chat rooms
channel -> Feed (as in RSS Feed in a Blog)
Posted keep posted

ping @csoler 
your comment regarding the PR?!

**Comment by csoler** [comment]
I agree with the renaming, but the various tabs should stay in the same order. Can you plz update your PR for that?

**Comment by csoler** [comment]
Also chat should preferably be "Chat rooms".

**Comment by stevensona** [comment]
@csoler I put the tabs back to their original order, and "chat" has been updated to "Chat rooms".

**Comment by csoler** [comment]
nice. Thx. It seems to me that the renaming should be made consistent throughout the GUI. For instance the "chat room" tab contains many references to "chat lobbies". That poses a problem. That happens in drop context menus, lobby creation window, etc. If you feel motivated enough, can you update them to "chat rooms" too? But be careful to _keep the naming_ in the backend. Don't change all "lobbies" into "rooms" in libretroshare and so on ;-)

The same naturally applies to "Feed", but I'm not sure yet if we should keep "Channels" or replace everything by "Feeds".

thx

**Comment by cavebeat** [comment]
I'm sure we should drop :tv: ~~channels~~, and name it :smile_cat: feeds .

**Comment by leethax666** [comment]
On this subject, maybe rename Posted to something more clear? it's confusing to explain it to new users

**Comment by felisucoibi** [comment]
Just to remember my bug report idea #485 
Simplify button names to make interface easier and compact....
"File sharing" > Files
"Chat Lobbies" > Chat
Messages > Mail
"News Feed" > remove it or move to the last an change it to "Log"
Posted > Links (its about Links to websites....)

**Comment by leethax666** [comment]
Has this been commited and made a release? I have a lot of people getting interested.

**Comment by csoler** [comment]
I haven't committed because I'm still waiting for the changes I mentioned above.

**Comment by felisucoibi** [comment]
@noflag you can try my fork: https://github.com/felisucoibi/RetroGhibli is just this the buttons renamed.

**Comment by felisucoibi** [comment]
This can be closed now, its already in the future releases and some code has been merged.

**Pull request closed without merging**
