### PR TITLE
Add JSON support to RetroShare serialization system

### PR DESCRIPTION
**Pull request by csoler**
This PR was created for testing the new serialization system without the need to clone G10H4ck's repository.

### CODE REVIEW

**Comment by G10h4ck** [comment]
It is really strange that tests failed on linux CI i have run them on my machine and all passed

[----------] Global test environment tear-down
[==========] 33 tests from 4 test cases ran. (47267 ms total)
[  PASSED  ] 33 tests.

  YOU HAVE 9 DISABLED TESTS

Memory still in use at end of program: 64 bytes.

**Comment by PhenomRetroShare** [comment]
Here the cleaned Travis Error with ++ marker for diff from my test:
[ RUN      ] libretroshare_serialiser.RsGxsGrpUpateItem
...
### These errors are expected.
RsSerialiser::size() ERROR serialiser missing!
RsSerialiser::size() PacketId: 2001003
RsSerialiser::serialise() ERROR serialiser missing!RsSerialiser::serialise() PacketId: 2001003
++RsSerializer::serialise(): ERROR. offset does not match expected size!
test_Item() size: 636
test_Item() done: 0
test_Item() sersize: 22000
test_Item() serialised:
++libretroshare/serialiser/support.h:222: Failure
++Value of: done == true
++  Actual: false
++Expected: true
++RsSerialiser::deserialise() ERROR: size mismatch!
++RsSerialiser::deserialise() pkt_size: 332 vs *size: 636
++RsSerialiser::deserialise() FAILED PACKET Size: 636 ID: 2001003RsSerialiser::deserialise() FAILED PACKET:  Version: 2 Class: 0 Type: 10 SubType: 3 Data: 020010030000027cb15604c22bf2b76ccc425b096f36a4b80000001305e986d9277fc6dd65ceeedf70dbdc510c3baeb7c40172091aa081c5f68fd4700eb3b2f80047ecdddc130cca410e898814cc7b89b479583c231abed08a1a9f7d1a67b02fe36ee6b4ce5a2c76ec10c4844a7ce99b4187a6f3b98d9bb39585da28566bc46079f2fd542d27c62cbb1774905a1d4b8c29156c611a02
++
++libretroshare/serialiser/support.h:228: Failure
++Value of: sersize2 == sersize
++  Actual: false
++Expected: true
++libretroshare/serialiser/support.h:235: Failure
++Value of: *outfi == rsfi
++  Actual: false
++Expected: true
++RsSerializer::serialise(): ERROR. offset does not match expected size!
++libretroshare/serialiser/support.h:240: Failure
++Value of: done2
++  Actual: false
++Expected: true
...
[  FAILED  ] libretroshare_serialiser.RsGxsGrpUpateItem (1 ms)
You can find entire log here: https://api.travis-ci.org/v3/job/334055502/log.txt

And You break Windows compil too:
https://ci.appveyor.com/project/PhenomRetroShare/retroshare/build/RetroShare-git-1155-738

**Comment by G10h4ck** [comment]
grep can find that type only in tests

 $ grep -rn RsGxsGrpUpateItem .
./tests/unittests/libretroshare/serialiser/rsgxsupdateitem_test.cc:100:TEST(libretroshare_serialiser, RsGxsGrpUpateItem)

I don't remember I hve touched that, and grep return the same result on master too, are the tests outdated?

**Comment by G10h4ck** [comment]
and it works on windows too now that they have updated rapidjson on mingw
https://ci.appveyor.com/project/G10h4ck/retroshare/build/RetroShare-git-json_experiments-205

**Pull request merged**
