### PR TITLE
Disable Yes button on chat room invitation if no Id selected.

### PR DESCRIPTION
**Pull request by PhenomRetroShare**

### CODE REVIEW

**Comment by csoler** [comment]
well done, except for 1 bug: if you receive an invitation but you already have IDs, one will be selected but the button Yes is still Off until you select another ID.

**Comment by PhenomRetroShare** [comment]
I don't have this bug...
And this is done by /retroshare-gui/src/gui/ChatLobbyWidget.cpp:1123

**Comment by PhenomRetroShare** [comment]
But I cannot connect to room because:
(EE) Cannot subscribe a non visible chat lobby!!
/libretroshare/src/chat/distributedchat.cc:1410

**Comment by PhenomRetroShare** [comment]
OK, Found and fixed.

**Pull request merged**
