### PR TITLE
Attempt to show extension icons for Files in channels

### PR DESCRIPTION
**Pull request by defnax**

### CODE REVIEW

**Comment by defnax** [comment]
attempted to add the extensions icons to show but it does not work im not sure why
@csoler

**Comment by defnax** [comment]
you know why this not works? @csoler

**Comment by csoler** [comment]
Did you set rootIsDecorated property in the QTreeView (in Qt designer) ?

**Comment by defnax** [comment]
> Did you set rootIsDecorated property in the QTreeView (in Qt designer) ?



> Did you set rootIsDecorated property in the QTreeView (in Qt designer) ?

no i forget that

**Comment by defnax** [comment]
i enabled but not working it shows the default tree image on mouse over, maybe the model is different coded it will not work
image
image

**Pull request closed without merging**
