### PR TITLE
chat names coloring made based on id hash

### PR DESCRIPTION
**Pull request by RetroPooh**

### CODE REVIEW

**Comment by csoler** [comment]
This is good, but if you dont mind, can you keep the GxsId type as long as possible, instead of casting it to a string? That will avoid unwanted color change the day we decide to e.g. print RsGxsId using upper case letters rather than lower case.

**Comment by RetroPooh** [comment]
sorry, i have no idea what you talking about :)

**Comment by csoler** [comment]
I'm saying: dont convert RsGxsId to std::string. Just pass it as is, and then read its bytes using id.toBytesArray()[i]

**Comment by RetroPooh** [comment]
updated version here https://github.com/RetroShare/RetroShare/pull/741

**Pull request closed without merging**
