### PR TITLE
added classic stylesheet

### PR DESCRIPTION
**Pull request by defnax**

### CODE REVIEW

**Comment by PhenomRetroShare** [comment]
Ok for me.

**Comment by defnax** [comment]
@csoler

**Comment by defnax** [comment]
@csoler can you check this?

**Comment by defnax** [comment]
it done for merge @csoler

**Comment by PhenomRetroShare** [comment]
It's stressful to wait other to merge... ;)
Be patient.

**Comment by defnax** [comment]
yes i know :)

**Comment by defnax** [comment]
@csoler

**Comment by csoler** [comment]
* the file should be in qss/stylesheets/ like other stylesheets. You need to embed it into the software like other built-in stylesheets. Look into images.qrc for that. Otherwise it will not show up in the list anyway (it doesn't on linux at least)
* also this file is really light as compared to other stylesheets. Is that normal? It's very surprising especially when you compare to the "default" stylesheet, which should be as small as possible given its name.
* the name is somewhat conflicting with the default stylesheet because "standard" sounds like default too.

**Comment by PhenomRetroShare** [comment]
@csoler : This qss is not compatible with all system them, So I ask @defnax to put it here like old qss.
It will be embedded by installer. 
default is always loaded (like when you've choose empty in list before), so this one only add white background to some widget.
By "standard" he think "like older version"...

**Comment by defnax** [comment]
or the rename to standard?

**Comment by PhenomRetroShare** [comment]
I don't know where @csoler see "standard". This "retroclassic" is fine for me.

**Comment by csoler** [comment]
ok then!

**Comment by csoler** [comment]
btw, why is appveyor not compiling fully?

**Comment by PhenomRetroShare** [comment]
Too long time:
 Failed 8 days ago in 1 hr

**Comment by defnax** [comment]
when it will be merged

**Pull request merged**
