### PR TITLE
UI cleanup

### PR DESCRIPTION
**Pull request by zapek**
- Removed HeaderFrames where it just copies the content of the window title
- Optimized some window titles
- Unified the font of the infolabels

### CODE REVIEW

**Comment by felisucoibi** [comment]
i thinks needs a code rebase

**Comment by zapek** [comment]
@felisucoibi what do you mean by code rebase?

**Comment by felisucoibi** [comment]
that i cant merge this pr with upstream rs code.

**Comment by zapek** [comment]
@felisucoibi $ git rebase upstream/master
Current branch ui_cleanup_2 is up to date.

**Comment by defnax2k** [comment]
after you removed all dont know which dialoged you opend.
i was oriented always with icon and frames.
the project is now going to develope a retroshare experts only.

on the places we need help nobodyy doing it since lots of years.
remove and renaming retroshare for experts.

**Comment by zapek** [comment]
@felisucoibi should be up to date now

**Pull request closed without merging**
