### PR TITLE
Added pinned column for forums

### PR DESCRIPTION
**Pull request by defnax**

### CODE REVIEW

**Comment by defnax** [comment]
@csoler

**Comment by csoler** [comment]
I haven't tried it yet, but what is the idea? We have a pinning system for posts already, that is controlled by the forum owner. Pinned posts display always on top.

**Comment by defnax** [comment]
you did coded pinned in a wrong column, you coded a dirty to use same column for read/unread
this kind i never do like how you did.
i maked it now more clear looks better when its have own column instead use the hybrid mode
i separeted the pinned from the read column

**Comment by defnax** [comment]
else i can show tonight how it looks before and after

**Comment by csoler** [comment]
But then you add a column that is unused for 99.99% of the posts ?

**Comment by defnax** [comment]
i forget this, then maybe we can add a option hide column when nothing pinned

**Pull request closed without merging**
