### PR TITLE
Add ntp finder to check Computer Time

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
Some of us are not in time.
Only go to ChatServer FR to see it.

### CODE REVIEW

**Comment by csoler** [comment]
I don't think that using a NTP finder is an acceptable solution:
- it calls of an external website (I know we do that for extaddr finder already)
- changing system time is not the role of retroshare
- the NTP only indicates you the actual time, not the time difference with your friend nodes, which is what matters in the first place
  The solution to detecting time discrepancies between RS users is IMHO to use the results of the RTT system.

**Comment by PhenomRetroShare** [comment]
1) Yes it calls external, like extadrr, but only when start and when received time error. And this list is editable.
2) RS don't change System time only informs user.
3) If all users are synchronized with NTP, no one have time discrepancies.

**Comment by csoler** [comment]
I'll test it tonight!

**Comment by sehraf** [comment]
i agree with cyril that the RTT service should be used instead of an external website. additionally this notice should only be used once so the user can fix his system time once and for all (so ideally you don't need to check the time on the next startup again)

**Comment by csoler** [comment]
This whole thing should be based on RTT. The cost of calling yet another clearnet service is not compensated by the gain in feature/security/etc.

**Pull request closed without merging**
