### PR TITLE
IPv6 support

### PR DESCRIPTION
**Pull request by G10h4ck**
Attempt to implement IPv6 dual stack operation in a retro-compatible non chain reaction manner

### CODE REVIEW

**Comment by sehraf** [comment]
Great to see that IPv6 support is still alive :smile: 
When this is in an usable state i can help testing (i have native IPv4 and IPv6).

**Comment by sehraf** [comment]
Since 0.6.4 is out, can this be merged now? :smile_cat:

**Comment by G10h4ck** [comment]
For the tests I have made this is ready to go

**Comment by tangdou1** [comment]
Does it supports DHT in ipv6？ When would the 0.6.5 including ipv6 be  released？ Thanks.

**Comment by G10h4ck** [comment]
No libbitdht doesn't support IPv6 and we don't plan to add IPv6 support to libbitdht ATM, we have been considering to switch to an independently maintained DHT library that supports IPv6 already. Next release will include the IPv6 support already included in master branch.

**Pull request merged**
