### PR TITLE
Update travis_makeOSXPackage.sh

### PR DESCRIPTION
**Pull request by core-code**
fix issue #2490

### CODE REVIEW

**Comment by defnax** [comment]
im not more sure, but we doesnt use more that file for compile on osx that was for github only with travis

**Comment by core-code** [comment]
so, what file do you use

**Comment by defnax** [comment]
when not possible we can do via commandline manually? then need to update the howto, maybe howto needs a PR too

**Comment by core-code** [comment]
maybe that one works ( https://github.com/RetroShare/RetroShare/pull/2493 ) but i can't test it.

**Comment by core-code** [comment]
> when not possible we can do via commandline manually?

sure. version numbers can either be added with the build system. or, afterwards by editing the Info.plist file manually or via tools like'`PlistBuddy` or `plutil`

**Comment by defnax** [comment]
maybe you can add to howto the manuall method, before creating the retroshare app

```
/usr/libexec/PlistBuddy -c "Delete :CFBundleGetInfoString" retroshare.app/Contents/Info.plist
/usr/libexec/PlistBuddy -c "Add :CFBundleVersion string 0.6.7" retroshare.app/Contents/Info.plist
/usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string 0.6.7" retroshare.app/Contents/Info.plist
```

**Comment by G10h4ck** [comment]
> im not more sure, but we doesnt use more that file for compile on osx that was for github only with travis

Well we aren't using it because our Travis CI macOS pipeline broke, but we are interested in any work in the direction of fixing it, as we have no better alternative, and i would say no alternative at all!

so @core-code if you have experience with macOS packaging you are very welcome to contribute fixing the macOS build and packaging via Travis CI or other free to use solution you might know

**Comment by G10h4ck** [comment]
Also i have heard that GitHub actions offer free CI build for open source projects, so setting up at least for macOS would be great

**Comment by core-code** [comment]
i haven't really used Qt's tools for a decade. but i can test new regarding macOS integration things like the Info.plist values.

**Comment by defnax** [comment]
maybe that needs a script or something before compile detect version and write to Info.plist
but the string doesnt worked for "CFBundleVersion", i created new build which using new Info.plist on Sunday

i do it manually to Info.plist

**Pull request closed without merging**
