### PR TITLE
Added Edit Identity button to People view

### PR DESCRIPTION
**Pull request by defnax**

### CODE REVIEW

**Comment by csoler** [comment]
Isn't there a edit identity in the context menu already?

**Comment by defnax** [comment]
Random reported on Forums that is not easy to go every time on context menu to edit Identity for Avatar.
He requested this, or he wanted a Avatar edit Button on People View

**Comment by csoler** [comment]
you dont edit an identity very often right? in this case, it's probably saving a lot of space to keep the edit button in the drop menu. If you add a button permanently for something that is really not common, isn't it a waste of space?

**Comment by defnax** [comment]
Its visible when invite button is hidden, i get idea only from Random.
Im not fan like you do all things from context menu.
It looks like before one button only visible, instead of a disabled invite button it shows a Edit one

**Comment by csoler** [comment]
ok. If it doesn't add yet another button, I suppose it's good to have.

**Comment by PhenomRetroShare** [comment]
Why not by just clicking on avatar?
This could be bordered if it is editable.

**Comment by csoler** [comment]
> Why not by just clicking on avatar?
> This could be bordered if it is editable.

I fully agree. The less buttons everywhere, the better.

**Comment by defnax** [comment]
> Why not by just clicking on avatar?
> This could be bordered if it is editable.

you can do a pr for Avatars Edit via one click, that needs recode to the avatarwidget more complex ;).
But again the AvatarDialog needs to fixed for GXS identities too.

It need then more work, maybe if you can do it via new PR :)

**Pull request merged**
