### PR TITLE
set the default size of the buttons on the chat window

### PR DESCRIPTION
**Pull request by defnax2k**
the default size its to small its never goes bigger... on big tv screen or notebook always very small.

i set a default size to look better for your eyes seems nobody see it.

before
image

after
image

### CODE REVIEW

**Comment by felisucoibi** [comment]
+1

**Comment by chelovechishko** [comment]
They are now too big for me, on ~15 px more than needed. Just average fullhd, nor big TV.

**Comment by defnax** [comment]
> They are now too big for me, on ~15 px more than needed. Just average fullhd, nor big TV.

show me a screenshot? i will look how much pixel it is

without default size it always 16- 22px .
with that caluculation on my notebook is 28px

**Comment by chelovechishko** [comment]
before
before
after
after

**Comment by defnax** [comment]
> before
> before
> after
> after

it looks misterous on your screenshots 2 different stylesheets 😅
its not main default style and settings icon looks smaller .

on my notebooks is to small 22px, on your looks lots of better with 33px

**Comment by chelovechishko** [comment]
> it looks misterous on your screenshots 2 different stylesheets

You can change stylesheets on the fly, you know?

> on my notebooks is to small 22px, on your looks lots of better with 33px

I can't understand this sentence.

This with standard theme:
after_standard

**Comment by defnax2k** [comment]
ok it looks good on your system only not on my notebook.

on W7 with big flat tv always 22px with standard.
its ugly to not use standard icon size 28-32px, before it was not a problem with qt seticonsize
image

**Comment by defnax** [comment]
closed seems it looks on every system different weight/height

**Pull request closed without merging**
