### PR TITLE
Added group icons for posted links

### PR DESCRIPTION
**Pull request by defnax**
Added group icons for posted, now backward compatible.
image

Added sorting comments via combobox
image

Added info frame for posted links group selection
image

### CODE REVIEW

**Comment by csoler** [comment]
Could you plz remove all explicit font sizes from the css file? When you say fontsize:12px, it will create very tiny text on high DPI screens. That's due to Qt not handling double resolution correctly. So you need to let Qt choose the font size, not tell it which size to use. The widgets that still have this problem in Links are:
- the create post button
- the entries in the combobox hot/new/top in the comments dialog and in the posts display

Another suggestion: when the buttons for voting are disabled, you should change the tooltip to indicate why it is disabled: "you have already voted"
Apart from that, this PR is ready to be merged.

**Comment by defnax** [comment]
> Could you plz remove all explicit font sizes from the css file? When you say fontsize:12px, it will create very tiny text on high DPI screens. That's due to Qt not handling double resolution correctly. So you need to let Qt choose the font size, not tell it which size to use. The widgets that still have this problem in Links are:
> 
> * the create post button
> * the entries in the combobox hot/new/top in the comments dialog and in the posts display
> 
> Another suggestion: when the buttons for voting are disabled, you should change the tooltip to indicate why it is disabled: "you have already voted"
> Apart from that, this PR is ready to be merged.


sorry im always in rehab not had time to fix it.

**Comment by csoler** [comment]
No worries. The message is here for when you come back.

**Comment by defnax** [comment]
> No worries. The message is here for when you come back.

i have here my notebook on rehab, i removed for that button and combobox the font size definition from qss file

**Pull request merged**
