### PR TITLE
Update and rename README.txt to README.md

### PR DESCRIPTION
**Pull request by AsamK**
Make README a bit nicer, with Markdown formatting and add compile dependencies for suse and arch.

### CODE REVIEW

**Comment by chozabu** [comment]
:+1:

**Comment by cavebeat** [comment]
:+1:

**Comment by SarcoRS** [comment]
While I did not figure yet how to add your fork as remote upstream to mine, I'll just leave a comment here.

https://github.com/AsamK/RetroShare/commit/ea8526b45ca1dbeef1c043d91862d24f634b3599#diff-04c6e90faac2675aa89e2176d2eec7d8R46

This is a mistake that you have inherited from README.txt.

The GUI binary produced after make finishes is named **RetroShare**, not **Retroshare**

**Comment by chozabu** [comment]
@SarcoRS one way is to:

```
git remote add asamk https://github.com/AsamK/RetroShare.git
```

more details here http://stackoverflow.com/questions/6022302/how-to-apply-unmerged-upstream-pull-requests-from-other-forks-into-my-fork

**Comment by AsamK** [comment]
Thanks  @SarcoRS , I fixed that.

**Comment by cavebeat** [comment]
thx @SarcoRS 

There is even a way to do it with the Webinterface of GitHub online without CLI. 
- create a new branch in GitHub branch-patch1
- Compare your branch Sarco/branch-patch1 with AsamK/patch-1 (consider the order!), and do a pull request pointing to your fork. 
  this leads to a pending pull request into your branch-patch1, you can accept it. 
- update online the changes in the file (or pull the PullRequest into a local branch without the need  adding a remote)
  *compare again AsamK/patch-1 with your branch Sarco/branch-patch1 (now the order is reversed!) and send him a pull request for his branch patch-1
- AsamK can merge your changes into his branch.

**Pull request merged**
