### PR TITLE
Changed group icons 

### PR DESCRIPTION
**Pull request by defnax**

### CODE REVIEW

**Comment by defnax** [comment]
@PhenomRetroShare this ok right?
the expert stuff what you need then you can make a PR for the changes when this is merged?

**Comment by PhenomRetroShare** [comment]
Seems OK for me.
Can you add svg for png source?

**Comment by defnax** [comment]
> Seems OK for me. Can you add svg for png source?

i doesnt have svg, its needed for you? only one color for svg source is ok?

**Comment by defnax** [comment]
@csoler can you merge this

**Comment by defnax** [comment]
@csoler

**Comment by defnax** [comment]
@csoler

**Comment by defnax** [comment]
@csoler you forget this, this is more importend then the from wire stuff

**Comment by csoler** [comment]
Does this color code corresponds to anything else in the software? Personally I don't really like the look of these icons, but it's a matter of taste. A more relevant question is: do you have them in svg rather than png?

**Comment by defnax** [comment]
> Does this color code corresponds to anything else in the software? Personally I don't really like the look of these icons, but it's a matter of taste. A more relevant question is: do you have them in svg rather than png?

yes i spoke with @PhenomRetroShare he liked it too colored, i has as svg too but for svg i generated only one color its in the pr. https://github.com/RetroShare/RetroShare/pull/2530/commits/dce14c4dec938932daba2c195022937edf398314
i can generate all colors in svg very easy,

But generally i wanted remove the old groups icons with the new one now every group has his own color that looks more nice, the outdated looks not good with ouer rs icons.
Every Group name has his own color thats realy nice, looks now not boring like before

**Comment by defnax** [comment]
@PhenomRetroShare  i can generate all colors tonight in svg too

**Comment by csoler** [comment]
No need to add the png to the repository if you already have the svg: the size is significantly smaller for a much better rendering.

**Comment by defnax** [comment]
> No need to add the png to the repository if you already have the svg: the size is significantly smaller for a much better rendering.

i will replace it tonight

**Comment by defnax** [comment]
done

**Comment by defnax** [comment]
svg added

**Comment by defnax** [comment]
@csoler @PhenomRetroShare

**Comment by defnax** [comment]
its done

**Comment by defnax** [comment]
@csoler @PhenomRetroShare please check svg done since few days

**Comment by defnax** [comment]
@csoler @PhenomRetroShare

**Comment by defnax** [comment]
@csoler you forget

**Comment by defnax** [comment]
any news?

**Comment by defnax** [comment]
its lots of days ago...svg done

**Comment by defnax** [comment]
any news? @csoler

**Comment by defnax** [comment]
@csoler

**Comment by defnax** [comment]
@csoler @PhenomRetroShare

**Comment by defnax** [comment]
@csoler

**Comment by defnax** [comment]
created this PR on 21.12.2021 
now new PR -> https://github.com/RetroShare/RetroShare/pull/2570
@csoler

**Pull request closed without merging**
