### PR TITLE
Fix Windows 7 32b Compilation from scratch.

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
And add scripts to build Libs on branch.
Good for beginners...

### CODE REVIEW

**Comment by hunbernd** [comment]
I recommend to use libssh 0.6.5 instead. It can be built without the fix.

**Comment by csoler** [comment]
libssh is not used anymore. Why would you need it?

**Comment by hunbernd** [comment]
In this case, neither protobuf is needed.

**Comment by csoler** [comment]
protobuf is indeed not needed anymore. I don't think that these two are included in the compilation anyway.

**Comment by csoler** [comment]
@Phenom: thx for all this. But please, try to make separate pull requests in the future when you're committing changes for different subjects. Huge changes in the code like this are very hard to review.

**Comment by PhenomRetroShare** [comment]
But I have to do it in same as they are linked...

**Comment by csoler** [comment]
the video preview looks terrible. What happenned??

**Comment by csoler** [comment]
seems that it comes from the _lastTimeToShowFrame thing. When removed, video looks ok again.
I also found a bug: clicking cancel while video preview is running causes a crash inside Qt. I didn't find the reason. 

Could you plz separate that PR at least in one block for VOIP, fixing the problems above, so that I can merge it? All the rest that deals with windows compilation can only be reviewed by thunder.

**Comment by csoler** [comment]
I merged the VOIP part.

**Pull request merged**
