### PR TITLE
WIP: Attempt to fix crashes caused by plugins on Windows

### PR DESCRIPTION
**Pull request by hunbernd**
Currently it turns libretroshare into a dll on Windows.

More to come...

### CODE REVIEW

**Comment by G10h4ck** [comment]
is this to be considered for merging already or it is a work in progress ?

**Comment by hunbernd** [comment]
I want to do some minor changes: fix packaging scripts, enable optimization on Windows.

Also it needs to be tested on Linux before merge.

**Comment by G10h4ck** [comment]
Ok so it is better to put WIP (Work in progress) prefix to the PR title in the meanwhile and remove it when it should be considered for merging ;)

**Comment by hunbernd** [comment]
I would add a label when I created the PR, but it seems like Github does not allow adding labels even if you are the owner of the PR.

**Pull request closed without merging**
