### PR TITLE
Added sticker support

### PR DESCRIPTION
**Pull request by hunbernd**
We need a better toolbar icon for the stickers

### CODE REVIEW

**Comment by defnax** [comment]
thank you realy nice

**Comment by defnax** [comment]
when this will be merged?

**Comment by csoler** [comment]
When Gio or myself can review this. I'm away until end of July. Sorry for the delay.

**Comment by felisucoibi** [comment]
+1

**Comment by defnax** [comment]
any news about this? hope it will be soon merged

**Comment by felisucoibi** [comment]
i'm testing it but i dont know how to add stickers

**Comment by hunbernd** [comment]
Create a folder called "stickers" inside .retroshare or your profile folder (Loc something) or next to the executable (win portable).
Put image files there, or if you make subfolders they will show up as categories. 
Restart RS. 
You will see a new button in the button bar of the chat window.

**Comment by defnax** [comment]
when this will be reviewed? @csoler you started your own ideas but you doesnt look on this?

**Comment by felisucoibi** [comment]
it works!, and tis nice, i miss when somebody post a image in a chat lweft burtton add to stickers option

**Comment by defnax** [comment]
yes i mean nice features like this is importend for rs to have more funny stuff in rs

**Comment by csoler** [comment]
Nice work! Sorry for the delay in reviewing this. I'm merging it, but I have a few suggestions on how to improve:
- when loading images, it can take some time. You may want to display a waiting cursor during the procedure, or some info to tell about what's going on.
- some images may be larger than the maximum size allowed for chat lobbies. That causes problems. Try to check the size before sending.
- add a tooltip on your new button to tell where to put the stickers.
- the new button name is not very indicative. "Stickers" would be better than "New".
- would be nice to cache the loaded images, to make the button more reactive.

**Comment by felisucoibi** [comment]
for me the most important is in a chat conversation a lobby or private When a sticker is published left button add to stickers, why? Because will be the way almost everybody will use to add stickers instead of copying in the folder manually, it's basic feature

**Comment by defnax** [comment]
on chat lobbies the stickers are compressed. loosing the quality and transparency
https://github.com/RetroShare/RetroShare/pull/1596

**Pull request merged**
