### PR TITLE
Add Gitlab continuous integration support

### PR DESCRIPTION
**Pull request by G10h4ck**
Gitlab CI is by far more powerful and flexible then the services we are using on github add support for it

### CODE REVIEW

**Comment by sehraf** [comment]
Off-topic: with the json API and the possibility of controlling (and setting up) retroshare completely autonomous, we could consider black box testing.
This can be used for regression tests like "is chat/downloads/gxs(forums)/mail  working".
Has anybody any experience with this?

**Comment by G10h4ck** [comment]
I have closed this PR and opened a new one please comment there  https://github.com/RetroShare/RetroShare/pull/1850

P.S. in GitlabCI I have put some trivial tests with JSON API, and I was thinking on a similar stuff then you like running multiple RS instances and run a bunch of test between them

**Comment by csoler** [comment]
So I have to re-read everything? Fine. But it will take me a while.

**Comment by G10h4ck** [comment]
> So I have to re-read everything? Fine. But it will take me a while.

please read my previous message

**Pull request closed without merging**
