### PR TITLE
discovery: don't remove new added locations too soon

### PR DESCRIPTION
**Pull request by sehraf**
The current code adds new locations via discovery with a "last seen" time stamp set to 0. This leads to the problem that the new location gets cleaned up within the next 10 minutes when no connection is established. This can be to fast for DHT connections when both sides are behind NAT/firewall.

This patch increases the "protection" time to 1 day by adding new locations with a sound "last seen" value.

### CODE REVIEW

**Comment by csoler** [comment]
I think that you could set it to time(NULL) directly. 

Also, a while ago, the removal of old locations always made sure that at least the most recent location was never deleted. Otherwise, the PGP key with no locations becomes useless anyway. That would be nice to re-instate this.

**Comment by sehraf** [comment]
i'm not sure if it's a good idea to add them with time(NULL) since this will add old locations with a new time stamp. but if you want it you shall get it :smile: 

the second patch adds a check that at least one location is kept (untested)

**Comment by csoler** [comment]
(minor), please do if(now > it->second.lastcontact + RS_PEER_OLD_PEER) instead of if(now - it->second.lastcontact > RS_PEER_OLD_PEER). I have had bad moments with differences between uint32_t / size_t. 

(more seriously) you always keep one location among the ones to be deleted. That's not what I meant. I meant kept at least one location among all locations. Also, you're doing a O(n^2) loop since you search each time you need to remove something. Just make a linear pass first to find the most recent location, then check that it's not the one you need to remove.

**Comment by sehraf** [comment]
Ok the minor remark is addressed now (FYI: all three values are time_t)

You are right about the clean up code - i guess i'll have to rewrite it instead (I've removed the patch for now)

Any comments about the time stamp to use when adding a location via discovery? After thinking a bit more about the problem adding a second time stamp for "last time connected" might be the best solution after all (or bool). Otherwise you may never get rid of old locations since there might be a friend that shares it just before he will delete it and then you have it and will share it for another day (or whatever time window we will use)

**Comment by csoler** [comment]
If we use a single TS for cleaning and deciding if we send in discovery, we need:
- set the delay for delete to be D1 (e.g. 90 days)
- only send in discovery if now < TS+D2   (with D2 equal to something like 30 days)
- set the TS when receiving via discovery to be "now - D2 - 1"
  Then disc-ed locations should be kept 60 days before being whipped  out, but won't be sent by discovery until connected.
  So I suppose that you were right in the first place. We just need T2 to be

**Comment by sehraf** [comment]
using this approach sounds reasonable - i'll send in a patch as soon i find some spare time

**Pull request merged**
