### PR TITLE
Fixed rsGetHostByNameSpecDNS

### PR DESCRIPTION
**Pull request by hunbernd**
Fixing things in rsGetHostByNameSpecDNS to make it work with lokinet DNS.

### CODE REVIEW

**Comment by G10h4ck** [comment]
@PhenomRetroShare AFAIR the original code is from you would you be so kind to review this PR ?

**Comment by G10h4ck** [comment]
The RetroShare repository have been split into submodules, I am sorry this happened while you had an opened PR on libretroshare. Can you move this PR to this repository? https://github.com/RetroShare/libretroshare

**Comment by PhenomRetroShare** [comment]
OK For me

**Comment by csoler** [comment]
plz could you solve the conflicts? It's ready to merge otherwise.

**Comment by G10h4ck** [comment]
I have moved this PR to the new libretroshare repository https://github.com/RetroShare/libretroshare/pull/10

**Pull request closed without merging**
