### PR TITLE
fix equal names

### PR DESCRIPTION
**Pull request by chelovechishko**

### CODE REVIEW

**Comment by G10h4ck** [comment]
did you get an error without those changes?

**Comment by chelovechishko** [comment]
I got ODR violation 6 months ago, now it is not needed for me anymore.

**Comment by G10h4ck** [comment]
by now you mean after applying this PR, or with the current master branch?

**Comment by chelovechishko** [comment]
With current master.

**Review by G10h4ck — APPROVED** [review]

**Comment by G10h4ck** [comment]
I have reviewed your patch, it make sense that the unpatched code endup in ODR violations because we use same name for same thing... also the ZeroedInt could confict easly so good to put it into a namespace

**Pull request merged**
