### PR TITLE
Fix BoardPostDisplayWidget when editor redraw.

### PR DESCRIPTION
**Pull request by PhenomRetroShare**

### CODE REVIEW

**Comment by csoler** [comment]
When I change the sorting (Top / New / Hot) ranks at left, the widget doesn't update. It does when I scroll. Could you find a way to call some update() method when we change the sorting?

**Comment by defnax** [comment]
-Switch to Card View has issues too its often slow
-after scroll the page is updated

**Comment by defnax** [comment]
> When I change the sorting (Top / New / Hot) ranks at left, the widget doesn't update. It does when I scroll. Could you find a way to call some update() method when we change the sorting?

this happens only on  card view, compact view has no issue with update

**Comment by PhenomRetroShare** [comment]
Updated.
All was in editor kept shown.
So I fix it in RSTreeView.

**Pull request merged**
