### PR TITLE
Removed outdated build scripts and information

### PR DESCRIPTION
**Pull request by hunbernd**

### CODE REVIEW

**Review by G10h4ck — APPROVED** [review]
Seems a nice cleanup to me, let's wait a bit for @csoler  and @thunder2 feedback

**Comment by csoler** [comment]
I'm ok with it too. I'm just not sure about the .bat. Maybe they are used by thunder?

**Comment by thunder2** [comment]
For me it's ok.
I only use files in build_scripts/Windows and build_scripts/Windows-msys2.

**Comment by csoler** [comment]
thx all for the confirmation. I'm merging this.

**Pull request merged**
