### PR TITLE
V0.6 channels gui

### PR DESCRIPTION
**Pull request by csoler**

### CODE REVIEW

**Comment by NyvenZA** [comment]
I tried this #2052  and it places the File name in a more readable location at the top of the tabs form. Better to read long titles. 

* When you initial go into Channels, when no post is selected,  the right click menu shows the Copy Retroshare link.  It gioves an error about an empty MsgId trying to use the menu. 

* The one difference I can now see is this build shows the image is a different Aspect ration than then current master build. The current build on the left and the new build on the right. 
image

**Comment by NyvenZA** [comment]
This build compiled and works sofar. 

I was wondering about possible looking at an alternative view for the channels that looks like this? Should probably get some feedback from people about this: 
suggestion for the channels
Went and googled images from QT  widgets and found this one. Don't know what it is called though. It might be the Thumbnail view.

**Comment by defnax** [comment]
> * The one difference I can now see is this build shows the image is a different Aspect ration than then current master build. The current build on the left and the new build on the right.
>   
image

its again to much text 3 lines for a title... or you zoomed in/out/ to get then this two or 3 lines?
i prefer only one line title ( maybe 30 characters is to much)

**Comment by csoler** [comment]
I added a list view for channels (accessible by right click on posts). Some bugs remain:
- switching to list needs to zoom/unzoom once to correct the absurd sizes and see the text
- switching back to grid needs to change widget size so that the columns automatically set again to the right size.
It's possible to add more info in the text (the delegate draws that text). In particular it's easy to draw information up to the height of the row.

**Comment by NyvenZA** [comment]
I tried this PR and it looks good so far.  It is still nice and fast. 

This item on the right click menu should probably get added to the top of the view still. 
image

I see what you mean with the ZOOM, the layout is not readable until you use the CTRL+Scroll wheel once. 
Before ZOOM
image
After ZOOM
image

Issues:
- when you click on a post on the List view, the post shifts to the left. The Thumbnail moves out of view a bit and there is no scroll bar to bring it back. 
image
If you click on the thumbnail, it moves back. 
image

My Suggestions for features :
- Change View at the top of the Page ( Buttons or drop down to the left of the search box)
- Remember the last view state across restarts. 
- (Personal preference, not a big requirement) I don't know if it is possible to have a separator line between posts, just to make it look more symmetric.

**Extra Info on the Post panel:** 
- Download button
- Comments Button 
- Comment Count and rating
- Share Button, that copies the RS Shortcut.
- First couple of lines of the Details  or a box with a scrollbar, with all the text.

**Comment by NyvenZA** [comment]
Issue:
The new post Star doesn't show properly on the Windows build with the thumbnail and list view:
image
Not sure if the thumbnail was supposed to be partial too:
image

**Comment by NyvenZA** [comment]
After updating to this version the channels look like this initially:
image
* The menu shows Switch to List view and then it shows the list properly. 
* Switching to Grid view it looks properly again. 

image

**Comment by defnax** [comment]
> I tried this PR and it looks good so far. It is still nice and fast.
> 
> This item on the right click menu should probably get added to the top of the view still.
> image
> 

But normaly its not best place to add a Switch action to the context menu...
Its needs as button normaly.. for me its on a wrong place :)

best place here:
image

**Comment by defnax** [comment]
> * The menu shows Switch to List view and then it shows the list properly.
> * Switching to Grid view it looks properly again.
> 
> image

issues:
1. to much text again 3 lines.. but we need allow only one line, the design looks bad when it has 3 lines... cut the rest
2. and when using zoom get wasted space between bottom & top Thumbnail

i prefer not to use the zoom thumbnail design goes looks more bugy
hope the zoom issues can be fixed too

**Comment by defnax** [comment]
when switching to list get wasted space
image

when switching from list to grid view i get this often under win (no zoom used)
image

**Comment by defnax** [comment]
> My Suggestions for features :
> 
> * Change View at the top of the Page ( Buttons or drop down to the left of the search box)

image

**Comment by defnax** [comment]
get always issues with the layout.
When switching to List View then the Layout always broken 
1, On List View wasted spaces
2. ON Thumbnail it gets wasted space too (when switching back)

Need to restart to have a clean thumbnail view without blank wasted spaces
I need to avoid to use the Zoom & avoid to switch to List View

image

**Comment by NyvenZA** [comment]
I am busy loading a channel that has 5 years data, to test with a large channel.
Thank you for changes so far. It is progressing nicely. 

Issues found:
* Just noticed that the if you use the Grid view and there is multiple pages of thumbnails and you then scroll use the mouse scroll wheel to scroll, it scrolls to much. I marked the first Icon in the top row and scroll and rather than scrolling one line, It looks like it scrolls more than one page. 

* Marking all as read takes a couple of seconds to start marking as read. It seems to run through all the posts sequentially and marks them as read. I can see the unread posts decreasing after a while.  If I then move to another channel, the marking stops. 

* The Files tab for a post shows that the sorting is on the file name, but it is not sorted until you actually click on the heading again to try and sort it. 
image

New Feature request:
* A button of drop down next to the View selection to "Show only Unread" and "Show All".
With the large channel loading, it takes a while to find the unread posts while trying to scroll. 

Issues address:
* The initial view of the channel after a restart looks correct now. It was not overlapping text like the picture I posted earlier in this PR.

**Comment by NyvenZA** [comment]
When moving between channels after searching for something, the search box is not cleared. The Search term is not used on the next channel page.

So one of two things should happen:
* Clear the search box ( probably the better option)
or
* Perform the same search on the next Channel page.

**Comment by felisucoibi** [comment]
Dont forget description in list mode

**Comment by NyvenZA** [comment]
Testing new version. 
When Opening the channel it is is in List View. The first Column Icons are showing and the text looks like it is drawing like the Gridview should be drawn. 

image

If I scrollwheel + Control once, it looks like the view is the list view and there is an item next to the first Item. 
image

**Other tests**

- View Unread only looks like it is working. 

- Search clear on change forum is working.

**Comment by NyvenZA** [comment]
Initial Display of the text is now working properly after a restart of RS. ([This](https://github.com/RetroShare/RetroShare/pull/2054#issuecomment-683318463) part is addressed)

**Comment by NyvenZA** [comment]
There was a PR #2052  that displayed the File name at the top of the tab. Will this be merged with this PR?

**Comment by NyvenZA** [comment]
Issue:
I enabled "Unread only" and it works. when I switch to a different channel, it is still on, but it shows all posts again. I have to turn it off and on again before it works again. 
I think it should just work if you enter a channel and you have it enabled.

**Comment by csoler** [comment]
I prefer to reset the button:
- in the code it's somehow connected to the filtering, so when we change the model it makes more sense to reset both showOnlyUnread and filter string
- if keeping that button pressed when switching channels, there is a risk that the new channel not showing anything (because nothing is unread) will raise questions.

**Comment by defnax** [comment]
it shows the wrong icon...
image

wasted spaces always there...
image
image

**Comment by csoler** [comment]
It's not really wasted space: there is space for 3 lines of text. In these posts there is only 1 line.

**Comment by felisucoibi** [comment]
ADD THE DESCRIPTION LIKE IT WAS IN CHANNELS BEFORE, SO WE CAN CLICK IN A RSLINK IN THE DESCRIPTION. USE SAME WIDTH FOR PHOTOS IN LIST AND IN THE INFO WHEN CLICK ON A CHANNEL, THAT IS RECTANGLE HORIZONTAL. IF 0 FILES DONT SAY ANYTHING. TO SEE DESCRITION NOW I HAVE TO CLICK IN THE ELEMENT TO SEE IT IN THE TABLE BELOW, BEFORE THE DESCRIPTION WAS IN THE ELEMENT TISELF WITCH CLICKABLE RSLINKS.

BTW THERE IS A BUG WITH THE FIST ELEMENT OF THE LIST VIEW I CANT SELECT IT.
imagen

**Comment by csoler** [comment]
Images do not always have the same aspect ratio, so we have a choice between two options:
1 - show the correct aspect ratio in the Details, in which case it cannot be the same than in the list otherwise all items in the list will have their own aspect ratio and the list is going to look ugly
2 - keep the same aspect ratio in both the list and Details, in which case you never see the image with its correct aspect ratio.

**Comment by defnax** [comment]
> It's not really wasted space: there is space for 3 lines of text. In these posts there is only 1 line.

maybe its windows only bug? not happening on linux?
when not using the "zoom" or not switching to "list view" the layout looks clean & good without extra space

@NyvenZA  you has this issue too when im right or?
issue comes with switch or zoom

no zoom or switched yet on fresh start:
image

after i switchted to "List View"and i go back to Grid View(Thumbnail View)
image

When using Zoom it will not help the Blank White Space will be bigger
image


When switching Back to Grid View why it doesnt have the same clean thumbnail dimensions ( no extra white spaces) like on Start?
Maybe it not good idea when both Views using same QTreeView which makes this issues?
You cant have different Zooms, Thumbnail View needs bigger View and maybe the List View smaller View...
When changing View in Líst View the Layout in Thumbnail View is destroyed or looks no so good.
For me it needs separation

**Comment by NyvenZA** [comment]
> > It's not really wasted space: there is space for 3 lines of text. In these posts there is only 1 line.
> @NyvenZA you has this issue too when im right or?
> issue comes with switch or zoom


Initial View:
image

Swapped to List view and then back to grid view. NO Zoom applied yet. 
image

Zoom to show the space  below the grid icon.
image

**Comment by NyvenZA** [comment]
Possible new issue: ( trying it on an older build as well, before the list view was build)
I have a channel that has 2002 posts going back to 2015. 
I set it to store indefinitely and it has now started downloading all the posts. Over the weekend I "marked it all as read" when about 50 new posts appeared. 
This Yesterday it hit 727 Unread posts and the "mark all as read" is not working anymore. I have tried a couple of times. 
I have now restarted RS and tried "Mark all as read" after the Post count changed from 0 to 2002.(in case there was something wrong with the multiple tries and switching channel views and showing only unread posts).  Will leave it for a while and see what happens. 

Feature request:
On the Channel Details page:
Show how many posts are actually stored locally. It reports how many posts are available in the channel remotely, but not how many i have. 
Current channel view shows 2002 posts in the channel. i have 6 months stored. I changed this to 1 year and new posts started arriving. Total posts is staying at 2002 on the details page. 

EDIT:
Restarted RS, waited for all the posts to load and then did a "Mark as Read". Looking at he Disk and CPU usage, it spiked for a couple of minutes and then stopped. None of the posts are marked as read.  The I/O graph was spiking to about 150MB/s Reads. So it was definitely reading data from files.
image

EDIT2:
I tested something that may show the issue:
1. Took the same channel on my main RS that had 78 unread posts. Viewed the I/O while it was running. 
2. Right click and select "Mark as read" and then waited for the count to reduce. I/O graph shows lots of reads. 
3. The moment the count of unread posts started to reduce, I click on a different Channel. 
4. The I/O Reads drop to nothing almost immediately and the Unread counter stops. No further posts get  marked as read.

**Comment by felisucoibi** [comment]
> Images do not always have the same aspect ratio, so we have a choice between two options:
> 1 - show the correct aspect ratio in the Details, in which case it cannot be the same than in the list otherwise all items in the list will have their own aspect ratio and the list is going to look ugly
> 2 - keep the same aspect ratio in both the list and Details, in which case you never see the image with its correct aspect ratio.

The correct answer is, leave it as it was before the new design, that was RECTANGULAR, not the VERTICAL RECTANGLE but the old HORIZONTAL RECTANGLE. So channels are like they were in the past. Don't knwo the reason to change from horizontal to vertical.

And about have the description also in list mode, will be it possible? 

Bests.

**Comment by csoler** [comment]
For image aspect ratio I propose the following:
- adding a choice for aspect ratio when creating a post (3:4, 16:9 and 1:1)
- when displaying the posts, using the aspect ratio that is the most common among posts. 
This way the aspect ratio doesn't need to be embedded in the channel data and the user doesn't have to set it either. It will be all automated.

**Comment by defnax** [comment]
one feature is missed, when using share channel permissions...
you cant see who posted the post...(Author)
it would be nice the share permissions can be used with GXS IDS..
Maybe new Feature neededed "share permissions" to a Admins/Moderators.(GXSID)

At the moment cant see who is the owner of the Channel Post.

**Comment by csoler** [comment]
> one feature is missed, when using share channel permissions...
> you cant see who posted the post...(Author)

The whole point of channels is to allow to post anonymously while ensuring that posts are always posted by the channel admin (or people who have permission to do so). I understand that when we share publish permissions, it would make sense to show who posted, while in other cases you do not want to make this information public. 

> it would be nice the share permissions can be used with GXS IDS..
> Maybe new Feature neededed "share permissions" to a Admins/Moderators.(GXSID)

I don't understand what you mean.

**Comment by defnax** [comment]
> > > it would be nice the share permissions can be used with GXS IDS..
> > Maybe new Feature neededed "share permissions" to a Admins/Moderators.(GXSID)
> 
> I don't understand what you mean.

Allow a Post feature to a GXSID 
I know there is always with "Share Permssions" to a friend.
Maybe idea when using Share Permissions why not embed this guys default identity as author? 

At the moment the Author is anonymous, maybe the Channel admin give Post rights to a unknown stranger and people downloading and using from strangers bad application.
and you never know who is guy .

on Boards you always know who is the poster.

**Comment by defnax** [comment]
another issue i doesnt found how to solve it for rs links navigate feature:

idea is something like this maybe you know it how solve that issue?

```
if (rslink == channel posts link)
{
	ui->channel_TW->setCurrentIndex(CHANNEL_TABS_POSTS);
	ui->details_TW->setCurrentIndex(CHANNEL_TABS_DETAILS);
}
else if (rslink == channel link )
{
	ui->channel_TW->setCurrentIndex(CHANNEL_TABS_DETAILS);
}
else if (rslink == channel comments link)
{
	ui->channel_TW->setCurrentIndex(CHANNEL_TABS_POSTS);
	ui->details_TW->setCurrentIndex(CHANNEL_TABS_COMMENTS);
}
```

**Comment by defnax** [comment]
hi, how can set to my channel 9:16 Poster Format?
Edit:
it looks like we has the option... seems needs store the combobox feature
but im not sure when using different formats posts on a channel how this will be look? which format will be keeped?
Normally needs one format choised by the Channel Admin.

i get now this no text more
but it doesnt keeps the Format ... when switching a channel which has 1:1 and go back to my channel.. my channel hasnt more 3:4 or its fixed
image

image

**Comment by csoler** [comment]
Channel format is determined automatically based on the 5 last posts. It looks like the display is not correct for you anyway. Which channel is this? I would like to test on my side.

**Comment by defnax** [comment]
i use since few month a Test Channel with 3:4 Format...

Now testing latest updates....the text is not so much readable but switching to other channels it does not more lose your Channel Format.
image

When zooming the text will be readable but the zoom has the old bug white white blank spaces...
image

**Comment by defnax** [comment]
But the combobox needs to keep the last used aspect ratio(store/load)..
i dont want do everytime to set my right aspect ratio for my Channel post.

**Comment by csoler** [comment]
I added a factor to scale the font. It's controlled by ChannelPostThumbnailView::FONT_SCALE_FACTOR. Seems to me that 1.5 is fine, but you can tell me. MAke sure it's ok in both msg creation window, and visualization. The same scale needs to be applied to both because it's a preview.

**Comment by defnax** [comment]
now it looks better but my 3:4 Channel has isssues with it at start...the other ones not.... 
image

**Comment by csoler** [comment]
The space keeps being wrong when you zoom?

**Comment by defnax** [comment]
> The space keeps being wrong when you zoom?

yes i told you this issue since the zoom is implemented it happens on windows on linux too?
NyvenZA has the same issue too, and  you cant remove the space manually, i need always restart and to avoid use the zoom.

between top and bottom thumbnail there it adds extra space

**Comment by defnax** [comment]
Fix for the Channel Composer
https://github.com/csoler/RetroShare/pull/17

**Comment by NyvenZA** [comment]
Mark as read is now working. 
- While I am on the channel;  
- If I click on a different channel the "mark as read" stops. 

Mark as unread works.

**Comment by csoler** [comment]
Seems that all major problems are fixed. If anything, remaining problems will be minor. So we can merge this.

**Pull request merged**
