### PR TITLE
Fixed memory leak when using tray menu of chat lobby and removed doub…

### PR DESCRIPTION
**Pull request by thunder2**
…le connect of signals
@defnax Can you try this? Maybe it fixes the crash on macOS.

### CODE REVIEW

**Comment by defnax** [comment]
Thank you i will test it tonight

**Comment by defnax** [comment]
its crashes again, i dont need clean compile or
```
1  QCocoaMenu::nsMenu() const                                                  qcocoamenu.mm                                                          102  0x110a44214    
2  ::-[QNSStatusItem triggerSelector:button:](id, Qt::MouseButton)             qcocoasystemtrayicon.mm                                                415  0x110a582cc    
3  -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:]           (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit      0x7fff44150d6d 
4  -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]                (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit      0x7fff4414d9c4 
5  -[NSWindow(NSEventRouting) sendEvent:]                                      (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit      0x7fff4414cc70 
6  -[NSStatusBarWindow sendEvent:]                                             (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit      0x7fff43f9f885 
7  -[NSApplication(NSEvent) sendEvent:]                                        (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit      0x7fff43fae236 
8  ::-[QNSApplication sendEvent:](NSEvent *)                                   qcocoaapplication.mm                                                   174  0x110a42eba    
9  -[NSApplication run]                                                        (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit      0x7fff4380e87d 
10 QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) qcocoaeventdispatcher.mm                                               429  0x110a3f623    
11 QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)            qeventloop.cpp                                                         138  0x10d5cdb6f    
12 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)                     qeventloop.cpp                                                         225  0x10d5cdb4e    
13 QCoreApplication::exec()                                                    qcoreapplication.cpp                                                   1400 0x10d5d20f2    
14 main                                                                        main.cpp                                                               590  0x10a33c006    
15 start                                                                       (x86_64) /usr/lib/system/libdyld.dylib                                      0x7fff6d4f7015 

```
image

**Comment by defnax** [comment]
or for mac we can add separate method?
instead with qmenu which lets crash rs, like how for forums

open right chat widget with the right chat room, dont know how to navigate to the right chat room
```
#ifdef Q_OS_MACOS
void ChatLobbyUserNotify::iconClickedMac(QAction* action)
{
   MainWindow::showWindow(MainWindow::ChatLobby);
}
#endif // Q_OS_MACOS
```

**Comment by thunder2** [comment]
Too bad that it doesn't solve the crash. It can be merge anyway.
@defnax Please post the last two comments in your issue #2818

**Comment by defnax** [comment]
@thunder2 my alternative fix for macos without menus please check if something is not good

- #2820

**Comment by csoler** [comment]
what do we do with this PR? It has some conflicts. It should be carefully merged with 2820.

**Comment by thunder2** [comment]
I have updated the PR.

**Comment by csoler** [comment]
@defnax : is this OK on macOS?

**Comment by defnax** [comment]
yes its ok

**Pull request merged**
