### PR TITLE
Add CommonMark in ChatLobbyDialog

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
Direct use of https://github.com/commonmark/cmark library.

### CODE REVIEW

**Comment by dtschmitz** [comment]
@csoler is there any impediment to this PR being merged?  If so, what?  Thanks Dietrich

**Comment by G10h4ck** [comment]
at some point it would be nice to detect if cmark is installed on the system and use the system version if available (on gentoo the package is named app-text/cmark so i suppose this will become common on many distro soon), but it is not urgent right now, so I would merge this and implement the detection of system library later (sehraf has done it for rapidjson if you want to take a look)

**Comment by csoler** [comment]
I'm ok with this.

**Comment by dtschmitz** [comment]
Gah:
util/HandleRichText.cpp:42:10: fatal error: gui/../../../supportlibs/cmark/src/cmark.h: No such file or directory
 #include <gui/../../../supportlibs/cmark/src/cmark.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.retroshare-gui:17195: temp/linux-g++/obj/HandleRichText.o] Error 1
make[1]: Leaving directory '/home/dts/retroshare-git/src/retroshare/retroshare-gui/src'
make: *** [Makefile:152: retroshare_gui-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
[dts@dts-pc retroshare-git]$ 
I have cmark installed.  The error is on Manjaro (Arch derivative)
cc: @sehraf

**Comment by G10h4ck** [comment]
@dtschmitz I think you need to delete the build directory and run qmake again

**Comment by dtschmitz** [comment]
All I did was run makepkg -s which runs the @sehraf PKGBUILD maintained script that includes the step for qmake etc.

`# Maintainer: sehraf
# Contributor: stqn

# Set this to 'true' to build and install the plugins
#_plugin_feedreader=true
#_plugin_voip=true

# Set this to 'true' to enable auto login
#_autologin='true'

# Set this to 'true' to enable wiki functionality (experimental)
#_wiki='true'

# Set this to 'true' to use clang for compiling (experimental)
#_clang='true'

# Unofficial plugins
#_plugin_lua4rs='true'

### Nothing to be changed below this line ###

_pkgname=retroshare
pkgname=${_pkgname}-git
pkgver=v0.6.4.r332.g82c9084ca
pkgrel=1
pkgdesc="Serverless encrypted instant messenger with filesharing, chatgroups, e-mail."
arch=('i686' 'x86_64' 'armv6h' 'armv7h')
url="http://retroshare.sourceforge.net/"
license=('GPL' 'LGPL')
depends=('qt5-multimedia' 'qt5-x11extras' 'libupnp' 'libxss' 'libmicrohttpd' 'sqlcipher')
makedepends=('git' 'qt5-tools')
optdepends=('tor: tor hidden node support'
            'i2p: i2p hidden node support')
provides=("${_pkgname}")
conflicts=("${_pkgname}")

source=("${_pkgname}::git+https://github.com/RetroShare/RetroShare.git")
sha256sums=('SKIP')

# Add missing dependencies if needed
[[ "$_plugin_voip" == 'true' ]] && depends=(${depends[@]} 'ffmpeg' 'opencv')
[[ "$_plugin_feedreader" == 'true' ]] && depends=(${depends[@]} 'curl' 'libxslt')
[[ "$_clang" == 'true' ]] && makedepends=(${makedepends[@]} 'clang')
[[ "$_autologin" == 'true' ]] && depends=(${depends[@]} 'libsecret')

# Set options for qmake
_optClang=''
_optAutol=''
_optPlugin=''
_optWiki=''
[[ "$_clang" == 'true' ]] && _optClang='-spec linux-clang CONFIG+=c++11'
[[ "$_autologin" == 'true' ]] && _optAutol='CONFIG+=rs_autologin'
([[ "$_plugin_voip" == 'true' ]] || [[ "$_plugin_feedreader" == 'true' ]] || [[ "$_plugin_lua4rs" == 'true' ]]) && _optPlugin='CONFIG+=retroshare_plugins'
[[ "$_wiki" == 'true' ]] && _optWiki='CONFIG+=wikipoos'

# Handle unofficial plugins
if [[ "$_plugin_lua4rs" == 'true' ]] ; then
	depends=(${depends[@]} 'lua')
	source=(${source[@]} 'Lua4RS::git+https://github.com/RetroShare/Lua4RS.git')
	sha256sums=(${sha256sums[@]} 'SKIP')
fi

pkgver() {
	cd "${srcdir}/${_pkgname}"
	git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
	cd "${srcdir}/${_pkgname}"

	# Handle unofficial plugins
	if [[ "$_plugin_lua4rs" == 'true' ]] ; then
		[[ -d 'plugins/Lua4RS' ]] &&  rm -r plugins//Lua4RS
		cp -r -l "${srcdir}/Lua4RS" plugins/
		sed -i -e 's/SUBDIRS += \\/SUBDIRS += \\\n\t\tLua4RS \\/g' plugins/plugins.pro
	fi

	# remove unwanted plugins
	[[ "$_plugin_voip" != 'true' ]] && sed -i '/VOIP \\/d' plugins/plugins.pro
	[[ "$_plugin_feedreader" != 'true' ]] && sed -i '/FeedReader/d' plugins/plugins.pro

	# call version scripts
	cd libretroshare/src
	LANG=C ./version_detail.sh
	cd ../..

	cd retroshare-gui/src
	LANG=C ./version_detail.sh
	cd ../..

	qmake   CONFIG-=debug CONFIG+=release \
		${_optAutol} ${_optClang} ${_optPlugin} ${_optWiki} \
		QMAKE_CFLAGS_RELEASE="${CFLAGS}" \
		QMAKE_CXXFLAGS_RELEASE="${CXXFLAGS}" \
		RetroShare.pro
	make
}

package() {
	cd "${srcdir}/${_pkgname}"

	make INSTALL_ROOT="${pkgdir}" install
}
`

**Comment by sehraf** [comment]
This pull request seems to be broken.
Why is cmark's `node.h` used? It's not meant to be used and **not** included in any packet (checken both Arch Linux and Ubunut). Instead the `cmark.h` has this comment:
```
/**
 * ## Parsing
 *
 * Simple interface:
 *
 *     cmark_node *document = cmark_parse_document("Hello *world*", 13,
 *                                                 CMARK_OPT_DEFAULT);
 *
 * Streaming interface:
 *
 *     cmark_parser *parser = cmark_parser_new(CMARK_OPT_DEFAULT);
 *     FILE *fp = fopen("myfile.md", "rb");
 *     while ((bytes = fread(buffer, 1, sizeof(buffer), fp)) > 0) {
 *         cmark_parser_feed(parser, buffer, bytes);
 *         if (bytes < sizeof(buffer)) {
 *             break;
 *         }
 *     }
 *     document = cmark_parser_finish(parser);
 *     cmark_parser_free(parser);
 */
```

Looking at the code in HandleRichText.cpp the simple interface should be sufficient or am i missing something? Thats **one** function call. Even then streaming interfaces doesn't require the `node.h` header :confused: 

Also what is the deal with `cmark_export.h` and `cmark_version.h`? Why do they have to be included in retroshare-gui? They are shipped with the system packet.
___
A bit of topic: do we really need to constantly add dependencies that need to be downloaded separately like rapidjson, cmark? I'm happy that @G10h4ck did not just check in the whole cmark tree into this repository.
___
https://www.archlinux.org/packages/community/x86_64/cmark/ (click on View the file list for cmark)
https://packages.ubuntu.com/cosmic/amd64/libcmark-dev/filelist

**Comment by G10h4ck** [comment]
I tought that the git submodule was downloaded automatically by qmake like i did with restbed, this could be fixed easly looking at how i madi it into the JSON API PR

**Comment by sehraf** [comment]
The problem is that nobody wants to download all the stuff when it is already installed on the system. Especially restbed pulls openssl ...

Edit:
`51M	supportlibs/restbed`
51M to download for nothing

**Comment by G10h4ck** [comment]
that is another topic specific of restbed there is already an iussue for that and a promise from them to fix it next stable version ;)

**Pull request merged**
