### PR TITLE
Tas branch

### PR DESCRIPTION
**Pull request by ASmith-**
Returns full functionality back to the retroshare/retroshare-gui/src/version_detail.sh file

### CODE REVIEW

**Comment by chozabu** [comment]
This has retroshare-gui alter libretroshare? why not have that bit in libretroshares version detail?

**Comment by ASmith-** [comment]
cavebeat stated "just use git describe
 v0.6.0-RC2-70-gf58e347"

Retrosharev0.6.0-RC2-70-gf58e347 for a RS06 basename doesn't provide the date of the last commit which was the lead developers Cyrils direct request to include that information. Lacking the date of the last commit specifically requested for builders to include in the RS06 basenames, downstream from the builders the potential user has far less recognition on newer vs older packages.

My modified version_detail.sh created Retroshare basename on the latest commit is: 
 retroshare0.6.0-20150823_fa54fc

**Comment by ASmith-** [comment]
My modified, pushed pull request #43 version_detail.sh file provides the Retroshare 0.6 basename using a near identical composition used by the lead developers own PPA filenames.

My basename on the latest commit is: 
retroshare0.6.0-20150823_fa54fc

That RS06 basename is composed of the tag description 0.6.0-, the actual date of the last commit minus the hyphens 20150823 and 3 bytes of the commit hash string fa54fc which is precisely as the RetroShare 0.6 lead developer Cyril requested and decided to use. Builders can easily then use the basename variable created by the modified version_detail.sh file as they wish later to rename their compiled build filenames.
.
The PPA RS06 basename (the most recent PPA release)
retroshare06_0.6.0-1.20150816.9734f32a
It appears Cyril is using 4 bytes for the last commit snippet however the basename composition with the pull request #43 version_detail.sh is keeping almost entirely with the same basename composition used now for the RS06 PPA basename.
.
The determination of the sequential version numbering going through the entire Retroshare Project master tree of commits is accurately reflecting each incremental commit added to the master also in Git RetroShare.git providing the log history of each build from 8610 on SourceForge to the most current master commit on RetroShare.git. That formula is accurate, automatically updated and provided as
mastercommits="$(($(git rev-list --count HEAD)+951))" and used by the modified version_detail.sh file in a single area in About-About svn that is incorrectly frozen now at 8613. Now with the latest commit this accurately shows 8706.
.
The modified version_detail.bat file correctly places the RFC date stamp of the latest commit used by the compiled build. This corrects simply taking the system time and date the build was compiled which has no direct connection at all when the latest commit was included. The time,date as used now can be a day or even days off of when the latest commit was added and the user would never know unless they looked back through the commit logs.

**Comment by cavebeat** [comment]
is it ok to close it?

**Pull request closed without merging**
