### PR TITLE
Added attach picture for posted links

### PR DESCRIPTION
**Pull request by defnax2k**
This pr needes to be tested and needs to be fixed.
I added this feature to let people in future use the posted links more too like as reddit clone. Maybe later animated gifs/webp or short videos too.

Its working when both using latest version with picture.
I tested lots of dont find how to fix im not expert with serialiser, cloning the same functions from channels to posted doesnt works properly.

i tested with same like channels method doesnt helped posted.h
```
struct RsPostedPost  : RsSerializable
{

	/// @see RsSerializable
	virtual void serial_process( RsGenericSerializer::SerializeJob j,
	                             RsGenericSerializer::SerializeContext& ctx )
	{
		RS_SERIAL_PROCESS(mImage);
		RS_SERIAL_PROCESS(mMeta);
		RS_SERIAL_PROCESS(mLink);
		RS_SERIAL_PROCESS(mHaveVoted);
		RS_SERIAL_PROCESS(mUpVotes);
		RS_SERIAL_PROCESS(mDownVotes);
		RS_SERIAL_PROCESS(mComments);
		RS_SERIAL_PROCESS(mHotScore);
		RS_SERIAL_PROCESS(mTopScore);
		RS_SERIAL_PROCESS(mNewScore);
	}
}
```

When get from old rs versions posted messages it doesnt gets loaded on posted listwidget.
i hope the serialiaser experts can fix the issues?
i see often:
RsGenExchange::getMsgData() deserialisation ERROR

image

@csoler or @G10h4ck can find time and fix the problem?
i hope it can be fixed soon..i wanted to make it public before i lose my work and maybe i dont have more time next weeks and month

### CODE REVIEW

**Comment by defnax2k** [comment]
icons for posted groups has same issues
https://github.com/RetroShare/RetroShare/pull/1463/commits/351e54ea0cf108f9eecc449a13704f99fec5873d

**Comment by csoler** [comment]
Hi,
I will help you in a few days, after the 0.6.5 release. I am too busy right now!
The problem mostly is that you need to make the serialization backward compatible. So put the mImage at the end of the serialization process, and when you de-deserialize, check for the remaining size. This can be done using the RS_SERIAL_PROCESS macro. Some classes do that already.

**Comment by felisucoibi** [comment]
I have some sugestions for posted, i hope one day we can talk in RS about it. I'm too busy now btw :(

**Comment by defnax2k** [comment]
@csoler you have soon time for this pr to fix?
and before fix merge the other one https://github.com/RetroShare/RetroShare/pull/1459 ?

**Comment by csoler** [comment]
I would like to wait for after 0.6.5 official is out before merging this because I'm not sure about backward compatibility.

**Comment by defnax2k** [comment]
> I would like to wait for after 0.6.5 official is out before merging this because I'm not sure about backward compatibility.

ah ok thinked 0.6.5 is released.

**Comment by defnax** [comment]
@csoler when you can fix it or @G10h4ck ? i think it will be a importend improvement for posted maybe it will increase usage on that service, hope when im right will see lots of funny posts there 😎

**Comment by defnax** [comment]
@csoler @hunbernd how to fix the file conflicts? but there is no conflicts on that qss file, web editor doesnt helps

**Comment by hunbernd** [comment]
You have to merge the retroshare master branch into this branch, then push it again.

git fetch retroshare
git merge retroshare master
Resolve the conflicts.
git commit
git push

I always use a GUI, so I'm not sure about the commands needed for conflict resolving.

**Comment by sehraf** [comment]
Rebasing is also an option

**Comment by defnax** [comment]
> You have to merge the retroshare master branch into this branch, then push it again.
> 
> git fetch retroshare
> git merge retroshare master
> Resolve the conflicts.
> git commit
> git push
> 
> I always use a GUI, so I'm not sure about the commands needed for conflict resolving.

i use Guthub desktop , never used commands
you mean it resolves the problem with qss file.

**Comment by defnax2k** [comment]
oh no sorry, i wanted only update and resolve my qss conflicts on my branch now it seems it merged here 🙈🙈

**Pull request merged**
