### PR TITLE
small patches

### PR DESCRIPTION
**Pull request by RetroPooh**

### CODE REVIEW

**Comment by defnax** [comment]
@RetroPooh thank you for the nice work.
its possible to for chat lobbies when switching id on the combobox, then display i leaved the chat room?
when i change the current id for the chat.

**Comment by RetroPooh** [comment]
@defnax I think it will be against anonymity. There is special event for signed identities already, RS_CHAT_LOBBY_EVENT_PEER_CHANGE_NICKNAME

**Comment by defnax** [comment]
> @defnax I think it will be against anonymity. There is special event for signed identities already, RS_CHAT_LOBBY_EVENT_PEER_CHANGE_NICKNAME

yes i had this issue very often, people coming & going dont say anything & no leave or entering status on the chat. 
RS_CHAT_LOBBY_EVENT_PEER_CHANGE_NICKNAME but this is not yet displaying on chat right?

**Comment by defnax** [comment]
there is a little issue on messsages:
counting of Attachments (0) is missed & we losing the tags when a message is send from composer.
rs doesnt keeps tags when compose new message or when replying.

but for drafts tags are stored.

**Comment by chelovechishko** [comment]
Say me Winnie, could add a patch to make it compilable with qt-5.15 (not considering code from this pr at all, of course):
```diff
--- a/retroshare-gui/src/gui/gxs/GxsIdDetails.cpp	2020-05-29 01:10:10.505104127 +0900
+++ b/retroshare-gui/src/gui/gxs/GxsIdDetails.cpp	2020-05-30 02:03:44.239273215 +0900
@@ -22,6 +22,7 @@
 #include <QThread>
 #include <QTimerEvent>
 #include <QMutexLocker>
+#include <QPainterPath>
 
 #include <math.h>
 #include <util/rsdir.h>
--- a/retroshare-gui/src/gui/gxs/GxsCommentTreeWidget.cpp	2020-05-29 01:10:10.505104127 +0900
+++ b/retroshare-gui/src/gui/gxs/GxsCommentTreeWidget.cpp	2020-05-30 02:03:44.239273215 +0900
@@ -24,6 +24,7 @@
 #include <QDateTime>
 #include <QMenu>
 #include <QMimeData>
+#include <QPainterPath>
 #include <QPainter>
 #include <QTextDocument>
 
```

**Comment by RetroPooh** [comment]
split to parts / obsolete.

**Pull request closed without merging**
