### PR TITLE
Add the ability to change OpMode in command line.

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
So you can change OpMode while running via ssh to get more bandwidth.
Usage: RetroShare06 --opmode [full|noturtle|gaming|minimal]

### CODE REVIEW

**Comment by csoler** [comment]
Parameters should be handled in rsinit.cc around line 350. This is better than asking Qt to do it, since it allows rs-nogui to also have the same option.

**Comment by PhenomRetroShare** [comment]
This parameter is sent to running instance.
No-gui don't manage it for the moment.

**Comment by PhenomRetroShare** [comment]
Added to RsInit::InitRetroShare.
I let the GUI part for when only one instance is setted.

**Comment by PhenomRetroShare** [comment]
Updated

**Pull request merged**
