### PR TITLE
* Fixed icon size of the group tree to display icon complete.

### PR DESCRIPTION
**Pull request by defnax**
* Fixed icon size of the group tree to display icon complete.
* Added for channel adminstrator clickable to contact easy.
* Format Channel Description when contains links or emote
* Added setting for disable Emoteicon

### CODE REVIEW

**Comment by defnax** [comment]
please review my changes @felisucoibi @G10h4ck @csoler

**Comment by csoler** [comment]
I tried it and honestly I really do not like the look of the icons: it adds colors that do not mean anything special and therefore adds information that does not help users. I think we shouldn't have icons here. Am I alone to think that way?

**Comment by defnax** [comment]
when dont want can be removed  any other feedback @G10h4ck @felisucoibi @hunbernd @PhenomRetroShare @RetroPooh  ?

**Comment by felisucoibi** [comment]
I like the work done by defnax, but i'm nobody.

**Comment by defnax** [comment]
> I tried it and honestly I really do not like the look of the icons: it adds colors that do not mean anything special and therefore adds information that does not help users. I think we shouldn't have icons here. Am I alone to think that way?

i knew from the last years you dont like icons on group trees 😅
but on this pr there is no new icons added only one fix the rest all something different has nothing todo with the group icons

- Added for channel adminstrator clickable to contact easy.
- Format Channel Description when contains links or emote
- Added setting for disable Emoteicon

i have more changes but dont commited yet then the pr goes bigger and bigger.
as you said make pr but now takes long to be checked nobody do what im doing look and feel and nice to have improvements.

**Comment by felisucoibi** [comment]
I like the pr after a few days using it. Meanwhile direct chats are gone, ghosts posts appears on forums, and gxid chats dont work properly, please let defnax take care of gui (that btw defnax changes are not going to make rs worse... i mean, actually the gui is just horrible, so why care about defnax changes?), i will create a new roadmap for 2019 just in case somebody wants to follow it. Bests.

**Comment by defnax** [comment]
> I like the pr after a few days using it. Meanwhile direct chats are gone, ghosts posts appears on forums, and gxid chats dont work properly, please let defnax take care of gui (that btw defnax changes are not going to make rs worse... i mean, actually the gui is just horrible, so why care about defnax changes?), i will create a new roadmap for 2019 just in case somebody wants to follow it. Bests.

only problem rs has no real qt developer to improve gui and make it easy for look and feel and easy rs ui.
But easy direct chat is gone. i see only expert things coming to rs.

**Comment by defnax** [comment]
more feedback please @G10h4ck  @hunbernd @PhenomRetroShare @RetroPooh  @sehraf ?

**Comment by G10h4ck** [comment]
I am more focused on libretroshare side, so let see what cyril will do about it as he cares more about retroshare-gui ;)

**Comment by csoler** [comment]
ok, let's merge this. I dont really like the look of it, but I trust the majority here.

**Comment by defnax** [comment]
we can remove it when doesnt want

**Pull request merged**
