### PR TITLE
Remove CppCheck warnings

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
When I can't, I've added #warning: Cppcheck.
3 memleak left but warned
A lot of /supportlibs/pegmarkdown/markdown_parser.c:xxx: warning: Cppcheck(constStatement): Redundant code: Found a statement that begins with numeric constant.
And unusedFunctions

### CODE REVIEW

**Comment by PhenomRetroShare** [comment]
This PR don't build under Windows, please wait before merging it.

**Comment by PhenomRetroShare** [comment]
Look fine now.

**Comment by csoler** [comment]
You have change it++ into ++it in the entire project, meaning 451 files? Seriously? I'm sorry but I cannot spend 4 hours reading all changes and make sure that there's it no name errors between iterators (that happened once already).

**Comment by PhenomRetroShare** [comment]
I've done it one by one reading all cppcheck warning.

**Pull request closed without merging**
