### PR TITLE
[Messages] Feature to expand To field 

### PR DESCRIPTION
**Pull request by defnax**
i has created this changes to view the mass mail recipients to resize the To field with recipients counting.
recreated old PR #1951

image
image

### CODE REVIEW

**Comment by csoler** [comment]
when you have many recipients, it seems that it makes the place very messy. Couldn't we use a tooltip instead?

**Comment by defnax** [comment]
it was only idea, i dont know how email clients handle it with lots of recipients for display.
Not sure if tooltip is a good idea
i know only from work, when get a lots of recipeints you can collapse the rest of recipients to view it.

**Comment by csoler** [comment]
They do the same as you did. The problem we have is that there's not much space to expand a multi-line widget.

**Comment by csoler** [comment]
Could you solve the conflicts? We could potentially merge this and improve it later on. Still, I'm comparing with what master branch currently does, and it already uses a widget with a slider to display large amounts of recipients at a time.

**Comment by defnax** [comment]
i can have a look tonight, now at work. yes it can be more improved.

**Comment by defnax** [comment]
#2660

**Pull request closed without merging**
