### PR TITLE
Added colors for the service output

### PR DESCRIPTION
**Pull request by defnax**

### CODE REVIEW

**Comment by G10h4ck** [comment]
Do this work also on non-windows platforms?

**Comment by defnax** [comment]
> Do this work also on non-windows platforms?

needs to be tested i get this thing from here, normaly cross platform feature
https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux

**Comment by defnax** [comment]
image

**Comment by csoler** [comment]
I just tested on linux. It works and for sure it makes the output more clear.

**Comment by csoler** [comment]
in the future it would be better to encapsulate the coloring into some function, because it puts some crap in the strings everywhere we use it.

**Pull request merged**
