### PR TITLE
StyleSheet Rewrite

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
Use QDarkStyle to make Standard_Dark.qss and Standard_Light.qss
Use Widget name to stylize them.
Add square in chat page parameters to check system setup.

### CODE REVIEW

**Comment by defnax** [comment]
i see it looks now different with light on my notebook w10
Fusion style is used
the avatars are now bigger:
image


image
image
image

**Comment by felisucoibi** [comment]
+1

**Comment by defnax** [comment]
👌

**Comment by defnax** [comment]
everything on default is grey and we doesnt use more header background color for the titles this blue one
image

Normal Fusion style on Windows 10 at the moment looks nice  
image

**Comment by defnax** [comment]
i ignore the grey stuff but the fonts are small unreadable
image

**Review by csoler — CHANGES_REQUESTED** [review]
Impressive amount of changes! The UI looks much more consistent with them.
A few suggestions:

- Darkstyle + gtk2: causes light grey lists on white background (network, preferences, identities at least) that are hardly readable.

- My files -> Visibility column shows truncated text.

- when switching between styles / stylesheets, set cursor to Qt::WaitCursor. That will help the user understand that something's currently going on, because it usually stalls for more 2 secs.

**Pull request merged**
