### PR TITLE
Fixed Windows compile of FriendServer

### PR DESCRIPTION
**Pull request by thunder2**

### CODE REVIEW

**Comment by defnax** [comment]
@G10h4ck @csoler please merge

**Comment by G10h4ck** [comment]
> @G10h4ck @csoler please merge

Seems @thunder2 is still working on it.

@thunder2 can you notice us when it is ready?

**Comment by thunder2** [comment]
It's ready. I had to add some libaries for linking with MSYS2. Native Windows build works without it.

**Comment by G10h4ck** [comment]
> It's ready. I had to add some libaries for linking with MSYS2. Native Windows build works without it.

The PR seems pretty good to me, @csoler is the original author of friendserver so let's wait him to have a look and merge the PR

**Review by G10h4ck — APPROVED** [review]

**Comment by csoler** [comment]
perfect! Thx.

**Pull request merged**
