### PR TITLE
Add ShowEmpty sub menu in Tree Remote SharedFilesDialog.

### PR DESCRIPTION
**Pull request by PhenomRetroShare**

### CODE REVIEW

**Comment by csoler** [comment]
There's a few bugs:
- headers sometimes show "Column -1"
- when unsetting "show empty" some lines become empty but the directories are not packed upward. This is not very nice. I suppose that calling a PostMod() or update function after telling the RemoteDirModel that things have changed, it needed

**Comment by PhenomRetroShare** [comment]
Updated.

**Comment by felisucoibi** [comment]
+1 waiting for this pr

**Comment by felisucoibi** [comment]
I hope this pr is ready for 0.6.4 son also flat mode can be updated to hide older than x days files, when sorting.

**Pull request merged**
