### PR TITLE
V0.6 boards gui

### PR DESCRIPTION
**Pull request by csoler**
Re-designing the internals of boards so that it supports proper sorting and so on. As a first shot, I'll be using PostedCardView for a widget (which looks like reddit) but if anyone has a better idea for a design, now is the time.

### CODE REVIEW

**Comment by defnax** [comment]
hi, but you are not removing the classic view i hope not? we need always two choices which want to use classic or card one

**Comment by NyvenZA** [comment]
Can you bring this PR forward to be inline with the master to allow compiling on Windows like the current master? There were some changes made on the master to allow Windows Compiling to work better.   

I had to remove the "clang" and "tor" parameters from the command line option to allow the compile to work.

**Comment by NyvenZA** [comment]
PR2026 compiles and works after the Upstream merge. 

Feedback:
* The boards load nice and fast. 
* I could not get it to crash by clicking between boards all the time. ( This used to crash mine)
* I like this new screen layout. 

Issues:
* If you resize the main for of RS, the Thumbnails do not resize properly. They seems to stay the same size as the max view. If you go out of the board and come back to the board, the Thumbnails resized properly to the current width. 

* Show Author in People tab doesn't work for me. 

* If you have the Comments view open, with some comments showing and you move your mouse to another thumbnail, the comment disappears on the comment view. Once I hover over the thumbnail with the comments again, the comment appear again.  

* Using the Upvote button on the Thumbnail, I didn't see the upvote count up until i clicked on another board and then came back.  Tried to upvote the same post on the old Board and it didn't work at all. So this is already one step forward.

**Comment by csoler** [comment]
> If you have the Comments view open, with some comments showing and you move your mouse to another thumbnail, the comment disappears on the comment view. Once I hover over the thumbnail with the comments again, the comment appear again.

Although I fixed the other ones, this one is actually very hard to fix. To understand why, here's some details: 
- Qt uses a delegate to display widgets as a pixmap when unused, and as a real widget when your mouse is on the item.
- the pixmap and the widget are generated by the same class: BoardPostDisplayWidget, from the post details supplied by the item model below.
Everytime you move your mouse from an item to another, a new widget is created, either for editing (real widget) or only for display (widget rendered into pixmap, then pixmap displayed).
- the loading of comments is asynchronous: when creating the widget, the comments are not available and the comments box will be empty.

So the reason for the bug is that you leave a true widget that has time to load its comments (asynchronously) for a widget that is immediately created and statically displayed as a pixmap, before it can even load its comments.

So have multiple options:
- wait for comments to load to get it synchronous. This is a bad idea because it will slow down the whole display of the list of items.
- keep loaded comments in a cache and get them from the cache first, then request them. This is implmented now in the branch, but doesn't fully work because apparently the comments do not display nicely. Maybe a adjustSize() is missing.  
- always render the true widgets in a pixmap, that is also kept in cache. When unused widgets are rendered, use the pixmap from the cache. That could work, but I haven't checked yet. The disadvantage is that unused widgets will not show new comments until you activate them again with the mouse. 
- when the comments are not loaded, display some text saying "Comments will load when you use the widget", or something similar. 
- keep the created widgets in cache (in both cases: , so that they are not re-created when used again. This looks more promising than other options. Disadvantage: larger memory requirements, although we could easily clear the cache when the board is changed.

**Comment by defnax** [comment]
Found a big issue....
adding the comments at the bottom of the tree its not good idea the comments has no space...
or we will use for few comments... for mass comments not useable

we need the comments view into tabs, why we have now tabs? we can use the tabs to view every posts into new tab then we can view more replies/comments into bigger view.

1. Show the Post into new tab when we want comment it with exanding feature for comments dialog 

image
image

**Comment by defnax** [comment]
the old comments view was more useable into tabs you has more space for comments...
i think the comments are now added into a not useful place

on my 15,6 inch notebook best place is into tabs

image

**Comment by csoler** [comment]
I never saw a lot of comments. Also there's a slider, so you can browse into the comments. Finally, i took inspiration from reddit and twitter.

**Comment by defnax** [comment]
> I never saw a lot of comments. Also there's a slider, so you can browse into the comments. Finally, i took inspiration from reddit and twitter.

yes when the a board has no comments or less comments under 10 then it doesnt needs much space...
i mean we has tabs we can use as option open into the tab when we have to much comments.

but on reddit the post opens when click on Comments button into new popup Window on classic/card view
on twitter you can open the full thread into new window too.

**Comment by defnax** [comment]
on classic view (4-5 comments)
i can use the scrollbar but when we have to much replies/comments that will be hard to view all comments
image

on card view its not useable...
image

**Comment by defnax** [comment]
i has another issue that was not present on old Card View...

i cant view more properly a Image Post, maybe it doesnt fits on my 15,6 inch Notebook.
when using mouse i doesnt get more fit one post properly. maybe now the images are bigger displayed then before?

image
image


normaly when a post is active it must be fit on your screen... 
i need to use now the right scrollbar more...
maybe issue with scrolling too it scrolls via mouse to much

**Comment by csoler** [comment]
it seems that Qt scrolls the widget automatically to align the current widget to be visible. So when you move the mouse over items, some scrolling may happen. I couldn't find an option in QTreeView to disable this.

**Comment by csoler** [comment]
ok. Isee what you mean about size: Qt doesn't automatically let the comments window grow large enough to see all comments. So let me do this:
- see if we can remove the auto-scrolling, which is anyway quite annoying
- if not, use tabs for comments, but only in card view. Actually I really hate tabs. Do you think we could use a dialog for comments in card view?

**Comment by defnax** [comment]
one last issue the hover effect on Card View it disturbs me.

**Comment by defnax** [comment]
> * if not, use tabs for comments, but only in card view. Actually I really hate tabs. Do you think we could use a dialog for comments in card view?

you mean as popup dialog?
i prefer as tabs for comments in card view

**Comment by defnax** [comment]
* one issue the hover effect on Card View it disturbs me.

* another issue now when you want scroll on the comments you can lose the active post on classic view.

**Comment by defnax** [comment]
> * if not, use tabs for comments, but only in card view. Actually I really hate tabs. Do you think we could use a dialog for comments in card view?

other idea is with stacked widget... like we how on twitter with back button for a full thread view...
when clicking on comments view the comment into the new stacked page and go back via "<" Back button
* StackedWidgetPage 1 = QTreeView
* StackedWidgetPage 2 = PostedItem or CardView + Comments Dialog.
Maybe with Tabs is easyer, there can view more Posts/Comments into more tabs

**Comment by csoler** [comment]
ok I agree with you: we should probably use tabs. So I will do that: use tabs where the tab contains the widget with small image on top (which is provided by the same widget we use for the item list in classical list view). This way the sync problems will also be gone since the list view will not show comments either.

**Comment by csoler** [comment]
I switched to tabs, but you will see that the layout is not working. I tried to fix that layout for about 2hrs and I couldn't. Sometimes Qt really drives me mad.

**Comment by defnax** [comment]
> I switched to tabs, but you will see that the layout is not working. I tried to fix that layout for about 2hrs and I couldn't. Sometimes Qt really drives me mad.

i see it, maybe the problem is in BoardPostDisplayWidget.ui
you used there VerticalLayout.... possible to use GridLayout will solve it.

VerticalLayout gets issues that the Bottom Widget will not stretch to top
on PostedItem we used GridLayout for widget or on frames
image

**Comment by csoler** [comment]
Well, if you can find a proper way to do it, that'd be great. The problemis mostly that we use the same widget for the list items and displaying the comments, so when you adapt the widget for one place you need to make sure it still look ok in the other place. In the end, maybe we should use two different widgets.

**Comment by defnax** [comment]
yes i prefer new widget too on comments, playing on the layout no success, best no VerticalLayouts 
or modify Posteditem & use it there

**Comment by csoler** [comment]
the problem seems to be mostly that GxsCommentDialog doesn't like having another widget aligned vertically above it. If not, it takes all the room as expected. So I changed the code so that only comments are displayed in the comments tab, not the items. Maybe we can improve it later, but honnestly I can leave with this, after wasting so much time trying to get this to work.

**Comment by NyvenZA** [comment]
Adding my findings too:
RetroShare Version: 0.6.5-1962-g1f253f6bf
Windows 10 Version 1909 QT 5.15.0

libretroshare
 - bzip2: 1.0.8, 13-Jul-2019
 - OpenSSL: OpenSSL 1.1.1g  21 Apr 2020
 - SQLite: 3.31.0
 - SQLCipher: 4.4.0 community
 - UPnP (MiniUPnP): 2.1.20190824
 - Zlib: 1.2.11



### COMMENTS

1. The comments button doesn't have TEXT visible, if the window is to small. See the green Circles on the images.
1.1 Is the TEXT not redundant by now, should just the ICONS not be used when in compact mode? 

2. When I click the Comments button, a TAB opens at the top, but it does not auto-focus. 
2.1 So I now have to click another TAB before I can see or post new comments. (Quality of life issue) This should probably switch automatically. 
2.2 The Identity I am viewing the board as, is shown at the top of the window. When i click a comment, It shows the same user there, when i add a comment, it is the same user. 
If I change the identity on the Comment page at the top, and try and add a comment, it is still on the original Identity, not the switched one. 
Same with changing the Identity on the posts page and clicking on the comments, the identity is swapped to the original identity. 

3. When I upvote a Comment, it closes the comments. Now I have to open it again to vote again or to do anything on the comments. 


### UI
1. In compact view, the entire panel resizes a little bit when your mouse moves over the panels. The Active panel is always a little larger than the rest. This moves the Mark as read, comments and other "buttons" / "links", you can click on. This is annoying, since I am trying to mark the post as read but the green dot shifts away when i try and click on it. See the blue lines on the two images. 

2. Mark as Read ( The green dot) doesn't seem to work properly. I have marked one post as read manually by clicking on the dot, then the same on the next post. The first post is the marked as new again. 
2.1 Should the post not also be marked as read when you click on the images?
2.2 Mark all as read also doesn't seem to work. The Board still shows 10 unread. 


3. There is an issue with the sort still. 
3.1 Sorted by TOP. Upvoted the top post (since it was good) and the post disappeared. I then had to change the order to new and back to TOP and then it was back at the top. 


TOP Post focused
image


BOTTOM post Focused
image

**Comment by defnax** [comment]
> 
> TOP Post focused
> 
> BOTTOM post Focused

image


this issue was not present on old boards every thumbnail had same dimensions... like the comics takes lots of space when keeping the ratio

* Every Thumbnail ends on different place
* Every title text starts on different place
* Every Button & Labels are on different places...

i dont like yet that we use for every thumbnail own dimensions it doesnt look good for me

**Comment by defnax** [comment]
old one has bether layout

Thumbnails & Text & Buttons are on right places...
image

**Comment by defnax** [comment]
here reddit
nice layout text & buttons are always on right place:
image
image

**Comment by defnax** [comment]
this new layout for card view looks not more good too

image

best is we have two .ui files for a view... like on the old boards...

it will be hard to fix layout issues when a ui is used on two different views
that was the reason i created new ui for the Card View then can easyly fix layout issues

**Comment by csoler** [comment]
You're probably right. I'll split the class into two (and keep common functionality between them in a base class).

**Comment by defnax** [comment]
the buttons are on wrong places on the pr but now its easier to fix this for card view since it has own ui.
thx for the improvements
my design is like this
image

**Comment by defnax** [comment]
i has stylesheets fixes 
https://github.com/csoler/RetroShare/pull/18

**Comment by defnax** [comment]
i has found a issue on darkstylesheets... seems similiar issue like the channel thumbnail background white color.
the background of the QWidget stays always white im not sure why but the hover effect color works on the QWidget.

i has tested to get the QWidget background color in other colors but no sucess always it stays white

image


my improvements for darkstylesheet 
https://github.com/csoler/RetroShare/pull/19

for the darkstylesheet-v2  i need to fix it too maybe the next days

**Comment by csoler** [comment]
I know about this problem. Maybe I found a way to fix it in the new channel branch. I'm not sure.

**Comment by NyvenZA** [comment]
* Mark as read is now working. 
* Mark all as read is now working. 

The Images in compact view is auto sized, and this causes the Comments and Share buttons are moved based on the size of the image. I think it should be aligned to look better. 

image

**Comment by csoler** [comment]
There's multiple ways to fix this:
- flush the image at right and all the text + buttons at left.
- flush the buttons at right, leave the title next to image as it is now
I prefer the first one. Problem is that the title and the image both have varying sizes, so it's not possible to put anything after them.

**Comment by defnax** [comment]
the issue is only with the thumbnails...
it looks ugly when every thumbnail has different dimensions...

i prefer the old design like reddit with 16x9
image

**Comment by defnax** [comment]
> The Images in compact view is auto sized, and this causes the Comments and Share buttons are moved based on the size of the image. I think it should be aligned to look better.
> 
yes the images are the problem with autosize ... not the buttons/labels itself...
best fix is we need fixed dimensions for thumbnails at the moment chaotic design with the autosize

**Comment by NyvenZA** [comment]
Build still fails

make[2]: *** No rule to make target 'C:/Users/USER/Documents/GitHub/RetroShare/retroshare-gui/src/gui/Posted/images/comments_blue.png', needed by 'temp/qrc/qrc_Posted_images.cpp'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/c/Users/USER/Documents/GitHub/RetroShare-msys2/builds/Qt-5.15.0-x64-Clang-release/retroshare-gui/src'
make[1]: *** [Makefile.retroshare-gui:45: release] Error 2
make[1]: Leaving directory '/c/Users/USER/Documents/GitHub/RetroShare-msys2/builds/Qt-5.15.0-x64-Clang-release/retroshare-gui/src'
make: *** [Makefile:157: retroshare_gui-make_first] Error 2

Build failed

**Comment by csoler** [comment]
about image size, I understand your concerns defnax, but there is no optimal solution: either you squeeze the image in one direction or the other, or you crop it. There's no way to have all image occupy the same space if they do not have the same aspect ratio.

**Comment by csoler** [comment]
We could obviously use the same trick than in channels: 
1 - determine optimal aspect ratio based on the size of all images (or the last 5 ones) 
2 - crop all images in that aspect ratio.

**Comment by defnax** [comment]
> We could obviously use the same trick than in channels:
> 1 - determine optimal aspect ratio based on the size of all images (or the last 5 ones)
> 2 - crop all images in that aspect ratio.

thats good idea, but i prefer default aspectio ratio with 4:3 and crop the image

**Comment by defnax** [comment]
> about image size, I understand your concerns defnax, but there is no optimal solution: either you squeeze the image in one direction or the other, or you crop it. There's no way to have all image occupy the same space if they do not have the same aspect ratio.

but on reddit they dont do autosize....i think they crop pictures into 4.3 format

image
image

**Comment by csoler** [comment]
ok, let's crop then. I'll use the same trick than on channels.

**Comment by defnax** [comment]
you forget to check my pr for darkstylesheet fixes and ui changes look like reddits card view more https://github.com/csoler/RetroShare/pull/19

**Comment by defnax** [comment]
this doesnt looks good...
the buttons are far away...for me more not good design...i prefer comments button with text...
image

i can say the old posteditem has better design layout like reddit layout
image

**Comment by defnax** [comment]
* darkstyle stylesheet fixes and ui changes look like reddits card view csoler#19

* another fix for the standard stylesheet  https://github.com/csoler/RetroShare/pull/20

**Comment by NyvenZA** [comment]
* When Viewing a new image on a board, the post doesn't get marked as "read". 
* When clicking on a Comment it still reverts to the first identity in the drop down list, rather than the currently selected Identity. 
* When Adding a new comment, it also reverts to the first identity in the drop down list. 
* when adding a new post, the first Identity in the list is selected and not the current selected ID. 

I see that the images are now cropped to fit in a specific aspect ratio
image


Working:
* Mark as read. 
* Alignment is better on the images and buttons.

**Comment by defnax** [comment]
some missed things:

* Add back "Comments" with counting text for the Comments Button
* Add for the zoomable Label back the blue hover border color
* Add the classic view to the top of the comments dialog back
* Fix to get work the rs links for boards posts
* Fix the "NEW" state to get work the background colors when post is a new post

**Comment by defnax** [comment]
what i wonder why pictures doesnt fit to the bottom of the widget
image
image
some classic view posts gets bigger height, not sure why not all have same height, only its ok when title needs two lines ore more then there it can be expand little bit

it looks like posts which has short title , at bottom no extra space
image

**Comment by defnax** [comment]
> * When Adding a new comment, it also reverts to the first identity in the drop down list.

yes when adding a new comment the tab closes automaticly, i has this issue too

**Comment by defnax** [comment]
other issue the new posts doesnt gets more the background  color when its a new post...
this works on channels, forums and boards normaly you can see often on news feed too
screenshot is from older boards system not from the new boards pr
image
image


```
/*Property Values at end to overwrite other settings*/

[new=false] {
	background: #202020;
}
[new=true] {
	background: #005000;
}

[WrongValue="true"] {
	background-color: #702020;
}
```

````
GxsChannelPostItem > QFrame#mainFrame[new=false] {
	border: 3px solid #D3D3D3;
	background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #F2F2F2);
	border-radius: 10px;
}

GxsChannelPostItem > QFrame#mainFrame[new=true] {
	border: 3px solid #82B9F4;
	background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #F0F8FD, stop:0.8 #E6F2FD, stop: 0.81 #E6F2FD, stop: 1 #D2E7FD);
	border-radius: 10px;
}
````

**Comment by csoler** [comment]
> some missed things:
> 
>     * Add back "Comments" with counting text for the Comments Button

The problem with the counting is that it will make the buttons to not align anymore. So in the compact view, I use a blue icon+tooltip to notify about existing comments. 

> 
>     * Add for the zoomable Label back the blue hover border color

Isn't that a CSS problem?

> 
>     * Add the classic view to the top of the comments dialog back

Could you do it? I'm not sure how to achieve this.

**Comment by defnax** [comment]
> > ```
> > * Add for the zoomable Label back the blue hover border color
> > ```
> 
> 
> Isn't that a CSS problem?

no, QLabel doesnt supports hover stylesheets by default.
to look like a Button hover i added for the **ClickableLabel** class a border stylesheet
i dont know if its possible from a css file to set the stylesheet for the enterEvent(); or leaveEvent();

`   void enterEvent(QEvent * /* ev */ ) override { if(mUseStyleSheet) setStyleSheet("QLabel { border: 2px solid #039bd5; }");}
    void leaveEvent(QEvent * /* ev */ ) override { if(mUseStyleSheet) setStyleSheet("QLabel { border: 2px solid #CCCCCC; border-radius: 3px; }");}`

that was the reason i added a  clickable label + the hover effect
https://stackoverflow.com/questions/40729040/how-to-create-qt-label-hover-effect

> > ```
> > * Add back "Comments" with counting text for the Comments Button
> > ```
> 
> 
> The problem with the counting is that it will make the buttons to not align anymore. So in the compact view, I use a blue >icon+tooltip to notify about existing comments.

But bring back the text back it doesnt looks good without naming

**Comment by defnax** [comment]
the buttons are to small on my notebook now
i need minimum 24-27x pixel
now by default its 16x
image

before:
image

**Comment by csoler** [comment]
about button sizes, this is surprising that all over the GUI you use the default button size, and in this place only you need to scale them by 50%.

**Comment by defnax** [comment]
>  you disabled the scaling, but where is the new 50% scale ?

I didn't restored the 50% scale. It looks bad on my screen: the icons look too big and sizes a inconsistent with the size of other icons in the UI.

**Comment by defnax** [comment]
> > ```
> > * Add the classic view to the top of the comments dialog back
> > ```
> 
> 
> Could you do it? I'm not sure how to achieve this.

or we can use the PostedItem class? then we dont need modify the compact widget.
PostedItem always used in News Feed Notify too.

seems you removed the header frame completely "postFrame"
it makes me harder to test the posteditem there
image

**Comment by defnax** [comment]
@csoler you has not added back the "new" for the frame readstatus can you fix that isue?
without that feature the color change via stylesheet not works more (when post is new)
https://github.com/RetroShare/RetroShare/pull/2026#issuecomment-702297990

```
	ui->mainFrame->setProperty("new", isNew);
	ui->mainFrame->style()->unpolish(ui->mainFrame);
	ui->mainFrame->style()->polish(  ui->mainFrame);

```

```
void BoardPostDisplayWidgetBase::setReadStatus(bool isNew, bool isUnread)
{
	if (isUnread)
        readButton()->setIcon(FilesDefs::getIconFromQtResourcePath(":/images/message-state-unread.png"));
	else
        readButton()->setIcon(FilesDefs::getIconFromQtResourcePath(":/images/message-state-read.png"));

    newLabel()->setVisible(isNew);

}
```

PostedItem class
```
`void PostedItem::setReadStatus(bool isNew, bool isUnread)
{
	if (isUnread)
	{
		ui->readButton->setChecked(true);
		ui->readButton->setIcon(FilesDefs::getIconFromQtResourcePath(":/images/message-state-unread.png"));
	}
	else
	{
		ui->readButton->setChecked(false);
		ui->readButton->setIcon(FilesDefs::getIconFromQtResourcePath(":/images/message-state-read.png"));
	}

	ui->newLabel->setVisible(isNew);

	ui->mainFrame->setProperty("new", isNew);
	ui->mainFrame->style()->unpolish(ui->mainFrame);
	ui->mainFrame->style()->polish(  ui->mainFrame);
}`
```

**Comment by defnax** [comment]
https://github.com/csoler/RetroShare/pull/23

**Comment by defnax** [comment]
you forget to add the dummy picture... without it will not look good on compact view
            else if (mPost.mImage.mData == NULL)
                ui->pictureLabel->hide();
            else
                ui->pictureLabel->show();

**Comment by csoler** [comment]
but the image is hidden, so you don't need to add anything in it right?

**Comment by defnax** [comment]
> but the image is hidden, so you don't need to add anything in it right?
yes but when you have mixed board posts with image. without image or with link layout will look ugly
i did same like how on reddit for PostedItem class
image


```
		else if (urlOkay && (mPost.mImage.mData == NULL))
		{
			ui->thumbnailLabel->setPixmap(FilesDefs::getPixmapFromQtResourcePath(LINK_IMAGE));
		}
		else
		{
		        ui->thumbnailLabel->setPixmap( QPixmap(":/images/thumb-default.png"));
		}
```

**Comment by defnax** [comment]
here it will not look good
image

**Comment by defnax** [comment]
here on PosteItem class on news feed this look better
image

**Comment by csoler** [comment]
ok that makes sense.

**Comment by defnax** [comment]
why the default thumbnail are bigger?
image

**Comment by defnax** [comment]
i have here few stylesheets fixes from few days ago
https://github.com/csoler/RetroShare/pull/23

**Comment by defnax** [comment]
but the share button with copy rs link is now on the pr non functionality
but how will the signal will work there?
i know you are context menu lover, but easier is find the functionality on a button or button menu.

but you added the importend features on the wrong class, how can connect the slot which is in class **PostedListWidgetWithModel**
i has no experience with it maybe you know it without to move the slots into class **BoardPostDisplayWidgetBase**

```
void PostedListWidgetWithModel::copyMessageLink()
void PostedListWidgetWithModel::editPost()
```


```
    QAction *CopyLinkAction = new QAction(QIcon(""),tr("Copy RetroShare Link"), this);
    connect(CopyLinkAction, SIGNAL(triggered()), this, SLOT(copyMessageLink()));
 

    QMenu *menu = new QMenu();
    menu->addAction(CopyLinkAction);
```

**Comment by csoler** [comment]
There's multiple constraints here:
- you need a "Edit" button. That cannot be in "share". It would not make sense at all.
- the Edit needs an access to the group flags
So in the end, edit must be at the level of the PostedListWidgetWithModel class.
I suggest that we move "show author in people tab" to the context menu as well. This thing has nothing to do in a "share" menu, right?

**Comment by defnax** [comment]
something like this but i had less experience and success with connect when it on ex

> There's multiple constraints here:
> 
> * you need a "Edit" button. That cannot be in "share". It would not make sense at all.
> * the Edit needs an access to the group flags
>   So in the end, edit must be at the level of the PostedListWidgetWithModel class.
>   I suggest that we move "show author in people tab" to the context menu as well. This thing has nothing to do in a "share" >menu, right?

im not fan of the hidden context menu, else i thinked we can move show author into a new menu button for edit or show author.
Share Button is normaly a must to have feature which is everywhere on social platforms or on reddit as button.
We need to keep the share button then as standalone but with a working slot for it.

But you dont said how we can connect to a slot which is outside the class not easy?

image

**Comment by defnax** [comment]
now how can connect this

connect(CopyLinkAction, SIGNAL(triggered()), this, SLOT(copyMessageLink()));

with PostedListWidgetWithModel::copyMessageLink()

**Comment by csoler** [comment]
you need to add a signal to the Boards Base item widget and launch this signal when local buttons are used. Then in the createEditor() method you can connect that signal to a slot in PostedListWidgetWithModel. But this is not very elegant IMHO,.

**Comment by defnax** [comment]
update PR https://github.com/csoler/RetroShare/pull/24

* Fixed to get work Copy RetroShare Link (using with emit)
* Removed the Minimum Expanding for GXS CommentsDialog
* Fixing margins for compact ui
* Fixing darkstylsheets
* Added Thumbnail for blocked messages
* Fixed to disable the Picture Label when Author is banned.

**Comment by csoler** [comment]
I thought that thumbails for blocked images was already here. It's in commit 65f7ead18d82aaeff8426899fb383958cbbb2e89
[edit]
I saw what you did. It's perfect.

**Comment by csoler** [comment]
This has been reviewed/improved extensively. I suppose I can merge it asap.

**Pull request merged**
