### PR TITLE
Sticker improvements

### PR DESCRIPTION
**Pull request by hunbernd**
requested here: https://github.com/RetroShare/RetroShare/pull/1589

- Waiting cursor
- Shows where to install the stickers when there is none, also creates a folder for them by default
- Added sticker icon
- Importing stickers from chat

Will not be fixed:
- Caching: I tested it, but it did not improve the performance
- Size checking: RS already downscales too large images, which looks ugly, but else I have to block nearly all stickers, because the size limit is too small

### CODE REVIEW

**Comment by felisucoibi** [comment]
thnks a lot

**Comment by defnax** [comment]
thank you 👍

**Comment by felisucoibi** [comment]
tested, and ok

**Comment by csoler** [comment]
I found a bug:in distant chat, normally the chat is not sent unless the tunnel is ok. When you add a sticker and the tunnel is not ok, it seems that it is still sent but gets lost. To reproduce: open a distant chat when the peer is offline and add a sticker . Then start the other peer, and when it is online, send a new msg. The peer will only see the second one.

**Comment by csoler** [comment]
in other words, the sticker should be put in the sending box, instead of directly in the conversation. So that you can edit the message with the sticker inside it.

**Comment by felisucoibi** [comment]
> in other words, the sticker should be put in the sending box, instead of directly in the conversation. So that you can edit the message with the sticker inside it.

If you add the sticker to the comment box, and you have to doble click to send it will be the first instant message software that does that. and the rest don't do it for a reason, stickers are fast ways to communicate a feeling. Click and share.... that's all in whatspap, telegram, fqacebook etc... is not a photo you take with your phone that you can comment in whatspap or telegram, is a expresion, a way to communicate with the world :p

btw the problem are nto stickers, but distant chats that are very crappy by now :dancer:

**Comment by csoler** [comment]
fine. Then you need to make sure that it is sent correctly.

**Comment by felisucoibi** [comment]
The way to solve this particular problem apart of the distant chat protocol that almost never works even if your friend is online, but anyway the way to solve it, is keep messages and stickers sent but not received, and like other similar software does, doble tick to say the destination has received it, meanwhile you keep them in your buffer waiting for your friend to be connected, and when he does you send automatically the message. any other approach or the actual frustrating approach of not be able to send it makes rs very frustrating. Very very frustratring, because now rs goes onli9ne and offline again and again and when you try to write it disconnects, and you can send it, and again and agina online offline rtc. Bests, as always i talk clear but is not my intention to offend. bests.

**Comment by csoler** [comment]
it seems that you experience problems with distant chat that could be related to saturation of your bandwidth by something else, despite the QoS on chat items. If that is the case, you may try to use RS less aggressively. For instance it is recommended to have less than 40 friends, to not transfer thousands of files at once, etc. Although the software works with largest numbers, the competition for bandwidth starts to take its toll.

**Comment by felisucoibi** [comment]
> it seems that you experience problems with distant chat that could be related to saturation of your bandwidth by something else, despite the QoS on chat items. If that is the case, you may try to use RS less aggressively. For instance it is recommended to have less than 40 friends, to not transfer thousands of files at once, etc. Although the software works with largest numbers, the competition for bandwidth starts to take its toll.

This is not the way things gets fixed in any software developement, you do it so often, you try to fix problems, "user side", "its your problem, how you use rs", not rs problem. I say it again, the best way to handle the situation is...not only for me, but for the project is to have a buffer that sends the message when the other person is online, atm is very frustrating, unnatural, and never seen before in a chat application, that you can't write if the other side is offline... this is ridiculous.... MUST BE A BUFFER, that the user don't care at all, the user write things and wait to be sended, like in every chat aplication. Is very common to have the other side of the conversation offline, only rs solves this in a CRAZY WAY for the user, THE USER DONT UNDERSTAND WHy THE HELL CAN'T SEND A MESSAGES IF THE OTHER SIDE IS OFFLINE, THEY DON'T UNDERSTAND AND MAKES RS FRUSTRATING (LIKE OTHER PARTS OF THW SOFTWARE LIKE THE NEW FORUMS loading AND CHANNELS loading)




 "The way to solve this particular problem apart of the distant chat protocol that almost never works even if your friend is online, but anyway the way to solve it, is keep messages and stickers sent but not received, and like other similar software does, doble tick to say the destination has received it, meanwhile you keep them in your buffer waiting for your friend to be connected, and when he does you send automatically the message. any other approach or the actual frustrating approach of not be able to send it makes rs very frustrating. Very very frustratring, because now rs goes onli9ne and offline again and again and when you try to write it disconnects, and you can send it, and again and agina online offline rtc. Bests, as always i talk clear but is not my intention to offend. bests."

**Comment by defnax** [comment]
@csoler you can view again? Thx

**Comment by defnax** [comment]
any news?

**Comment by felisucoibi** [comment]
Me too waiting this pr to be merged

**Comment by felisucoibi** [comment]
Btw last modification cam be removed, now there is a buffer, this pr should be removed, not necessary and maybe makes thing worse...
https://github.com/RetroShare/RetroShare/pull/1669/commits/9c877d3cdd837e73db77694f7d005310157aff4f

**Comment by defnax** [comment]
hope soon will be merged seems code needs to edited? @hunbernd @felisucoibi

**Comment by felisucoibi** [comment]
Me too

**Comment by defnax** [comment]
any news? the conflicted files can be easly fixed but when i do use webbeditor for fixing that will merge after fix this pr? 
when is this will be merged?

**Comment by defnax** [comment]
@csoler

**Comment by defnax** [comment]
whats the status?

**Comment by defnax** [comment]
@csoler @hunbernd

**Comment by defnax** [comment]
any news ? @csoler @hunbernd

**Comment by hunbernd** [comment]
I won't have time until december

**Comment by defnax** [comment]
Conflicting files
retroshare-gui/src/gui/chat/ChatWidget.cpp
retroshare-gui/src/gui/icons.qrc

thats easy to fix here on webeditor cyril can do it
i can do it, but im not allowed, waiting for cyril

**Comment by felisucoibi** [comment]
Hello pr

**Comment by defnax** [comment]
when it will be fixed this pr?
two files @hunbernd

**Comment by defnax** [comment]
whats the status

**Comment by felisucoibi** [comment]
hello pr

**Pull request merged**
