### PR TITLE
Get local addresses

### PR DESCRIPTION
**Pull request by G10h4ck**
This pull request now meant for merging but for easier code review!

This branch is meant to substitute de getPreferredInterface based on wrong assumptions like that an host has just two addresses (one public and one private) on which it should listen for RS connections.

The implication of this are deep rooted in the whole RS core, this branch is intended to prepare only the low level part for a multipath RetroShare in the future.

In particular flawed functions like getPreferredInterface and related has been removed and the brand new getLocalAddresses take his place.

getLocalAdrresses is tested on linux and on windows it also support IPv6 preparing the ground for IPv6 support on RetroShare

Before the actual merging some extra debug will be removed or made conditional too.

### CODE REVIEW

**Comment by defnax** [comment]
Hi, I has tested on my W 7, to compile your branch...
but i get trouble... wont compile yet. 
disabeld includes which are not available on mingw compiler:

In file included from pqi/pqinetwork.cc:27:0:
./util/rswin.h:37:0: warning: "stat64" redefined [enabled by default]
 #define stat64 _stati64
 ^
In file included from C:/MinGW/i686-w64-mingw32/include/wchar.h:380:0,
                 from C:/MinGW/i686-w64-mingw32/include/c++/cwchar:44,
                 from C:/MinGW/i686-w64-mingw32/include/c++/bits/postypes.h:40,
                 from C:/MinGW/i686-w64-mingw32/include/c++/bits/char_traits.h:4
0,
                 from C:/MinGW/i686-w64-mingw32/include/c++/string:40,
                 from ./util/rswin.h:34,
                 from pqi/pqinetwork.cc:27:
C:/MinGW/i686-w64-mingw32/include/_mingw_stat64.h:92:0: note: this is the locati
on of the previous definition
 #define stat64   _stat64  /\* for POSIX */
 ^
pqi/pqinetwork.cc: In function 'in_addr_t inet_netof(in_addr)':
pqi/pqinetwork.cc:273:28: error: 'pqi_inet_netof' was not declared in this scope

  return pqi_inet_netof(addr);
                            ^
pqi/pqinetwork.cc: In function 'bool getLocalAddresses(std::list<sockaddr_storag
e>&)':
pqi/pqinetwork.cc:315:2: error: 'IP_ADAPTER_ADDRESSES' was not declared in this
scope
  IP_ADAPTER_ADDRESSES\* adapter_addresses = (IP_ADAPTER_ADDRESSES_) malloc(bf_si
ze);
  ^
pqi/pqinetwork.cc:315:24: error: 'adapter_addresses' was not declared in this sc
ope
  IP_ADAPTER_ADDRESSES_ adapter_addresses = (IP_ADAPTER_ADDRESSES_) malloc(bf_si
ze);
                        ^
pqi/pqinetwork.cc:315:66: error: expected primary-expression before ')' token
  IP_ADAPTER_ADDRESSES_ adapter_addresses = (IP_ADAPTER_ADDRESSES_) malloc(bf_si
ze);
                                                                  ^
pqi/pqinetwork.cc:315:68: error: expected ';' before 'malloc'
  IP_ADAPTER_ADDRESSES_ adapter_addresses = (IP_ADAPTER_ADDRESSES_) malloc(bf_si
ze);
                                                                    ^
pqi/pqinetwork.cc:317:13: error: 'GAA_FLAG_SKIP_MULTICAST' was not declared in t
his scope
             GAA_FLAG_SKIP_MULTICAST |
             ^
pqi/pqinetwork.cc:318:13: error: 'GAA_FLAG_SKIP_DNS_SERVER' was not declared in
this scope
             GAA_FLAG_SKIP_DNS_SERVER |
             ^
pqi/pqinetwork.cc:319:13: error: 'GAA_FLAG_SKIP_FRIENDLY_NAME' was not declared
in this scope
             GAA_FLAG_SKIP_FRIENDLY_NAME,
             ^
pqi/pqinetwork.cc:322:21: error: 'GetAdaptersAddresses' was not declared in this
 scope
             &bf_size);
                     ^
pqi/pqinetwork.cc:325:36: error: 'adapter' was not declared in this scope
  IP_ADAPTER_ADDRESSES_ adapter(NULL);
                                    ^
pqi/pqinetwork.cc:328:26: error: 'IF_TYPE_SOFTWARE_LOOPBACK' was not declared in
 this scope
   if (adapter->IfType == IF_TYPE_SOFTWARE_LOOPBACK) continue;
                          ^
pqi/pqinetwork.cc:330:3: error: 'IP_ADAPTER_UNICAST_ADDRESS' was not declared in
 this scope
   IP_ADAPTER_UNICAST_ADDRESS\* address;
   ^
pqi/pqinetwork.cc:330:31: error: 'address' was not declared in this scope
   IP_ADAPTER_UNICAST_ADDRESS\* address;
                               ^
pqi/pqinetwork.cc:336:5: error: expected ')' before 'addrs'
     addrs.push_back(*tmp);
     ^
pqi/pqinetwork.cc: In function 'in_addr_t inet_netof(in_addr)':
pqi/pqinetwork.cc:274:1: warning: control reaches end of non-void function [-Wre
turn-type]
 }
 ^

**Comment by G10h4ck** [comment]
May you try again now please ?

**Comment by defnax** [comment]
new errors:

include -I../../openpgpsdk/src -I../../../../Qt5.5.0/5.5/mingw492_32/mkspecs/win
32-g++  -o temp/obj/pqinetwork.o pqi/pqinetwork.cc
In file included from pqi/pqinetwork.cc:27:0:
./util/rswin.h:37:0: warning: "stat64" redefined [enabled by default]
 #define stat64 _stati64
 ^
In file included from C:/MinGW/i686-w64-mingw32/include/wchar.h:380:0,
                 from C:/MinGW/i686-w64-mingw32/include/c++/cwchar:44,
                 from C:/MinGW/i686-w64-mingw32/include/c++/bits/postypes.h:40,
                 from C:/MinGW/i686-w64-mingw32/include/c++/bits/char_traits.h:4
0,
                 from C:/MinGW/i686-w64-mingw32/include/c++/string:40,
                 from ./util/rswin.h:34,
                 from pqi/pqinetwork.cc:27:
C:/MinGW/i686-w64-mingw32/include/_mingw_stat64.h:92:0: note: this is the locati
on of the previous definition
 #define stat64   _stat64  /\* for POSIX */
 ^
pqi/pqinetwork.cc:302:0: warning: ignoring #pragma comment  [-Wunknown-pragmas]
 #pragma comment(lib, "IPHLPAPI.lib")
 ^
pqi/pqinetwork.cc: In function 'in_addr_t inet_netof(in_addr)':
pqi/pqinetwork.cc:273:28: error: 'pqi_inet_netof' was not declared in this scope

  return pqi_inet_netof(addr);
                            ^
pqi/pqinetwork.cc: In function 'bool getLocalAddresses(std::list<sockaddr_storag
e>&)':
pqi/pqinetwork.cc:342:5: error: expected ')' before 'addrs'
     addrs.push_back(*tmp);
     ^
pqi/pqinetwork.cc: In function 'in_addr_t inet_netof(in_addr)':
pqi/pqinetwork.cc:274:1: warning: control reaches end of non-void function [-Wre
turn-type]
 }

**Comment by G10h4ck** [comment]
May you test it again please ? :)

**Comment by sirjenster** [comment]
do you REALLY need line 926 and 927 here? i had to comment it out to get it to compile on osx..

util/rsnet_ss.cc:426:18: error: no member named '__ss_padding' in 'sockaddr_storage'
  output << addr.__ss_padding;

might still work on Yosemite/El_Capitan OSX, but i see no reason to include if not necessary.

**Comment by defnax** [comment]
util\rsnet_ss.cc: In function 'void sockaddr_storage_dump(const sockaddr_storage
&, std::string_)':
util\rsnet_ss.cc:409:73: error: 'inet_ntop' was not declared in this scope
   inet_ntop(addr.ss_family, &(in6->sin6_addr), addrStr, INET6_ADDRSTRLEN);
                                                                         ^
util\rsnet_ss.cc:426:18: error: 'const struct sockaddr_storage' has no member na
med '__ss_padding'
   output << addr.__ss_padding;
                  ^
util\rsnet_ss.cc: In function 'std::string sockaddr_storage_ipv6_iptostring(cons
t sockaddr_storage&)':
util\rsnet_ss.cc:872:76: error: 'inet_ntop' was not declared in this scope
  inet_ntop(addr.ss_family, &(addrv6p->sin6_addr), addrStr, INET6_ADDRSTRLEN);
                                                                            ^
util\rsnet_ss.cc: At global scope:
util\rsnet_ss.cc:962:66: warning: unused parameter 'addr' [-Wunused-parameter]
 bool sockaddr_storage_ipv6_isnull(const struct sockaddr_storage &addr)
                                                                  ^
util\rsnet_ss.cc:972:70: warning: unused parameter 'addr' [-Wunused-parameter]
 bool sockaddr_storage_ipv6_isValidNet(const struct sockaddr_storage &addr)
                                                                      ^
util\rsnet_ss.cc:982:73: warning: unused parameter 'addr' [-Wunused-parameter]
 bool sockaddr_storage_ipv6_isLoopbackNet(const struct sockaddr_storage &addr)
                                                                         ^
util\rsnet_ss.cc:992:72: warning: unused parameter 'addr' [-Wunused-parameter]
 bool sockaddr_storage_ipv6_isPrivateNet(const struct sockaddr_storage &addr)
                                                                        ^
util\rsnet_ss.cc:1002:73: warning: unused parameter 'addr' [-Wunused-parameter]
 bool sockaddr_storage_ipv6_isExternalNet(const struct sockaddr_storage &addr)
                                                                         ^
Makefile.Debug:7405: recipe for target 'temp/obj/rsnet_ss.o' failed
mingw32-make[1]: *_\* [temp/obj/rsnet_ss.o] Error 1
mingw32-make[1]: Leaving directory 'C:/Qt/RetroShare/RetroShare/libretroshare/sr
c'
makefile:48: recipe for target 'debug' failed
mingw32-make: **\* [debug] Error 2

**Comment by G10h4ck** [comment]
May you test it again please ? :)

**Comment by defnax** [comment]
In file included from pqi/pqinetwork.cc:27:0:
./util/rswin.h:37:0: warning: "stat64" redefined [enabled by default]
 #define stat64 _stati64
 ^
In file included from C:/MinGW/i686-w64-mingw32/include/wchar.h:380:0,
                 from C:/MinGW/i686-w64-mingw32/include/c++/cwchar:44,
                 from C:/MinGW/i686-w64-mingw32/include/c++/bits/postypes.h:40,
                 from C:/MinGW/i686-w64-mingw32/include/c++/bits/char_traits.h:4
0,
                 from C:/MinGW/i686-w64-mingw32/include/c++/string:40,
                 from ./util/rswin.h:34,
                 from pqi/pqinetwork.cc:27:
C:/MinGW/i686-w64-mingw32/include/_mingw_stat64.h:92:0: note: this is the locati
on of the previous definition
 #define stat64   _stat64  /\* for POSIX */
 ^
pqi/pqinetwork.cc:302:0: warning: ignoring #pragma comment  [-Wunknown-pragmas]
 #pragma comment(lib, "IPHLPAPI.lib")
 ^
pqi/pqinetwork.cc: In function 'in_addr_t inet_netof(in_addr)':
pqi/pqinetwork.cc:273:28: error: 'pqi_inet_netof' was not declared in this scope

  return pqi_inet_netof(addr);
                            ^
pqi/pqinetwork.cc: In function 'bool getLocalAddresses(std::list<sockaddr_storag
e>&)':
pqi/pqinetwork.cc:342:5: error: expected ')' before 'addrs'
     addrs.push_back(_tmp);
     ^
pqi/pqinetwork.cc: In function 'in_addr_t inet_netof(in_addr)':
pqi/pqinetwork.cc:274:1: warning: control reaches end of non-void function [-Wre
turn-type]
 }
 ^
Makefile.Release:3633: recipe for target 'temp/obj/pqinetwork.o' failed
mingw32-make[1]: *_\* [temp/obj/pqinetwork.o] Error 1
mingw32-make[1]: Leaving directory 'C:/Qt/RetroShare/RetroShare-getLocalAddresse
s/libretroshare/src'
Makefile:34: recipe for target 'release' failed
mingw32-make: **\* [release] Error 2

C:\Qt\RetroShare\RetroShare-getLocalAddresses\libretroshare\src>pause
 . . .

**Comment by G10h4ck** [comment]
Ready for merging

**Pull request merged**
