### PR TITLE
Abstract item model for channels 

### PR DESCRIPTION
**Pull request by csoler**

### CODE REVIEW

**Comment by defnax** [comment]
hi hope you not forget to add the status column feature on the File View, that is a very nice feature 

`		QWidget *statusWidget = new GxsChannelFilesStatusWidget(post.mMeta.mGroupId, post.mMeta.mMsgId, file);
		ui->treeWidget->setItemWidget(treeItem, COLUMN_STATUS, statusWidget);`

**Comment by csoler** [comment]
Do you have a screenshot of what it should look like?

**Comment by defnax** [comment]
> Do you have a screenshot of what it should look like?

image

**Comment by felisucoibi** [comment]
+1 i m happy if i can add rslinks to description, thats the only one feature i use or maybe be able to add directories not only files.

**Comment by defnax** [comment]
> +1 i m happy if i can add rslinks to description, thats the only one feature i use or maybe be able to add directories not only files.

http links works, but description is sended as plaintext

**Comment by felisucoibi** [comment]
> > +1 i m happy if i can add rslinks to description, thats the only one feature i use or maybe be able to add directories not only files.
> 
> http links works, but description is sended as plaintext

what i mean is to not remove this functionality. Or even include rslinks or directory structure in the new files model inside a channel post.

**Comment by defnax** [comment]
@csoler cant compile, there is sources & include mist seems you forget to commit it.
`#include "GxsChannelPostsModel.h"`

**Comment by defnax** [comment]
hi i dont like this big button , better with short width one or put into column
image

**Comment by csoler** [comment]
Sure. This is just a placeholder for now. I much prefer the "one button per line" example that you gave above. I just dont know yet how to do it.

**Comment by defnax** [comment]
whats its importend that we get the Button with the Status back for the File View & dont know if the other files tab get this feature too? subfileitem always supported it too. normaly it must have it too?

image


After Download finished you can always do Play/Open the media or Open the folder
on the feed channelsmsgitem you can do everything via the button features

**Comment by defnax** [comment]
here for the thumbview selected files tab would be nice too

image

**Comment by csoler** [comment]
I'm using the same AbstractItemModel for both views, so whatever is in the post files view will also be in the global view.

**Comment by defnax** [comment]
* Hover color for Thumbnail 
* a Highlight color for new posts 

few ui todos:
* set default thumbs for channel or channel post logo( first start its empty )
* set default column width for File Name, Size or Status Column 
* store splitter position
* Edit Channel button ( can be added to the details)
* Edit Button (for posts details)
* Published Time needs to be displayed on Files tab too

**Comment by csoler** [comment]
> some issues:
> 
> * first 3 thumbnails shows different sizes (w10)

I cannot reproduce this bug on ubuntu 18.04 . Seems to be a Qt issue. We'll need t find a workaround.

> * Title needs maybe be cuted when its to big after some characters (thumbview)

I have a proposition to fix this: let's ask users to create posts with short titles. To do that, we should display in the title creation window, a preview of what the thumbnail will look like. This is also helpful to fix up the image aspect ratio.

> * Title needs something about minimum fontsize 10 which is readable when possible (thumbview)

This is handled using the variable THUMBNAIL_OVERSAMPLE_FACTOR. Now it's 2.0, meaning that fonts are 2.0 smaller than normal fonts in the thumbnails. This is a compromize between visibility and not cutting the text. We can try other factors such as 1.5. Then the text will be larger but probably cut.

> * selection color for files model not works

This is on purpose: you never have to select anything in this view. The buttons are always ready for you to click on them.

> * Hover color for Thumbnail (stylesheet)(but one some styles works by default hover color)

That is possible. I'm not sure that it is useful. We can also add a tooltip with some info.
 
> few ui todos:
> 
> * set default thumbs for channel or channel post logo( first start its empty )

When it's empty, there's a placeholder. What do you mean?

> * add Channel Name Label to details

ok

> * set default column width for File Name Column

Normally the widget stretches automatically around file names. Why would you need some default column size??

> * store splitter position

I'll let you do that one.

**Comment by defnax** [comment]
> I have a proposition to fix this: let's ask users to create posts with short titles. To do that, we should display in the title creation window, a preview of what the thumbnail will look like. This is also helpful to fix up the image aspect ratio.

yes best idea


> 
> > * selection color for files model not works
> 
> This is on purpose: you never have to select anything in this view. The buttons are always ready for you to click on them.
> 
thats something weird we have always selection colored on trees in rs
i mean for me not normal when we disable selection colors?
im thinking always its a bug... 
> > * Hover color for Thumbnail (stylesheet)(but one some styles works by default hover color)
> 
> That is possible. I'm not sure that it is useful. We can also add a tooltip with some info.
> 
this is often nice (only need to know the class name and the which qt class is defined the thumbnail to set the hover stylesheet when the qobject is not missed.
> > few ui todos:
> > 
> > * set default thumbs for channel or channel post logo( first start its empty )
> 
> When it's empty, there's a placeholder. What do you mean?
> 
place holder image (default thumb) when nothing selected on first start or when nothing  selected
but you doesnt added yet 
image
image


> > * set default column width for File Name Column
> 
> Normally the widget stretches automatically around file names. Why would you need some default column size??
> 
i doesnt like this method,  everytime it stretches the column and the Download  button looks every time different width. 
it looks more clean with default width i doesnt need to fit the complete file name
we need default like how we used on some other places (mails, forums).
i prefer for silesize a default width too.
then it will look more clean without stretching, we used on the file view too default sizes to look nice

image
image

**Comment by csoler** [comment]
ok. I get your point about column with. What we should do is:
- make download button have a fixed size
- stretch the size
- give the rest to files
Is that better?

**Comment by defnax** [comment]
> ok. I get your point about column with. What we should do is:
> 
> * make download button have a fixed size
> * stretch the size
> * give the rest to files
>   Is that better?

i prefer default width for "file" column but it stretches when you making your main window bigger, 
size default width about 100pixel the rest is for download button,
but resize able columns but not more resize the "File" column with filenames
this looks goods when you switch to another post to look like same
image
i dont want that the download button or "Size" column stretches by default.

**Comment by defnax** [comment]
look how this looks but i miss selection here too we had always on File View selection colors
image

**Comment by csoler** [comment]
selection is currently used as a trick to bypass the double click that was needed before on the download button, and allows the widgets to be "clickable" with buttons and custom widgets.
If you want selection here, then you need to put download/pause, and so on, in a context menu. It's possible, but less elegant IMO.
What I can do, is highlight the current item (item under the mouse is automatically selected. That is needed to bypass the double click).

**Comment by defnax** [comment]
> selection is currently used as a trick to bypass the double click that was needed before on the download button, and allows the widgets to be "clickable" with buttons and custom widgets.
> If you want selection here, then you need to put download/pause, and so on, in a context menu. It's possible, but less elegant IMO.
> What I can do, is highlight the current item (item under the mouse is automatically selected. That is needed to bypass the double click).

selection not yet important but the default width for "file" and not more stretch the file column by filename

**Comment by defnax** [comment]
> 15:38 PhenomVB: 15:34 PhenomVB: Hello devs,
> About PR#1994, here a patch to get channel post Files delegate well painted and get hover event.
> You can use it for all Files Tab too:

```
--- retroshare-gui/src/gui/gxschannels/GxsChannelPostsWidgetWithModel.cpp
+++ retroshare-gui/src/gui/gxschannels/GxsChannelPostsWidgetWithModel.cpp
@@ -23,2 +23,3 @@
 #include <QPainter>
+#include <QTreeView>
 
@@ -211,2 +212,3 @@ void ChannelPostFilesDelegate::paint(QPainter * painter, const QStyleOptionViewI
         w.setFixedWidth(option.rect.width());
+ w.setFixedHeight(option.rect.height());
 
@@ -259,2 +261,3 @@ GxsChannelPostsWidgetWithModel::GxsChannelPostsWidgetWithModel(const RsGxsGroupI
     ui->channelFiles_TV->setItemDelegate(new ChannelPostFilesDelegate());
+ ui->channelPostFiles_TV->viewport()->installEventFilter(this);
 
@@ -996,1 +999,26 @@ void GxsChannelPostsWidgetWithModel::setAllMessagesReadDo(bool read, uint32_t &t
-
+
+bool GxsChannelPostsWidgetWithModel::eventFilter(QObject *obj, QEvent *ev)
+{
+ QTreeView* tv = qobject_cast<QTreeView*>(obj->parent());
+ QMouseEvent* me = static_cast<QMouseEvent*>(ev);
+ if(tv == ui->channelPostFiles_TV)
+ {
+ RsDbg() << __PRETTY_FUNCTION__ << " " << qt_getEnumName(ev->type());
+ if (me && me->type()==QEvent::HoverMove)
+ {
+ QModelIndex i = tv->indexAt(me->pos());
+ if(i.isValid() && i.column()==RsGxsChannelPostFilesModel::COLUMN_FILES_FILE)
+ {
+ if(!tv->isPersistentEditorOpen(i))
+ tv->openPersistentEditor(i);
+ }
+ if(mLastItemHover != i || !i.isValid())
+ {
+ if(tv->isPersistentEditorOpen(mLastItemHover))
+ tv->closePersistentEditor(mLastItemHover);
+ }
+ mLastItemHover = i;
+ }
+ }
+ return QObject::eventFilter(obj, ev);
+}
--- retroshare-gui/src/gui/gxschannels/GxsChannelPostsWidgetWithModel.h
+++ retroshare-gui/src/gui/gxschannels/GxsChannelPostsWidgetWithModel.h
@@ -128,2 +128,5 @@ protected:
 
+protected:
+ bool eventFilter(QObject *obj, QEvent *ev) override;
+
 private slots:
@@ -162,2 +165,4 @@ private:
 
+ QModelIndex mLastItemHover;
+
   /* UI - from Designer */`
```

**Comment by defnax** [comment]
i has added last night a Channel Name Label back to ui file, seems there is the tokenservice removed to
can you  add back to retrieve the Channel name?

this code doesnt get it more when i enable it
> void GxsChannelPostsWidgetWithModel::groupNameChanged(const QString &name)
> {
> 	if (groupId().isNull()) {
> 		ui->nameLabel->setText(tr("No Channel Selected"));
> 		ui->logoLabel->setPixmap(QPixmap(":/icons/png/channels.png"));
> 	} else {
> 		ui->nameLabel->setText(name);
> 	}
> 

}

**Comment by NyvenZA** [comment]
Compiled the last version yesterday and tested the look and feel. 

- Sorting now works on the Main Files Tab. 

- I cannot seem to find out what the sort order of the thumbnails are on the Main Posts tab. Also I can't change the sort order. But the original Channels didn't have a sort here, so i assume it is supposed to be sorted in date time order. It is not. 

- I can't find where the posted date and time is. 

- On the Main Posts tab, I see thatthere are extra thumbnails added to the end of the list to fill up the last line.  This only seems to happen if you resize the RS Gui so that the last line is not filled.

**Comment by NyvenZA** [comment]
- Made a new post on the PR1994 version and it populated through to my live master version. 
- Made a comment on the master version and on the PR 1994. 
-- The Comment on the PR1994 didn't show up on the master version. 
-- The live comment came through to the PR 1994. 

- I did use Refresh on both sides a couple of times and it only shows the test comment on the PR 1994 side.

**Comment by defnax** [comment]
Idea for new posts highlighting

1. highlighting with foreground color 
2. 'New' Label under the Thumbnail

Dont know if its possible then it can be defined with Stylesheet the colors & look

**Comment by defnax** [comment]
File View idea from old File view was:

When File is selected it displays on the details from the contained post
The Titel, Thumbnail & Message, Time

**Comment by defnax** [comment]
for navigate feature:
i saw two issues:

1. the Thumbnail is not selected
2. when details or files tab is active cant see the post, need a feature to activitate the "Posts" tab channel_TW->setCurrentIndex(int index);

other small issue thing when open channels into tabs channel name is missed there
```
QString GxsChannelPostsWidgetWithModel::groupName(bool)
{
    return "Group name" ;
}
```

**Comment by defnax** [comment]
another issue:
when opening a channel into tab, the details are gone/cleared
test

**Pull request merged**
