### PR TITLE
Fix GUI Loading Threads when Destructors are called.

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
Only left RsEvents.

### CODE REVIEW

**Comment by felisucoibi** [comment]
wiii

**Comment by jolavillette** [comment]
pr #1973 still crashes on ubuntu when I switch from a channel to another.
I posted 2 gdb logs on "RetroShare Crash reports" forum.

**Comment by PhenomRetroShare** [comment]
@jolavillette : Did you test this:
[Re: crash report for pr/1973](retroshare://forum?name=Re%3A%20crash%20report%20for%20pr%2F1973&id=b5a11bf3e08034f9cc1da71522f1325a&msgid=9eacb891eb94eb969692cd0fad2db767997676a5)

**Comment by NyvenZA** [comment]
On the Channel page the channels take VERY long to load now. If I click on one channel it evently displays. 
This displays in the Debug window while it takes long to load. 

 1590953362.572 virtual GxsChannelPostItem::~GxsChannelPostItem() is Waiting Message Comment loading finished.
D 1590953362.681 virtual GxsChannelPostItem::~GxsChannelPostItem() is Waiting Message Comment loading finished.
D 1590953362.807 virtual GxsChannelPostItem::~GxsChannelPostItem() is Waiting Message Comment loading finished.
D 1590953362.919 virtual GxsChannelPostItem::~GxsChannelPostItem() is Waiting Message Comment loading finished.
D 1590953363.024 virtual GxsChannelPostItem::~GxsChannelPostItem() is Waiting Message Comment loading finished.
D 1590953363.135 virtual GxsChannelPostItem::~GxsChannelPostItem() is Waiting Message Comment loading finished.
D 1590953363.244 virtual GxsChannelPostItem::~GxsChannelPostItem() is Waiting Message Comment loading finished.
D 1590953363.354 virtual GxsChannelPostItem::~GxsChannelPostItem() is Waiting Message Comment loading finished.
D 1590953363.465 virtual GxsChannelPostItem::~GxsChannelPostItem() is Waiting Message Comment loading finished.
D 1590953363.574 virtual GxsChannelPostItem::~GxsChannelPostItem() is Waiting Message Comment loading finished.
D 1590953363.693 virtual GxsChannelPostItem::~GxsChannelPostItem() is Waiting Message Comment loading finished.


ALSO
Open Circles, ( But I don't think this is related. )
Right-click  on a circle view properties. 
Then close immediately and then do the same with another circle.  I repeated 2 or three times and then it crashed. 

[20200531-pr1973-crash.txt](https://github.com/RetroShare/RetroShare/files/4708256/20200531-pr1973-crash.txt)

**Pull request closed without merging**
