### PR TITLE
V0.6 bug fixing

### PR DESCRIPTION
**Pull request by csoler**

### CODE REVIEW

**Comment by csoler** [comment]
This pull request should fix the crashes in news feed. To be tested.
I also fixed somehow the logic in deleting items. Before that, the FeedItem class used to send a signal from within its destructor. That is definitely not a good idea.
The next step should be to get rid of the TokenQueue system in this part of the code too.

**Comment by hunbernd** [comment]
No crash.

But I don't get notifications about new mail, posts etc.

**Comment by csoler** [comment]
Thx. I'll check that. I assume that the corresponding checkboxes are activates in your RS?

**Comment by csoler** [comment]
I fixed it.

**Pull request merged**
