### PR TITLE
gui stuff: add friend wizard tweaks; chatlobby splitter saving; QuickStartWizard to Home; GenCertDialog minor fixes; gxs sync 372 thing

### PR DESCRIPTION
**Pull request by RetroPooh**
oops. i fail with branches, sorry. half of commits were in previous PR

### CODE REVIEW

**Comment by csoler** [comment]
Thx. I'll try it asap. Note: since I merge into branch v0.6-ImprovedGUI, you'd better merge the latest of this branch into yours, instead of merging trunk.

**Comment by csoler** [comment]
can you plz take a look at the conflicts? It's almost nothing. thx!

**Comment by RetroPooh** [comment]
i think i did :P

**Comment by csoler** [comment]
Hi. I wanted to push my latest modifications to the GUI but it created 2 small conflicts in your branch. Can you plz fix them? Sorry for the inconvenience, but I did lots of changes in config pages and we probably edited the same lines. Apparently there's nothing serious. Thx!

**Comment by RetroPooh** [comment]
done?

**Comment by csoler** [comment]
you removed "ui->_direct_transfer_CB_2  ->setChecked(peerDetails.service_perm_flags & RS_NODE_PERM_DIRECT_DL) ;" in order to use a default value (false), but the dialog works for both editing and displaying existing info. So it need to be initialised with the proper existing value.

**Comment by RetroPooh** [comment]
> the dialog works for both editing and displaying existing info.

It does not work that way.

**Comment by csoler** [comment]
Hi,
I have no idea how many of these commits are still relevant to current trunk. As such, it is almost impossible for me to review this PR. This is too bad, because there's very good contributions in it. I suppose I will have to do some cherry-picking, unless you clean it up.

Thx

**Comment by RetroPooh** [comment]
it is here now: https://github.com/RetroShare/RetroShare/pull/710

**Pull request closed without merging**
