### PR TITLE
Added export Friendslist to Profile Page

### PR DESCRIPTION
**Pull request by defnax**
- updated version of https://github.com/RetroShare/RetroShare/pull/2847

### CODE REVIEW

**Comment by defnax** [comment]
@csoler

**Comment by csoler** [comment]
There's no point in allocating a NewFriendList (which takes quite a lot of RAM) since there is one already in the Network page. Here you're basically allocating memory that is most probably not going to be used. There's two good ways to do what you need:
1 - use a slot in CryptoPage that does NewFriendList().exportFriendListClicked() (this allocates a NewFriendList only temporarily and then destroys it)
or better:
2 - make NewFriendList::exportFriendList() static, and from CryptoPage, just call this method as a static method.

**Comment by defnax** [comment]
hi i doesnt get it worked

```
connect(ui.exportfriendslist,SIGNAL(clicked()), this, SLOT(exportFriendsList()) );


void CryptoPage::exportFriendsList()
{
    NewFriendList::exportFriendList();
}

```

and in NewFriendList.h
```
Public:

	static  bool exportFriendlist(QString &fileName);
```

its public im not sure why it does not find it?

image

**Comment by defnax** [comment]
- new version https://github.com/RetroShare/RetroShare/pull/2849

**Pull request closed without merging**
