### PR TITLE
Implement deep indexing and search for forums

### PR DESCRIPTION
**Pull request by G10h4ck**
Implement service level GXS generic deep search
Improve deep indexing

When ready should also supersede https://github.com/RetroShare/RetroShare/pull/2218 and https://github.com/RetroShare/RetroShare/pull/1453

### CODE REVIEW

**Comment by defnax** [comment]
@G10h4ck  hope you not forget for Boards too, it needs deep search too

**Comment by defnax** [comment]
maybe for the wire service too (twitter clone in rs)

**Comment by G10h4ck** [comment]
Most probably it would be useful for any service, but right now my priority is forum and files

**Comment by felisucoibi** [comment]
+1 forum and files

**Comment by G10h4ck** [comment]
I am quite tired of keeping re-basing this PR due to merge conflicts, as there are no major oppositions since months I'll merge this once the appveyor build completes

**Pull request merged**
