### PR TITLE
Added publish time display and some feeds fixes

### PR DESCRIPTION
**Pull request by defnax**
Added to display the Created time for Channels/Posted/forums
Display the Topics Thumbnail on the Info frame
Fixed some feed items

### CODE REVIEW

**Comment by felisucoibi** [comment]
+1

**Comment by defnax** [comment]
Improved Node display 
moved the Export button to the main node tab.
image

**Comment by defnax** [comment]
* Update authors on About dialog
* Updated the website links
* Moved Status/Download button to the middle for Channel Files View
* Set text aligment for Size

**Comment by defnax** [comment]
@csoler when you checking this pr?

**Comment by csoler** [comment]
Looks very nice!

**Pull request merged**
