### PR TITLE
aded PB PetaByte to filelists.

### PR DESCRIPTION
**Pull request by felisucoibi**
To be tested.

### CODE REVIEW

**Comment by felisucoibi** [comment]
Tested, needs more love, I think there are kind of defaults, i'll try to do it.

**Comment by felisucoibi** [comment]
I think the logic for TB is harcoded in libretroshare/src/file_sharing/hash_cache.cc if somebodyu can have a look.

**Comment by csoler** [comment]
The loop in misc.cpp should go to 6 instead of 5.

**Comment by felisucoibi** [comment]
Finished, it works.

**Pull request merged**
