### PR TITLE
Format ISO Received time for chat message in WebUI.

### PR DESCRIPTION
**Pull request by PhenomRetroShare**

### CODE REVIEW

**Comment by AsamK** [comment]
:+1:

**Comment by electron128** [comment]
I think it would be better to format the time on the client side, because we could then respect the client time zone.
It would be nice to show relative time, like "5 minutes ago".
Does someone know a JavaScript library for this?
(Would be nice if the library could speak multiple languages.)

**Comment by csoler** [comment]
@electron128: I leave this one on you. It's apparently not 100% ready.

**Comment by PhenomRetroShare** [comment]
Yes it is finished.
Use web client date format and time offset.

**Comment by electron128** [comment]
Commit 1 would be ok, but i found it is much easier to do this in JavaScript:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
Commit 2 is not ok, because it deletes some files which i want to keep. Those files appear unused, because they are not meant to run in the browser. They are made for nodejs.
I added formatting of the time in a75cbcd7b3b82933be38276acd7491437d3c6303 with a one-liner:

``` javascript
new Date(msg.send_time*1000).toLocaleTimeString()
```

I want to avoid pulling in more React dependencies, because i may drop React.
Thanks for your work on this Phenom, i hope you can understand that i prefer the solution which uses standard JavaScript functions.

**Pull request closed without merging**
