### PR TITLE
V0.6 file lists

### PR DESCRIPTION
**Pull request by csoler**
For testing purposes. Seems to work much more efficiently than the previous implementation, but needs to be tested with large file lists.

### CODE REVIEW

**Comment by csoler** [comment]
There's a bug however that I cannot manage to get rid of:when the search is empty, RS expands all items. This takes a long time. This should be avoided, and my code is  normally supposed to do that but it doesn't and I dont understand why.

[EDIT] FIXED. Apparently, QString::isNull() is not equivalent to QString()=="". Weird.

**Comment by felisucoibi** [comment]
I ll test it today

**Comment by felisucoibi** [comment]
Tested, works well with huge file lists, in fact it does not hang the gui, and it just takes 5 secs to crawl my whole friends file lists... very good!, 
BUT is not usefull at all, because it show lot of files and directories that have no relation with the search result, it should HIDE all the directories, and all the files of the friend tree of files that are not related to the search result.
Example, a directory with 1000 files and also 500 directories inside, and one of the files is called, "champions of the world" if you search for "champions of the world" you will see a directory with 1000 files 500 directories, and you will not even be able to see which of these files contains "champions of the world", ones does but is impossible to find it, and also it shows other directories inside this 1000 files directory if exists... so it should hide all the directories without "champions of the world" file inside, and all the files in the same directory without "champions of the world" string.

**Comment by felisucoibi** [comment]
Thanks for all this work here, super useful.

In friends filelists there is a green icon a triangle, and when you search for something ther eis a red cross, in My files is not this icon, so after searching you cant remove the search clicking in the red icon and you can see your filelist without a search result.


Btw in friend filelists, could be useful to remove the users that a) use old rs versions or b) don't share anything with you, now they are there, and they just use space.

And also could be very useful a column for total files shared, and another for total TB shared, so column shorting can work, now, is mixed in one column, and sorting is not working.

**Pull request merged**
