### PR TITLE
Switching Debian Stretch builds to QT5.

### PR DESCRIPTION
**Pull request by heini**
Did a succesfull build against QT5 on Stretch today with these changes.

### CODE REVIEW

**Comment by sehraf** [comment]
since Qt4 support ended last year (19.12.2015) i'd suggest using Qt5 everywhere.

**Comment by heini** [comment]
I'd guess that depends on availability of QT5 for particular (older) distribution versions.

**Comment by electron128** [comment]
ping @csoler : please have a look at this. If you want to merge this, you maybe want to merge before next release.

**Comment by sehraf** [comment]
maybe we can switch all OS's that support it  to Qt5 for the next RC?

**Comment by csoler** [comment]
I'm ok with the switch to Qt5, but I insist on being able to keep Qt4 when Qt5 not available. Some people use RS on home servers or NAS that might not have Qt5.

**Comment by csoler** [comment]
why do you need a new rules file btw?

**Comment by heini** [comment]
Because this is for Stretch only. Don't know whether it's possible to have conditionals in the rules file to distinguish between releases.

**Pull request merged**
