### PR TITLE
Add General Font Size Factor

### PR DESCRIPTION
**Pull request by PhenomRetroShare**

### CODE REVIEW

**Comment by csoler** [comment]
Doesn't compile for me: 

gui/ChatLobbyWidget.cpp: In constructor ‘ChatLobbyWidget::ChatLobbyWidget(QWidget*, Qt::WindowFlags)’:
gui/ChatLobbyWidget.cpp:210:6: error: redeclaration of ‘int H’
  210 |  int H = misc::getFontSizeFactor("HelpButton").height();
      |      ^
gui/ChatLobbyWidget.cpp:96:6: note: ‘int H’ previously declared here
   96 |  int H = QFontMetricsF(ui.lobbyTreeWidget->font()).height();
      |      ^

**Comment by PhenomRetroShare** [comment]
Sorry, upload it too quickly, without test.
Updated.

**Comment by defnax** [comment]
in Shared Files/My files there are issue with font and item heigths, needs to be fixed

**Comment by csoler** [comment]
where can I change the font size in the UI?

**Comment by PhenomRetroShare** [comment]
??? This is to scale icons.
Each icon ask size factor in setting. For now, no GUI, but saved in RetroShare.conf file.

**Pull request merged**
