### PR TITLE
added auto delete active token feature to RsGxsIfaceHelper

### PR DESCRIPTION
**Pull request by csoler**
This should help fixing the loading problem on forums

### CODE REVIEW

**Comment by csoler** [comment]
this PR is ready and should be tested. It seems to me that it makes UI much more responsive. I've basically removed all TokenQueue calls from GxsGroupFrameDialog and GxsGroupDialog.  I might add a few more commits soon to get rid of the last TokenQueue calls in Identity widgets.

**Comment by sehraf** [comment]
When loading of forums/posts/channels works it is fast. Nevertheless there is still something blocking from time to time. When this blocking happens nothing is loaded, neither forums nor posts or channels.
Beside that, this pr doesn't compile with jsonapi enabled.

**Comment by csoler** [comment]
it's possible that two groups are loaded at once and alone. This is case one removes the other fro the queue. Can you spot exactly what is not loading?

**Comment by sehraf** [comment]
hard to tell. when the "lock" hits nothing is loaded, neither posts, other forums or even channels.
looking at gdb and debug output it seems like rs is processing the request (the Active tokens are building up and then go away again) but the gui is not updated. 
What i do see is this: and maybe this is the problem:
(happens when widly clicking in the gui - this is likely to trigger the "lock")
```
[New Thread 0x7ffe2b7fe700 (LWP 37611)]
Active tokens (this=0x555557fdf2d8): 5547 (2) 5557 (4) 
[New Thread 0x7ffe2affd700 (LWP 37612)]
Active tokens (this=0x555557fdf2d8): 5547 (2) 5557 (4) 5558 (4) 
[New Thread 0x7ffe2bfff700 (LWP 37613)]
Active tokens (this=0x555557fdf2d8): 5547 (2) 5557 (4) 5558 (4) 5559 (4) 
[New Thread 0x7fff03fff700 (LWP 37614)]
Active tokens (this=0x555557fdf2d8): 5547 (2) 5557 (4) 5558 (4) 5559 (4) 5560 (4) 
[New Thread 0x7fff037fe700 (LWP 37615)]
Active tokens (this=0x555557fdf2d8): 5547 (2) 5557 (4) 5558 (4) 5559 (4) 5560 (4) 5561 (4) 
[New Thread 0x7fff01ffb700 (LWP 37616)]
Active tokens (this=0x555557fdf2d8): 5547 (2) 5557 (4) 5558 (4) 5559 (4) 5560 (4) 5561 (4) 5562 (4) 
[New Thread 0x7fff017fa700 (LWP 37617)]
Active tokens (this=0x555557fdf2d8): 5547 (2) 5557 (4) 5558 (4) 5559 (4) 5560 (4) 5561 (4) 5562 (4) 5563 (4) 
[New Thread 0x7ffee37fe700 (LWP 37618)]
Active tokens (this=0x555557fdf2d8): 5547 (2) 5557 (4) 5558 (4) 5559 (4) 5560 (4) 5561 (4) 5562 (4) 5563 (4) 5564 (4) 
[New Thread 0x7ffee2ffd700 (LWP 37619)]
Active tokens (this=0x555557fdf2d8): 5547 (2) 5557 (4) 5558 (4) 5559 (4) 5560 (4) 5561 (4) 5562 (4) 5563 (4) 5564 (4) 5565 (4) 
(Tue Mar 24 19:07:10 2020 Z: pqisslzone, lvl: 0): pqissl::Basic_Connection_Complete() ENETUNREACH/ETIMEDOUT: cert: ... 
[Thread 0x7ffe2a7fc700 (LWP 37610) exited]
[Thread 0x7ffe2b7fe700 (LWP 37611) exited]
[Thread 0x7ffe2affd700 (LWP 37612) exited]
[Thread 0x7ffe2bfff700 (LWP 37613) exited]
[Thread 0x7fff037fe700 (LWP 37615) exited]
[Thread 0x7fff03fff700 (LWP 37614) exited]
[Thread 0x7fff01ffb700 (LWP 37616) exited]
[Thread 0x7fff017fa700 (LWP 37617) exited]
[Thread 0x7ffee37fe700 (LWP 37618) exited]
[Thread 0x7ffee2ffd700 (LWP 37619) exited]
[New Thread 0x7ffee2ffd700 (LWP 37620)]
Active tokens (this=0x555557fdf2d8): 5566 (2) 
GxsForumThreadWidget::insertPostData() Ignoring Invalid Data....
	 CurrForumId: 46fdb5601deaad434feb0a65989af611 != msg.GroupId: 46fdb5601deaad434feb0a65989af611
	 or CurrThdId: 00336653e5f5eb26582dedd44ee61fe0a081352c != msg.MsgId: cf13f6ef02b32e009d0b2842da0c3710762b1972

[Thread 0x7ffee2ffd700 (LWP 37620) exited]
[New Thread 0x7ffee2ffd700 (LWP 37621)]
Active tokens (this=0x555557fdf2d8): 5577 (4) 
[New Thread 0x7ffee37fe700 (LWP 37622)]
Active tokens (this=0x555557fdf2d8): 5577 (4) 5578 (6) 
[New Thread 0x7fff017fa700 (LWP 37623)]
Active tokens (this=0x555557fdf2d8): 5577 (4) 5578 (6) 5579 (6) 
[New Thread 0x7fff01ffb700 (LWP 37624)]
bool rsGetHostByName(const string&, in_addr&)(EE) getaddrinfo returned error -2 on string "..."
DNSResolver: lookup error for address "..."
[Thread 0x7fff01ffb700 (LWP 37624) exited]
[New Thread 0x7fff01ffb700 (LWP 37625)]
Active tokens (this=0x555557fdf2d8): 5577 (4) 5578 (6) 5579 (6) 5580 (2) 
[New Thread 0x7fff03fff700 (LWP 37626)]
Active tokens (this=0x555557fdf2d8): 5577 (4) 5578 (6) 5579 (6) 5580 (2) 5582 (4) 
[New Thread 0x7fff037fe700 (LWP 37627)]
Active tokens (this=0x555557fdf2d8): 5577 (4) 5578 (6) 5579 (6) 5580 (2) 5582 (4) 5583 (2) 
[New Thread 0x7ffee27fc700 (LWP 37628)]
Active tokens (this=0x555557fdf2d8): 5577 (4) 5578 (6) 5579 (6) 5580 (2) 5582 (4) 5583 (2) 5585 (4) 
[New Thread 0x7ffee1ffb700 (LWP 37629)]
Active tokens (this=0x555557fdf2d8): 5577 (4) 5578 (6) 5579 (6) 5580 (2) 5582 (4) 5583 ([New Thread 0x7ffee17fa700 (LWP 37630)]
2) 5585 (4) 5586 (6) 
Active tokens (this=0x555557fdf2d8): 5577 (4) 5578 (6) 5579 (6) 5580 (2) 5582 (4) 5583 (2) 5585 (4) 5586 (6) 5587 (6) 
(Tue Mar 24 19:07:14 2020 Z: pqisslzone, lvl: 0): pqissl::Basic_Connection_Complete() ENETUNREACH/ETIMEDOUT: cert: .... 
GxsForumThreadWidget::updateMessageData(const RsGxsMessageId&)::<lambda()> no posts for msgId aeb2a6878abf8e170bc3da7cd7d7c5dac0036a15. Database corruption?
```

**Comment by csoler** [comment]
another possibility would be that when you connect to friends the db is hit with big requests to compute the delta between what you an your friend has. If these requests are not made using rsgxsifacehelper there's no way to cancel them.  So I suppose that this can be worked on using different tricks:
- do smaller requests (e.g. only exchange the latest month of posts if the sync happens on that period only)
- have a system to prioritize new requests over existing ones. instead of canceling them.
For now there's a flag tat, when you mke a request, prevents it fro being wiped out. This is a bit dangerous but helps when you request two separate group data in a row. Otherwise the later cancels the former that hasn't time to complete. See rsgxsifacehelper.h

**Comment by csoler** [comment]
it's probably that, becuse once you've let the softare run for 3-4 minutes, then everything is very responsive.

**Comment by sehraf** [comment]
It's running for the whole day now (no crash!) but as soon as i start spam clicking posts and forums it sooner or later locks and doesn't update anything (until a short time - maybe 15-30 secs? and then it responds as expected)

**Comment by csoler** [comment]
Also I've removed the update of GxsGroupFrameDialog on show(), which causes the fact that if the first update fails for some reason, then the list of groups never shows up. It was causing too many db access everytime you closed/open RS's window. I suppose it's possible to check that the widget is already filled in show() before launching update().

**Comment by sehraf** [comment]
Today i saw what matches your explanation: 
Short after start up (maybe 1 to 2 mins?) i opened the channel, forum and boards tabs and nothing was shown (the lists were empty). 
After some time a lot of tokens where queued 
`Active tokens (this=0x55555819adc8): 335 (4) 336 (4) 337 (4) 338 (4) 339 (4) 340 (4) 341 (4) 342 (4) 343 (4) 344 (4) 345 (4) 346 (4) 347 (4) 348 (4) 349 (4) 350 (4) 351 (4) 352 (4) 353 (4) 354 (4) 355 (4) 356 (4) 357 (4) 358 (4) 359 (4) 360 (4) 361 (4) 362 (4) 363 (4) 364 (4) 365 (4) 366 (4) 367 (4) 368 (4) 369 (4) 370 (4) 371 (4) 372 (4) 373 (4) 374 (4) 375 (4)`
and afterwards the forums were displayed as expected

**Comment by sehraf** [comment]
Next observation:
- selected a forums
- many tokens were queued 
- forum is shown (quickly)
- waited for a few seconds (many threads were terminated)
- selected a post
- two tokens are queued
- nothing happens (post is not displayed)
- selected another post
- is instantly displayed
- selected the first post again 
- is instantly displayed

**Comment by sehraf** [comment]
What should i be looking for in the debug output?
When getting *ERROR: Forum could not be loaded. Database might be in heavy use. Please try later.* i can't finde anything like 
*RsDataService::retrieveGxsGrpMetaData() gxsforums_db, Requests: 1, Results: 0, Time: 0*
with a larger time (when it is != 0 it is something like 0.000xxx ...)
So it must be something else.

Also why is time so often (exatcly) 0.000976562 ? is this some float/double side effect or a calculation error?

The biggest time i saw so far was this:
*RsDataService::retrieveGxsGrpMetaData() gxschannels_dbgxsforums_db, Requests: , Requests: 1, Results: 13, Time: 1, Results: 0*
:grin:

**Pull request merged**
