### PR TITLE
More qmake improvements

### PR DESCRIPTION
**Pull request by AsamK**
This PR further improves the qmake build files: The main features:
- Possiblity to install subprojects (gui/nogui) without compiling unneeded subprojects (good to compile nogui on a raspberrypi)
- Add .pri include file for common stuff of all .pro files, so far it contains the default values for the installation paths
- Reduce duplicate code in gui/nogui, by moving LIBS*=… directives to libretroshare (see http://doc.qt.io/qt-5/qmake-advanced-usage.html#libdepend) only done for linux, as i can't test on other platforms
- Treat missing sqlcipher as error, and allow building without it only by using "qmake CONFIG+=NO_SQLCIPHER" (in which case it doesn't link to sqlcipher even if it exists on the system)

For more info see the commit messages.

### CODE REVIEW

**Comment by AsamK** [comment]
Fixed travis build by adding CONFIG+=NO_SQLCIPHER to the travis config. The travis build doesn't have sqlcipher and that is now an error unless NO_SQLCIPHER is specified.

**Comment by thunder2** [comment]
Windows compile is broken with the commits d116f40d6ea9a7c992b0deda0f472f6ac6b27eb2 "Move openpgpsdk to common section of libretroshare.pro" and 829c2f396eb19cde5acb1f92a7ebeb310f63d949 "Move LIBS from gui/nogui linux section to libretroshare".
The libs are needed in the pro file of the binary (gui, nogui) not in the libretroshare.pro.

**Comment by AsamK** [comment]
that's what config+=create_prl and link_prl should be doing, automatically adding the LIBS to all projects that use the library (http://doc.qt.io/qt-5/qmake-advanced-usage.html#libdepend) the docs don't mention anything that this doesn't work on windows.
can you try running qmake -r to regenerate all makefiles?

**Comment by sehraf** [comment]
using qmake with '-r' did the trick on Arch Linux (using Qt4)

**Comment by thunder2** [comment]
I already use -r to build rs and it doesn't work with Qt 4 and Qt 5. I tried it with and without shadow build.
qmake ..\RetroShare.pro -r CONFIG+="release"

**Comment by AsamK** [comment]
can you check that the file libretroshare/src/lib/libretroshare.prl is created in the build directory, and that it contains the necessary LIBS?

unfortunately i don't have an RS build environment set up on windows to test it.

**Comment by thunder2** [comment]
The file exists.

QMAKE_PRL_BUILD_DIR = <path to>/libretroshare/src
QMAKE_PRO_INPUT = libretroshare.pro
QMAKE_PRL_TARGET = libretroshare
QMAKE_PRL_CONFIG = include_source_dir lex yacc warn_on debug uic resources incremental_off thread_off windows debug DebugBuild Debug build_pass warn_on link_prl copy_dir_files debug_and_release debug_and_release_target precompile_header debug stl exceptions rtti mmx 3dnow sse sse2 largefile debug DebugBuild Debug build_pass staticlib bitdht create_prl gxs upnp_miniupnpc debug DebugBuild Debug build_pass no_autoqmake static staticlib
QMAKE_PRL_LIBS = ../../libbitdht/src/lib/libbitdht.a ../../openpgpsdk/src/lib/libops.a -lbz2

**Comment by AsamK** [comment]
Strange, the file is created correctly, just not picked up for the gui/nogui builds. I found the same issue here: https://bugreports.qt.io/browse/QTBUG-12901 no real solution, but they say it works with qt 5.3.

if it doesn't work with qt 5.3 either, i guess you should just readd

```
LIBS += ../../libbitdht/src/lib/libbitdht.a ../../openpgpsdk/src/lib/libops.a -lbz2
```

to the gui/nogui .pro files in the win32 section.

**Comment by thunder2** [comment]
The name of the prl file with Qt 4 and Qt 5 is wrong. It's retroshare.prl and not libretroshare.prl (I was wrong in the previous post).

The link with Qt 4 still fails because the order of the libraries is wrong. I don't know why, but ws2_32 needs to be in LIBS after libbitdht, crypto after libretroshare. Maybe we can add these libraries to the prl file too?
In Qt 4 the libs from prl are added at the end and in Qt 5 at the beginning of LIBS, that's why RS can be linked with Qt 5 when I rename the prl file.

**Comment by thunder2** [comment]
In the sources of qmake I found, that "TARGET_PRL = libretroshare" fixes the name.

**Comment by AsamK** [comment]
Good find with TARGET_PRL, I just set up a windows build here, and that fixed the build with qt5.
To add the ws2_32 to the prl file, just move the "LIBS+=-lws2_32" from retroshare-(no)gui.pro to the win32 section of libretroshare.pro. The bitdht lib in this file is added before the win32 section so this should work

**Comment by thunder2** [comment]
Solved link issues by using "QMAKE_LFLAGS += -Wl,--start-group".
Now the order of the libraries doesn't matter.

**Pull request merged**
