### PR TITLE
V0.6 file lists

### PR DESCRIPTION
**Pull request by mr-alice**
Hi there!

I implemented a new file list system, which has the following characteristics:
- hashes are kept in a "hash cache" that is the only part responsible for hashing files when needed.
- a new service was implemented, named p3filedatabase. The service exchanges directory content between friends when needed.
- the old cache system (cachestrapper, cachesource, etc) have been removed, so is the old file index and fimonitor system
- the file transfer and file search work in compatibility with the existing system, but file lists are not backward compatible.
- friends only get what they are allowed to see, in a way that hides the indexes and all information that may indicate that some files are hidden to them
- all data for hashed files and friend directories is saved encrypted using the SSL key (previously, friend lists were not).

The UI has some new features too:
- hierarchies are kept opened while being updated
- opening a directory triggers an update of it, so you can browse almost interactively if the friend is online
- hierarchies are silently synchronized while friends keep being online
- files immediately appear in the hierarchy, but are displayed in green if not hashed yet
- all GUI accesses to file hierarchies have a constant cost, which improves over the existing log and log-linear costs

It seems stable enough, but it was developed on a Debian system so it is likely to not work out of the box on windows, apple computers and possibly some other distributions (like Ubuntu). Can anyone test it? 

WARNING: it is advised to not use this branch on your regular instance, since configuration files have changed a lot and you may lose some of your configuration.

Among unknowns, it seems that on windows, the daylight saving time causes some problems (https://support.microsoft.com/en-us/kb/190315). In particular the following code is likely to print different timestamps. Can anyone test on windows for me?

If time stamps get to be different depending on when in time we access them, that means Retroshare is going to re-hash its entire database when changing times in autumn or when changing the computer time. What would be the best way to overcome this problem? Creating a temporary file and getting its time, and shifting all access reported by stat64 by the same shift?
# include <iostream>
# include <stdio.h>
# include <stdint.h>
# include <sys/stat.h>

int main(int argc,char *argv[])
{
  std::string fullname = "fname.txt" ;
  FILE *f = fopen(fullname.c_str(),"w") ;

  // create a file
  uint32_t a = 3;
  fwrite(&a,sizeof(uint32_t),1,f) ;
  fclose(f) ;

  // read its time
  struct stat64 buf ;

  if (-1 == stat64(fullname.c_str(), &buf))
   throw std::runtime_error("Error") ;

  // see what the system gives as modification time.
  std::cout << "file time is " << buf.st_mtime << std::endl;
  std::cout << "time now is " << time(NULL) << std::endl;
  return 1;
}

Thank you very much for the feedback!
Mr.Alice

### CODE REVIEW

**Comment by PhenomRetroShare** [comment]
@mr-alice : Please rebase your branch and push it with --force-with-lease
Can you, too, fix unittests?
https://travis-ci.org/RetroShare/RetroShare/builds/161431232#L3780
Thanks for your work.

**Comment by mr-alice** [comment]
I tried to rebase (only conflict was on rstypes.h), but then I got into a real conflict nightmare while trying to git pull from origin before pushing again. I am currently re-creating my local repository from scratch. So no, I cannot rebase sorry.

I will try my best to fix the tests of course.

**Comment by mr-alice** [comment]
It seems that "Travis" does not see my last two commits. Bug?

**Comment by PhenomRetroShare** [comment]
Did you use git pull --rebase ?
You can also make a diff file and patch a new "clean" branch with it. But you'll loose your history.
This what I use to do that:
git diff master > ../`git rev-parse --abbrev-ref HEAD`_`git log -1 --format=%h master`_`date +"%Y%m%d_%H%M%S"`.patch

**Comment by csoler** [comment]
I see no problem with this branch. Seems to work perfectly, at least on Ubuntu. Has anyone tested on windows yet?

About the time shift problem, a simple solution is to always check the time up to +/- 3600 shifts. It's very unlikely (yet possible) that a file changes its modification time of exactly 3600 secs while keeping the same name and size. Having that as an option in Options->Directories would solve it.

**Comment by sehraf** [comment]
I get crashes from time to time when hashing files (rarely but it does happen)
I try to provide more info when available (using gdb now).
Beside that this seems to work just fine. When new folders are made visible/invisible the update takes some time to reach the friends (maybe a few minutes) but this shouldn't be a problem.
One note: maybe the output (to console) can be reduced a bit (though this applies to whole RS - especially the circle code :P )

**Comment by mr-alice** [comment]
It could be due to a missing mutex. If you can spot where it crash, that might give a clue.

**Comment by sehraf** [comment]
```
[directory storage] removing non existing file logo.png at index 6262
[directory storage] removing non existing file fanart.jpg at index 6261
[directory storage] removing non existing file clearart.png at index 6260
FATAL ERROR: getLocalAddresses failed!
[Thread 0x7fffd9b72700 (LWP 12316) exited]

Thread 1 "RetroShare06" received signal SIGSEGV, Segmentation fault.
0x00007ffff3a43a20 in QAbstractEventDispatcherPrivate::allocateTimerId() () from /usr/lib/libQt5Core.so.5
(gdb) where
#0  0x00007ffff3a43a20 in QAbstractEventDispatcherPrivate::allocateTimerId() () from /usr/lib/libQt5Core.so.5
#1  0x00007ffff3a44079 in QAbstractEventDispatcher::registerTimer(int, Qt::TimerType, QObject*) () from /usr/lib/libQt5Core.so.5
#2  0x00007ffff3a744ce in QObject::startTimer(int, Qt::TimerType) () from /usr/lib/libQt5Core.so.5
#3  0x00007ffff3a7f51c in QTimer::start() () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff45b74b9 in ?? () from /usr/lib/libQt5Gui.so.5
#5  0x00007ffff3a724e9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#6  0x00007ffff3a7f568 in QTimer::timerEvent(QTimerEvent*) () from /usr/lib/libQt5Core.so.5
#7  0x00007ffff3a73303 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff51dbe3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff51e35b1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff3a46c80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff3a9a51e in QTimerInfoList::activateTimers() () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff3a9aa79 in ?? () from /usr/lib/libQt5Core.so.5
#13 0x00007ffff722fe67 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#14 0x00007ffff72300d0 in ?? () from /usr/lib/libglib-2.0.so.0
#15 0x00007ffff723017c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#16 0x00007ffff3a9b59b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#17 0x00007ffff3a450da in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#18 0x00007ffff3a4d5cc in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#19 0x0000000000dbc460 in main (argc=1, argv=0x7fffffffe758) at ../../../RetroShare/retroshare-gui/src/main.cpp:419
```

> [directory storage] removing non existing file clearart.png at index 6260
 FATAL ERROR: getLocalAddresses failed!

i've seen this now twice
i'll update to the current version

**Comment by sehraf** [comment]
current version (+ rebase)
```
FATAL ERROR: getLocalAddresses failed!

Thread 1 "RetroShare06" received signal SIGSEGV, Segmentation fault.
0x00007ffff459ce43 in QImageReader::canRead() const () from /usr/lib/libQt5Gui.so.5
(gdb) where 
#0  0x00007ffff459ce43 in QImageReader::canRead() const () from /usr/lib/libQt5Gui.so.5
#1  0x00007ffff45b6844 in ?? () from /usr/lib/libQt5Gui.so.5
#2  0x00007ffff45b736d in ?? () from /usr/lib/libQt5Gui.so.5
#3  0x00007ffff3a724e9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff3a7f568 in QTimer::timerEvent(QTimerEvent*) () from /usr/lib/libQt5Core.so.5
#5  0x00007ffff3a73303 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#6  0x00007ffff51dbe3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff51e35b1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff3a46c80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#9  0x00007ffff3a9a51e in QTimerInfoList::activateTimers() () from /usr/lib/libQt5Core.so.5
#10 0x00007ffff3a9aa79 in ?? () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff722fe67 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#12 0x00007ffff72300d0 in ?? () from /usr/lib/libglib-2.0.so.0
#13 0x00007ffff723017c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#14 0x00007ffff3a9b57f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#15 0x00007ffff3a450da in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#16 0x00007ffff3a4d5cc in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#17 0x0000000000dbc3d0 in main (argc=1, argv=0x7fffffffe758) at ../../../RetroShare/retroshare-gui/src/main.cpp:419
```
interesting:
> FATAL ERROR: getLocalAddresses failed!

happened again!

> QTimer::timerEvent

is involved again

```[gdb]
(gdb) info threads 
  Id   Target Id         Frame 
* 1    Thread 0x7ffff7f0ed40 (LWP 2591) "RetroShare06" 0x00007ffff459ce43 in QImageReader::canRead() const () from /usr/lib/libQt5Gui.so.5
  2    Thread 0x7fffe9549700 (LWP 2595) "AuthGPG" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  3    Thread 0x7fffe5f8b700 (LWP 2596) "QXcbEventReader" 0x00007ffff27cd48d in poll () from /usr/lib/libc.so.6
  4    Thread 0x7fffdbb86700 (LWP 2597) "gmain" 0x00007ffff27cd48d in poll () from /usr/lib/libc.so.6
  5    Thread 0x7fffdb385700 (LWP 2598) "gdbus" 0x00007ffff27cd48d in poll () from /usr/lib/libc.so.6
  6    Thread 0x7fffd9b72700 (LWP 2599) "QDBusConnection" 0x00007ffff27cd48d in poll () from /usr/lib/libc.so.6
  7    Thread 0x7fffc8e14700 (LWP 2600) "RetroShare06" 0x00007ffff333c10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  12   Thread 0x7fffc8105700 (LWP 2611) "RetroShare06" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  13   Thread 0x7fffc7904700 (LWP 2612) "RetroShare06" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  14   Thread 0x7fffc7103700 (LWP 2613) "gxs id" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  15   Thread 0x7fffc6902700 (LWP 2614) "gxs circle" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  16   Thread 0x7fffc6101700 (LWP 2615) "gxs posted" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  17   Thread 0x7fffc5900700 (LWP 2616) "gxs forums" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  18   Thread 0x7fffc50ff700 (LWP 2617) "gxs channels" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  19   Thread 0x7fffc48fe700 (LWP 2618) "gxs id ns" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  20   Thread 0x7fffaffff700 (LWP 2619) "gxs circle ns" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  21   Thread 0x7fffaf7fe700 (LWP 2620) "gxs posted ns" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  22   Thread 0x7fffaeffd700 (LWP 2621) "gxs forums ns" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  23   Thread 0x7fffae7fc700 (LWP 2622) "gxs channels ns" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  24   Thread 0x7fffadffb700 (LWP 2623) "ft extra lst" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  25   Thread 0x7fffad7fa700 (LWP 2624) "RetroShare06" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  26   Thread 0x7fffacff9700 (LWP 2625) "ft ctrl" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  27   Thread 0x7fffa7fff700 (LWP 2626) "ft dataplex" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  28   Thread 0x7fffa77fe700 (LWP 2627) "RetroShare06" 0x00007ffff27a5ffd in nanosleep () from /usr/lib/libc.so.6
  29   Thread 0x7fffa6ffd700 (LWP 2628) "rs main" 0x00007ffff7deeae9 in _dl_close_worker () from /lib64/ld-linux-x86-64.so.2
  30   Thread 0x7fffa67fc700 (LWP 2629) "libmicrohttpd" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  31   Thread 0x7fffa4bf0700 (LWP 2633) "RetroShare06" 0x00007ffff27c94ed in read () from /usr/lib/libc.so.6
  34   Thread 0x7fff96e1d700 (LWP 2660) "pqi 732aa8f1628" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  35   Thread 0x7fff9661c700 (LWP 2661) "pqi 7b401abe0be" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  37   Thread 0x7fff9561a700 (LWP 2664) "pqi c5407c362ed" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  38   Thread 0x7fff94e19700 (LWP 2665) "pqi f7aefb0cc43" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  39   Thread 0x7fff73fff700 (LWP 2666) "pqi 2d4df7f4941" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  41   Thread 0x7fff72ffd700 (LWP 2668) "pqi bb78f0074f1" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  42   Thread 0x7fff727fc700 (LWP 2669) "pqi 595be32ad8c" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  46   Thread 0x7fff53fff700 (LWP 2679) "pqi 02d99473281" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  47   Thread 0x7fff537fe700 (LWP 2680) "pqi 687aea724d8" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  49   Thread 0x7fff527fc700 (LWP 2682) "pqi ed993248422" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  50   Thread 0x7fff51ffb700 (LWP 2683) "pqi ef6aff9c2d1" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  53   Thread 0x7fff33fff700 (LWP 2687) "pqi 281f55dd9d5" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  54   Thread 0x7fff337fe700 (LWP 2688) "pqi 3be5c80f79d" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  56   Thread 0x7fff327fc700 (LWP 2690) "pqi 7b87ddde2b6" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  57   Thread 0x7fff31ffb700 (LWP 2691) "pqi fc20824e6ff" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  58   Thread 0x7fff317fa700 (LWP 2692) "pqi 63d13fffb6d" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  59   Thread 0x7fff30ff9700 (LWP 2693) "pqi b852adac217" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  60   Thread 0x7fff50ff9700 (LWP 2694) "pqi 5070d98ffd7" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  70   Thread 0x7fff52ffd700 (LWP 3101) "pqi 6e2a7db41d5" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  82   Thread 0x7fff0bfff700 (LWP 7725) "pqi bf5b6fdfa9e" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6
  88   Thread 0x7fff32ffd700 (LWP 10202) "pqi b5b87248f93" 0x00007ffff27cf0b3 in select () from /usr/lib/libc.so.6

```

**Comment by sehraf** [comment]
```[gdb]
FATAL ERROR: getLocalAddresses failed!
[Thread 0x7fffd9b90700 (LWP 4421) exited]

Thread 1 "RetroShare06" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7f0ed40 (LWP 4413)]
0x00007ffff386a26b in QThreadStorageData::get() const () from /usr/lib/libQt5Core.so.5
(gdb) where
#0  0x00007ffff386a26b in QThreadStorageData::get() const () from /usr/lib/libQt5Core.so.5
#1  0x00007ffff45e0aff in ?? () from /usr/lib/libQt5Gui.so.5
#2  0x00007ffff45e0c74 in QFontPrivate::engineForScript(int) const () from /usr/lib/libQt5Gui.so.5
#3  0x00007ffff45ff083 in QFontMetricsF::height() const () from /usr/lib/libQt5Gui.so.5
#4  0x00000000010bb1de in DHTStatus::getDHTStatus (this=0x4a9f2f0) at ../../../RetroShare/retroshare-gui/src/gui/statusbar/dhtstatus.cpp:83
#5  0x0000000000e0a1a8 in MainWindow::updateStatus (this=0x3ff2920) at ../../../RetroShare/retroshare-gui/src/gui/MainWindow.cpp:693
#6  0x00000000012a4d3b in MainWindow::qt_static_metacall (_o=0x3ff2920, _c=QMetaObject::InvokeMetaMethod, _id=13, _a=0x7fffffffda10) at temp/moc/moc_MainWindow.cpp:214
#7  0x00007ffff3a714e9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff3a7e568 in QTimer::timerEvent(QTimerEvent*) () from /usr/lib/libQt5Core.so.5
#9  0x00007ffff3a72303 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#10 0x00007ffff51dae3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff51e25b1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff3a45c80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#13 0x00007ffff3a9951e in QTimerInfoList::activateTimers() () from /usr/lib/libQt5Core.so.5
#14 0x00007ffff3a99a79 in ?? () from /usr/lib/libQt5Core.so.5
#15 0x00007ffff722fe67 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#16 0x00007ffff72300d0 in ?? () from /usr/lib/libglib-2.0.so.0
#17 0x00007ffff723017c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#18 0x00007ffff3a9a57f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#19 0x00007ffff3a440da in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff3a4c5cc in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#21 0x0000000000dbc3d0 in main (argc=1, argv=0x7fffffffe758) at ../../../RetroShare/retroshare-gui/src/main.cpp:419
(gdb) info threads 
  Id   Target Id         Frame 
* 1    Thread 0x7ffff7f0ed40 (LWP 4413) "RetroShare06" 0x00007ffff386a26b in QThreadStorageData::get() const () from /usr/lib/libQt5Core.so.5
  2    Thread 0x7fffe9548700 (LWP 4417) "AuthGPG" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  3    Thread 0x7fffe5f8a700 (LWP 4418) "QXcbEventReader" 0x00007ffff27cc48d in poll () from /usr/lib/libc.so.6
  4    Thread 0x7fffdbb86700 (LWP 4419) "gmain" 0x00007ffff27cc48d in poll () from /usr/lib/libc.so.6
  5    Thread 0x7fffdb385700 (LWP 4420) "gdbus" 0x00007ffff27cc48d in poll () from /usr/lib/libc.so.6
  7    Thread 0x7fffc8e14700 (LWP 4428) "RetroShare06" 0x00007ffff333b10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  12   Thread 0x7fffc8105700 (LWP 4453) "RetroShare06" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  13   Thread 0x7fffc7904700 (LWP 4454) "RetroShare06" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  14   Thread 0x7fffc7103700 (LWP 4462) "gxs id" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  15   Thread 0x7fffc6902700 (LWP 4463) "gxs circle" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  16   Thread 0x7fffc6101700 (LWP 4464) "gxs posted" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  17   Thread 0x7fffc5900700 (LWP 4465) "gxs forums" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  18   Thread 0x7fffc50ff700 (LWP 4466) "gxs channels" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  19   Thread 0x7fffc48fe700 (LWP 4467) "gxs id ns" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  20   Thread 0x7fffaffff700 (LWP 4468) "gxs circle ns" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  21   Thread 0x7fffaf7fe700 (LWP 4469) "gxs posted ns" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  22   Thread 0x7fffaeffd700 (LWP 4470) "gxs forums ns" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  23   Thread 0x7fffae7fc700 (LWP 4471) "gxs channels ns" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  24   Thread 0x7fffadffb700 (LWP 4472) "ft extra lst" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  25   Thread 0x7fffad7fa700 (LWP 4473) "RetroShare06" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  26   Thread 0x7fffacff9700 (LWP 4474) "ft ctrl" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  27   Thread 0x7fffa7fff700 (LWP 4475) "ft dataplex" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  28   Thread 0x7fffa77fe700 (LWP 4476) "RetroShare06" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  29   Thread 0x7fffa6ffd700 (LWP 4477) "rs main" 0x00007ffff7de9ca0 in _dl_debug_state () from /lib64/ld-linux-x86-64.so.2
  30   Thread 0x7fffa67fc700 (LWP 4541) "libmicrohttpd" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  86   Thread 0x7fff597fa700 (LWP 23228) "pqi 2d4df7f4941" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  87   Thread 0x7fff777fe700 (LWP 23229) "pqi 732aa8f1628" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  88   Thread 0x7fff59ffb700 (LWP 23232) "pqi 6e2a7db41d5" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  89   Thread 0x7ffefb7fe700 (LWP 23233) "pqi 7b401abe0be" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  90   Thread 0x7fffa4bf0700 (LWP 23234) "pqi 595be32ad8c" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  91   Thread 0x7fff8ee1d700 (LWP 23235) "pqi 6e55146a199" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  92   Thread 0x7fff8e61c700 (LWP 23236) "pqi c5407c362ed" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  93   Thread 0x7fff8de1b700 (LWP 23239) "pqi f7aefb0cc43" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  94   Thread 0x7fff8d61a700 (LWP 23240) "pqi 02d99473281" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  96   Thread 0x7fff77fff700 (LWP 23242) "pqi bb78f0074f1" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  97   Thread 0x7fff76ffd700 (LWP 23243) "pqi 003caf0ae71" 0x00007ffff27a4ffd in nanosleep () from /usr/lib/libc.so.6
  98   Thread 0x7fff767fc700 (LWP 23248) "pqi b5b87248f93" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  99   Thread 0x7fff75ffb700 (LWP 23249) "pqi b852adac217" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  100  Thread 0x7fff757fa700 (LWP 23250) "pqi c332c791f1e" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  101  Thread 0x7fff74ff9700 (LWP 23251) "pqi f2fd0b3586b" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  102  Thread 0x7fff5bfff700 (LWP 23252) "pqi fc20824e6ff" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  104  Thread 0x7fff5affd700 (LWP 23254) "pqi 281f55dd9d5" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  105  Thread 0x7fff5a7fc700 (LWP 23255) "pqi 63d13fffb6d" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  106  Thread 0x7fff58ff9700 (LWP 23256) "pqi 687aea724d8" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  107  Thread 0x7fff37fff700 (LWP 23257) "pqi 7b60fedccf9" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  108  Thread 0x7fff377fe700 (LWP 23258) "pqi ed993248422" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  109  Thread 0x7fff36ffd700 (LWP 23263) "pqi 5070d98ffd7" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  110  Thread 0x7fff367fc700 (LWP 23276) "pqi 3be5c80f79d" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  111  Thread 0x7fff35ffb700 (LWP 23468) "pqi 3703c4e23e2" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  115  Thread 0x7fff8ce19700 (LWP 24522) "pqi 20baac5f363" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
  116  Thread 0x7fff5b7fe700 (LWP 24681) "pqi 118bc88bec0" 0x00007ffff27ce0b3 in select () from /usr/lib/libc.so.6
```

**Comment by sehraf** [comment]
I've deleted the crashes since they were unrelated and are fixed now

**Comment by csoler** [comment]
Apparently there's a FD leak in folderiterator.cc:153, since the folder iterator is not valid anymore at the end of reading the entire directory. Therefore the function returns even before closing the dir ;-)

**Comment by hunbernd** [comment]
Testing on Windows...
There are some compile errors, but nothing serious so far.

**Pull request merged**
