### PR TITLE
add travis file

### PR DESCRIPTION
**Pull request by chozabu**

### CODE REVIEW

**Comment by cavebeat** [comment]
+1
I'll try to add a Organization Travis Account when the MR is implemented.

**Comment by chozabu** [comment]
what is "the MR"?

**Comment by cavebeat** [comment]
PR = Pull Request(GitHub) and MR = Merge Request (GitLab/Gitorious)
i use them synonym

**Comment by csoler** [comment]
why use libsqlite3-dev instead of libsqlcipher-dev as a dependency?

**Comment by cavebeat** [comment]
@csoler 
E: Unable to locate package libsqlcipher-dev 
https://travis-ci.org/cavebeat/RetroShare/builds/73695371#L672

Because the Build Environment of Travis runs on Ubuntu 12.04 LTS, there is no libsqlcipher-dev package available. 
http://packages.ubuntu.com/search?suite=precise&keywords=libsqlcipher-dev

**Pull request merged**
