### PR TITLE
Change RetroShare06 to lower case

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
This is important to comply with linux standards.

### CODE REVIEW

**Comment by sehraf** [comment]
while you are right, this might break anything that is relying on the executable's name.

**Comment by PhenomRetroShare** [comment]
It's on Cyril todo ;)

**Comment by sehraf** [comment]
That comment was not meant to stop the PR - i'd just like to point out that it could lead to people complaining 😉

**Comment by csoler** [comment]
If you get the time, could you also remove the 06 suffix? It was meant to allow to use both 05 and 06 on the same computer, but that is not needed anymore.

**Pull request merged**
