### PR TITLE
Removed compiler warnings in libretroshare

### PR DESCRIPTION
**Pull request by thunder2**

### CODE REVIEW

**Review by thunder2 — COMMENTED** [review]
Is the function getCurrentTS needed anymore?

**Review by thunder2 — COMMENTED** [review]
The parameter req_result_count of p3turtle::performLocalSearch_generic looks like an output parameter which is not initialized.

**Comment by csoler** [comment]
> The parameter req_result_count of p3turtle::performLocalSearch_generic looks like an output parameter which is not initialized.

I think that's because the generic search result item obfuscates the number of search results. I suppose it would be possible to add a virtual method in this item type that returns the correct number everytime.

**Comment by csoler** [comment]
> Is the function getCurrentTS needed anymore?

There's a dozen of copies of this function throughout the code. Would be nice to clean that up, only using one from rstime.h

**Pull request merged**
