### PR TITLE
Fix Change Font for Links on Chat.

### PR DESCRIPTION
**Pull request by PhenomRetroShare**

### CODE REVIEW

**Comment by csoler** [comment]
what does this fixes exactly?

**Comment by PhenomRetroShare** [comment]
When you change font for a link in chat text edit, the link is loose transformed as plain text.

**Comment by defnax** [comment]
when this will be merged?

**Comment by PhenomRetroShare** [comment]
@csoler ;)

**Comment by defnax** [comment]
@csoler

**Comment by defnax** [comment]
@csoler

**Comment by csoler** [comment]
This PR works, but for some reason I had to create a new one with the same code (problem with submodules), which is PR 2676.

**Pull request closed without merging**
