### PR TITLE
Add StatusBar and its widgets hide options.

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
The StatusBar is hidden by default.

### CODE REVIEW

**Comment by felisucoibi** [comment]
love it, thanks!

**Comment by defnax** [comment]
i dont agree it, statusbar needs to be visible by default, for experts maybe they neeed settings.
and now retrohare goes overfloated with lots settings.
i dont know why work on some code, to hide some stuff, instead of help on importend things.

**Comment by felisucoibi** [comment]
I tested it, IT'S PERFECT! i already added to my fork!

**Comment by csoler** [comment]
It's very nice to have. I just would like it more consistent:
- make all the "hide" checkboxes to be a "show" (the parent checkbox "status bar" acts a a disabling item, so the buttons below should be to *show*, not to *hide*).
- check them by default
Then, in the first time start, we may uncheck them automatically if needed, but they should appear by default when running the softare.

thx!

**Comment by PhenomRetroShare** [comment]
Done

**Comment by RetroPooh** [comment]
Hi. natstatus and dhtstatus should be hidden permanently when running hidden node.
discovery exchange display is currently disabled for hidden nodes - is it bug or as intended?

**Pull request merged**
