### PR TITLE
Darkstylesheet fixes

### PR DESCRIPTION
**Pull request by defnax**
Fixed some wrong url path.
Fixed the background of the labels to be transparent

### CODE REVIEW

**Comment by felisucoibi** [comment]
+10000

**Comment by defnax** [comment]
> +10000

normally this things can be fixed by you :)

**Comment by felisucoibi** [comment]
i tried to modify dark themes to change blue link color (a href) to another color and i was not able, i tried hard, maybe you can do it.
default blue with balck backgruond is impossible to read.

Also there are some missing or invisible icons in tree filelists and other tree componetns of rs.

**Comment by defnax** [comment]
> i tried to modify dark themes to change blue link color (a href) to another color and i was not able, i tried hard, maybe you can do it.
> default blue with balck backgruond is impossible to read.

that links color is hardcoded but it can be changed to use light blue
> 
> Also there are some missing or invisible icons in tree filelists and other tree componetns of rs.

i has fixed the tree icons which was missed, i doesnt looked on filelist.

**Comment by felisucoibi** [comment]
i really triend to remove this blue, is in lot of places, but i read wasnot possible globally, i really tried and i'm not a programmer of this century at least. :page_facing_up: 
I think is not fixed in fiellists.

**Comment by defnax** [comment]
> I think is not fixed in fiellists.
 
why you not make screenshots? then we see it better

here with the changes:
image

**Comment by felisucoibi** [comment]
I'm using qdarkstye

imagen

**Comment by felisucoibi** [comment]
The blue in news feed for example impossible to read.
imagen
And the blue in links in forums etc.
imagen

**Comment by defnax** [comment]
> I'm using qdarkstye
> 
> imagen

thats is fixed on master

**Comment by defnax** [comment]
> The blue in news feed for example impossible to read.
> imagen
> And the blue in links in forums etc.
> imagen

maybe need to check if using a dark styleesheet or else use a different href color light blue or else

**Pull request merged**
