### PR TITLE
Fix RsCertificate::toStdString by fixing PGPKeyParser::read_125Size.

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
And added some comments, plus values in hexadecimal for better view.

### CODE REVIEW

**Comment by csoler** [comment]
you changed base 10 values for base 16. Fine. But how does this fix the cert bug??

**Comment by csoler** [comment]
ok ;-) thx

**Comment by csoler** [comment]
actually this was wrong. See the latest commits, where I think I made it right. I also removed the hexa, since RFC4880 uses decimal values, and it's easier to correlate it with the code if using non hexa.

**Comment by PhenomRetroShare** [comment]
But you don't take care of "negative" value...
See my uint8_t(b2 + 0xC0) to get addition in byte.

**Comment by csoler** [comment]
you don't need to. Read RFC4880: the value needs to be shifted down by 192, _then_ converted to bytes.

**Comment by PhenomRetroShare** [comment]
OK, it works fine now.

But why did you break indent char? ;)

**Pull request merged**
