### PR TITLE
Fix MSys2 Windows Compilation after #f1847a9 commit.

### PR DESCRIPTION
**Pull request by PhenomRetroShare**
As used by AppVeyor.

### CODE REVIEW

**Comment by thunder2** [comment]
When I compile in MSYS2 environment the variable MINGW_PREFIX is set. Why do you need this?
When MSYS2 is not used the message "MINGW_PREFIX is empty. Set it in your environment variables." is annoying.

**Comment by PhenomRetroShare** [comment]
Because I use QtCreator ;)

**Comment by PhenomRetroShare** [comment]
And even AppVeyor can't compil it too!!!
This is the referent to see if code is compilable.
I'll make a modification to remove this message.

**Comment by PhenomRetroShare** [comment]
Done.

**Comment by thunder2** [comment]
That's fine. Thank you.

I use MinGW from MSYS2 directly from the Windows commandline with a batch file like this. All environment variables from MSYS2 are set.

set MSYS2Dir=C:\msys32
set MSYS2SH=%MSYS2Dir%\usr\bin\sh

set MSYS2CurPath=%cd%
set MSYS2CurPath=/%MSYS2CurPath:~0,1%/%MSYS2CurPath:~3%
set MSYS2CurPath=%MSYS2CurPath:\=/%

set MSYSTEM=MINGW32

"%MSYS2SH%" -lc "cd %MSYS2CurPath% && <command to execute e.g. %2>"
exit /b %ERRORLEVEL%

**Pull request merged**
